// resource.h - the editor's dialog template and control identifiers, as
// the image's .rsrc dialogs and their users' DDX and GetDlgItem calls
// spell them. The original resource.h is not recorded: the names follow
// the AppWizard IDD_/IDC_ style from each control's role.
#ifndef HOMM3_EDITOR_RESOURCE_H
#define HOMM3_EDITOR_RESOURCE_H

enum {
    IDD_EDIT_RUMOR = 167,
    IDD_SIGN_PROPS = 171,
    IDD_FLAGGABLE_PROPS = 207,
    IDD_SELECT_ARTIFACT = 256,
    IDD_OPTIONS = 304
};

enum {
    IDC_RUMOR_TEXT_EDIT = 1073,
    IDC_RUMOR_NAME_EDIT = 1074,
    IDC_SIGN_MESSAGE_EDIT = 1087,
    IDC_OWNER_NONE_RADIO = 1207,
    IDC_ARTIFACT_LIST = 1263,
    IDC_OWNER_PLAYER1_RADIO = 1336,
    IDC_OWNER_PLAYER2_RADIO = 1337,
    IDC_OWNER_PLAYER3_RADIO = 1338,
    IDC_OWNER_PLAYER4_RADIO = 1339,
    IDC_OWNER_PLAYER5_RADIO = 1340,
    IDC_OWNER_PLAYER6_RADIO = 1341,
    IDC_OWNER_PLAYER7_RADIO = 1342,
    IDC_OWNER_PLAYER8_RADIO = 1343,
    IDC_AUTOSAVE_CHECK = 1586,
    IDC_AUTOSAVE_MINUTES_EDIT = 1587,
    IDC_AUTOSAVE_MINUTES_SPIN = 1588,
    IDC_TILE_FREQUENCY_SLIDER = 1598,
    IDC_REPAINT_CHECK = 1599,
    IDC_OWNER_STATIC = 1639,
    IDC_SIGN_MESSAGE_STATIC = 1641,
    IDC_RUMOR_NAME_STATIC = 1670,
    IDC_RUMOR_TEXT_STATIC = 1671,
    IDC_TILE_FREQUENCY_STATIC = 1708,
    IDC_TILE_FREQUENCY_NONE_STATIC = 1709,
    IDC_TILE_FREQUENCY_LOTS_STATIC = 1710,
    IDC_AUTOSAVE_OPTIONS_STATIC = 1711,
    IDC_AUTOSAVE_EVERY_STATIC = 1712,
    IDC_AUTOSAVE_MINUTES_STATIC = 1713
};

#endif  /* HOMM3_EDITOR_RESOURCE_H */
