"""homm3 loki-game: the Loki Linux game 1.3.1a as evidence for the Windows game.

  init [--exe PATH]
        verify and stage heroes3.dynamic (HOMM3_LOKI_HEROES3) at build/orig/loki/
  census
        headless Ghidra census: functions, calls and data references
        (build/heroes3-loki/census/; Java runs with -Djava.awt.headless=true)
  profile [TAG ...]
        compile the proof units (config/loki/game.toml [proof]) under each flag
        variant with the staged GCC 2.95.2 (`homm3 loki toolchain`) and count
        the unique exact bodies found in the image
  pair [--no-fingerprint]
        pair Loki functions with Windows functions (homm3.loki_game.pair) and
        write config/retail/heroes3-loki/functions.tsv; prints counts by evidence
  vtables
        write config/retail/heroes3-loki/vtables.tsv from the image's RTTI
  calls WIN_RVA [LOKI_ADDRESS]
        ordered callees of a paired function on both sides, Loki callees
        annotated with their Windows pair and whether Windows calls it
  compile UNIT ... [--scan]
        compile src/UNIT.cpp at the game profile (build/heroes3-loki/objects/)
        and, with --scan, search its bodies in the image
"""
from __future__ import annotations

import argparse
import sys


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="homm3 loki-game", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    p = sub.add_parser("init")
    p.add_argument("--exe")
    sub.add_parser("census")
    p = sub.add_parser("profile")
    p.add_argument("tags", nargs="*")
    p = sub.add_parser("pair")
    p.add_argument("--no-fingerprint", action="store_true")
    sub.add_parser("vtables")
    p = sub.add_parser("compile")
    p.add_argument("units", nargs="+")
    p.add_argument("--scan", action="store_true")
    p = sub.add_parser("calls")
    p.add_argument("win")
    p.add_argument("loki", nargs="?")
    args = parser.parse_args(argv)
    try:
        if args.command == "init":
            from homm3.loki_game.image import stage
            print(f"[loki-game] image: {stage(args.exe)}")
        elif args.command == "census":
            from homm3.loki_game import census
            print(f"[loki-game] census: {census.run()}")
        elif args.command == "profile":
            from homm3.loki_game import scan
            variants = scan.profile_spec()["proof"]["variants"]
            if args.tags:
                variants = {t: variants[t] for t in args.tags}
            scan.profile(variants)
        elif args.command == "pair":
            from homm3.loki_game import pair
            pairing = pair.Pairing()
            counts = pairing.run([] if args.no_fingerprint else pair.default_objects())
            pairing.write()
            print(f"[loki-game] {sum(counts.values())} pairs: " +
                  ", ".join(f"{k} {v}" for k, v in counts.most_common()))
        elif args.command == "vtables":
            return _vtables()
        elif args.command == "compile":
            return _compile(args.units, args.scan)
        elif args.command == "calls":
            return _calls(int(args.win, 16), int(args.loki, 16) if args.loki else None)
    except (ValueError, OSError, RuntimeError, KeyError) as exc:
        print(f"[loki-game] ERROR: {exc}", file=sys.stderr)
        return 2
    return 0


def _compile(units: list[str], scan: bool) -> int:
    from homm3.loki_game import compile as cc
    rc = 0
    for unit in units:
        obj, diagnostics = cc.compile_unit(unit)
        errors = [line for line in diagnostics.splitlines() if ": " in line and "In file included" not in line]
        if not obj.is_file() or errors and "error" in diagnostics.lower():
            print(f"[loki-game] {unit}: compile failed")
            for line in errors[:20]:
                print("  " + line.replace(str(cc.ROOT) + "/", ""))
            rc = 1
            continue
        print(f"[loki-game] {unit}: {obj}")
        if scan:
            from homm3.loki_game.scan import Scanner
            for name, size, hits in Scanner().scan([obj]):
                where = f"0x{hits[0]:08x}" if len(hits) == 1 else f"{len(hits)} hits"
                print(f"  {size:6} {where:>12} {name}")
    return rc


def _vtables() -> int:
    from homm3.loki_game import rtti
    from homm3.loki_game.image import RETAIL
    rows = ["# GENERATED by `homm3 loki-game vtables`: each vtable the RTTI type_info functions",
            "# anchor (zero word, __tf slot, virtual functions in slot order).",
            "address\ttype_name\ttf\tslots"]
    for v in sorted(rtti.vtables(), key=lambda v: v.address):
        rows.append(f"0x{v.address:08x}\t{v.type_name}\t0x{v.tf:08x}\t" +
                    ",".join(f"0x{s:08x}" for s in v.slots))
    (RETAIL / "vtables.tsv").write_text("\n".join(rows) + "\n")
    print(f"[loki-game] {len(rows) - 3} vtables")
    return 0


def _calls(win: int, loki: int | None) -> int:
    from homm3.loki_game import pair, refs
    from homm3.loki_game.image import LokiGame
    pairs = pair.load()
    W, K, ledger = refs.windows(), refs.loki(), refs.ledger()
    plt = LokiGame().plt
    k2w = {k: w for w, (k, _) in pairs.items()}
    if loki is None:
        if win not in pairs:
            print(f"[loki-game] 0x{win:x} is not paired", file=sys.stderr)
            return 1
        loki = pairs[win][0]

    def name(w):
        return ledger.get(w, {}).get("name", f"sub_{w:x}")
    print(f"WIN 0x{win:x} {name(win)} ({W[win].size} bytes)")
    for c in W[win].calls:
        tail = f"  = loki 0x{pairs[c][0]:x}" if c in pairs else ""
        print(f"  -> 0x{c:06x} {name(c)[:100]}{tail}")
    print(f"LOKI 0x{loki:x} ({K[loki].size} bytes)")
    called = set(W[win].calls)
    for c in K[loki].calls:
        if c in plt:
            print(f"  -> plt {plt[c]}")
            continue
        w = k2w.get(c)
        size = K[c].size if c in K else "?"
        if w is None:
            print(f"  -> 0x{c:x} ({size} bytes) unpaired")
        else:
            seen = "Windows calls it" if w in called else "Windows expands or omits it"
            print(f"  -> 0x{c:x} ({size} bytes) {name(w)[:90]} [{seen}]")
    return 0


def logged_main(argv=None) -> int:
    from homm3.core import paths
    from homm3.core.usage import append, run_logged
    import shlex
    argv = list(sys.argv[1:] if argv is None else argv)
    cmd = shlex.join(["homm3", "loki-game", *argv])
    return run_logged(main, argv,
                      lambda rc, **meta: append(paths.SHARED_BUILD / "homm3_usage.log",
                                                cmd, rc, **meta))


if __name__ == "__main__":
    raise SystemExit(logged_main())
