#!/usr/bin/env python3
"""ONE-OFF carve admission (not a pipeline actor) - admit the EH-funclet
and init-array inventories into config/.

Both are once-generated carve products (user decision 2026-08-04: such
inventories belong in config, not behind a live carve walk):

  config/retail-funclets.tsv     rva, parent_rva, state - every FuncInfo
                                 unwind-action funclet in the pinned image
                                 (retail EH metadata walk) with the
                                 function whose FuncInfo owns it (retail
                                 reloc evidence; `-` where unresolved).
  config/retail-init-thunks.tsv  rva, slot - the `.CRT$XCU` initializer
                                 bodies in slot order (the carve
                                 init-array walk; includes the 26 LIBCPMT
                                 facet ctors at the tail - consumers
                                 classify by their own precedence).

After this admission the runtime pipeline (homm3.match.universe) reads
these tables and calls nothing in homm3.carve; the stage refuses to
overwrite the hand-owned outputs unless --force is given.
"""
from __future__ import annotations

import sys

from homm3.carve import audit, common
from homm3.carve.naming import eh_parentage

FUNCLETS_OUT = common.HOMM3_DIR / "config/retail-funclets.tsv"
INIT_OUT = common.HOMM3_DIR / "config/retail-init-thunks.tsv"

STAMP = ("# MANUALLY MANAGED - INITIALLY GENERATED by `python3 -m "
         "homm3.carve.funclets`\n# (provenance below) and hand-owned after "
         "admission: corrections are edited\n# directly into these rows; "
         "do not regenerate over hand edits.\n")


def main(argv=None) -> int:
    argv = list(argv or [])
    force = "--force" in argv
    for target in (FUNCLETS_OUT, INIT_OUT):
        if target.is_file() and not force:
            common.die(f"{target} already exists and is hand-owned - "
                       "rerun with --force only if you mean to regenerate")

    functions = {}
    for line in (common.HOMM3_DIR / "config/retail-functions.tsv").open():
        if line[0] not in "#r":
            rva, size = line.split()
            functions[int(rva, 16)] = int(size)
    entries = sorted(functions)

    import bisect

    def owner_of(rva):
        i = bisect.bisect_right(entries, rva) - 1
        if i >= 0 and entries[i] <= rva < entries[i] + functions[entries[i]]:
            return entries[i]
        return None

    image, _info = common.load_image()
    _fi, funclets, _missing = audit.gate_eh_funclets(image, set(functions))
    parent = eh_parentage(image, entries, owner_of)

    provenance = "\n".join(common.provenance("homm3.carve.funclets"))
    rows = []
    orphans = 0
    for rva in sorted(funclets):
        p = parent.get(rva)
        if p is None:
            rows.append(f"0x{rva:x}\t-\t-")
            orphans += 1
        else:
            rows.append(f"0x{rva:x}\t0x{p[0]:x}\t{p[1]}")
    FUNCLETS_OUT.write_text(
        STAMP + provenance + "\n"
        + "# rva = funclet entry; parent_rva = the function whose FuncInfo\n"
        "# owns it (matches with its parent); state = unwind state index.\n"
        + "rva\tparent_rva\tstate\n" + "\n".join(rows) + "\n")

    seed_log = common.CARVE_DIR / "seed_log.tsv"
    init_rows = []
    for r in common.read_tsv(common.need(seed_log, "ghidra")):
        if r["run"] == "1" and r["iter"] == "1" \
                and r["source"] == "init-array":
            target = int(r["target_rva"], 16)
            if target in functions:
                init_rows.append(f"0x{target:x}\t{len(init_rows)}")
    INIT_OUT.write_text(
        STAMP + provenance + "\n"
        + "# `.CRT$XCU` initializer bodies in slot (link) order.\n"
        + "rva\tslot\n" + "\n".join(init_rows) + "\n")

    print(f"[carve funclets] {len(rows)} funclets ({orphans} without a "
          f"resolved parent) -> {FUNCLETS_OUT.name}; "
          f"{len(init_rows)} init thunks -> {INIT_OUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
