// Bind only scalar domains and the request record; never C++ object ownership.
#include "rmg_request.h"
#include "terrain_type.h"
#include "artifact_type.h"
#include "rmg_line_pattern.h"
#include "tile_direction.h"
#include "game_resource.h"
#include "rmg_columns.h"
#include "rmg_terrain_data.h"
#include "adventure_object_type.h"
#include "adventure_object_data.h"
#include "objectmask.h"
#include "spellschool.h"
#include "keycolor.h"
