"""homm3 worktree - create and remove ready-to-match linked worktrees.

    homm3 worktree new PATH [-b BRANCH] [--from REF] [--seed-from DIR]
                            [--no-seed] [--no-objects]
    homm3 worktree remove PATH [--delete-branch]

`new` replaces the manual lane bootstrap (git worktree add, toolchain
symlink, executable staging, Mac SDK copy, a full build before `--fast`):

1. `git worktree add [-b BRANCH] PATH [REF]` in the current checkout's repo.
2. Link the shared VC6 toolchain directory and the VC6 RTM compiler overlay
   from the seed checkout (default: the repository's main worktree) and copy
   its verified Mac SDK; the SDK stager rejects symlinks, so it is a real copy.
3. Run the new tree's own `homm3 init --no-smoke` with the seed's staged
   executables and CodeWarrior tools (hash-verified on staging, no download).
   Each editor image (`homm3 --image KEY init`) is staged from the seed's
   copy or its `$HOMM3_<KEY>_EXE` override, with the seed's SP3 MFC overlay
   or `$HOMM3_MFC_SP3`; an image with neither is reported, since a full
   `homm3 build` refuses to run without it.
4. Seed comparison state so `homm3 build --fast TU` works immediately:
   * retail targets, normalized copies and build/gen label/model outputs
     from the seed. Targets come from the retail executable pinned in both
     trees' config/project.toml and from the seed's last delink, so they
     carry the symbol names of the seed's source claims at that time.
     Normalized copies carry provenance stamps; stale ones are rebuilt.
   * every base object whose compile receipt (source, scanned headers,
     toolchain, flags, wrapper bytes) matches the new tree's files exactly,
     taken from the seed or any other worktree of the repository.
5. Run `ninja objects` in the new tree. Seeded objects are adopted by
   cc_wrap's receipt check without invoking Wine, so Ninja records its own
   log and header dependencies; objects no checkout could supply compile.
6. Run `homm3 delink` in the new tree (about two minutes): retail targets,
   build/gen labels and normalized copies then describe the new tree's own
   source claims, so `homm3 build --fast TU` equals a full build. The seed's
   targets and build/gen carry the seed's claims from its last delink, which
   can be arbitrarily old; `--no-delink` keeps them (scores of renamed or
   re-claimed functions are then not comparable, and `homm3 status update`
   must not bank them).

`remove` refuses a worktree with uncommitted or untracked changes, stops its
Wine server, and runs `git worktree remove`; `--delete-branch` then deletes
the branch with `git branch -d` (which refuses unmerged work).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import time

from homm3.core import common
from homm3.core.project import Project
from homm3.core.root import project_root

TOOLCHAIN = Path("build/homm3-toolchain-vc6-sp3")
# The VC6 RTM compiler overlay of the zlib units (homm3.init.vc6_rtm).
RTM_TOOLCHAIN = Path("build/homm3-toolchain-vc6-rtm")
MAC_SDK = Path("build/mac/sdk")
MAC_TOOLCHAIN = Path("build/mac/toolchain")
OBJDIFF = Path("build/objdiff")
GEN = Path("build/gen")
# Generated by the new tree's own init (compilation database); never copied.
GEN_SKIP = {"msvc-include", ".msvc-include.lock"}
RECEIPT_SUFFIX = ".inputs.json"


class WorktreeError(RuntimeError):
    pass


def log(message: str) -> None:
    print(f"[worktree] {message}", flush=True)


def _git(repo: Path, *args: str, capture: bool = True) -> str:
    result = subprocess.run(["git", "-C", str(repo), *args], text=True,
                            capture_output=capture)
    if result.returncode:
        detail = (result.stderr or result.stdout or "").strip() if capture else ""
        raise WorktreeError(f"git {' '.join(args)} failed" + (f": {detail}" if detail else ""))
    return result.stdout if capture else ""


def worktrees(repo: Path) -> list[dict]:
    """`git worktree list --porcelain` entries; the first is the main worktree."""
    entries, entry = [], {}
    for line in _git(repo, "worktree", "list", "--porcelain").splitlines() + [""]:
        if not line:
            if entry:
                entries.append(entry)
            entry = {}
            continue
        key, _, value = line.partition(" ")
        entry[key] = value or True
    return entries


def _environment(tree: Path) -> dict:
    env = dict(os.environ)
    env.pop("HOMM3_DIR_FORCE", None)
    env["HOMM3_DIR"] = str(tree)
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    env["PYTHONPATH"] = os.pathsep.join(
        [str(tree / "scripts")] + ([env["PYTHONPATH"]] if env.get("PYTHONPATH") else []))
    return env


def _run_in(tree: Path, *command: str) -> int:
    return subprocess.run(list(command), cwd=tree, env=_environment(tree)).returncode


def _homm3(tree: Path, *args: str) -> int:
    return _run_in(tree, sys.executable, "-m", "homm3", *args)


def _find_ci(directory: Path, name: str) -> Path | None:
    if not directory.is_dir():
        return None
    return next((p for p in directory.iterdir() if p.name.lower() == name.lower()), None)


# --------------------------------------------------------------- receipts

class _Hashes:
    """Content digests of the new tree's files, read once each."""

    def __init__(self):
        self.cache: dict[str, str | None] = {}

    def __call__(self, path: str) -> str | None:
        if path not in self.cache:
            try:
                digest = hashlib.sha256()
                with open(path, "rb") as stream:
                    for block in iter(lambda: stream.read(1 << 20), b""):
                        digest.update(block)
                self.cache[path] = digest.hexdigest()
            except OSError:
                self.cache[path] = None
        return self.cache[path]


class _Origin:
    """Receipt translation from one checkout into the new tree.

    Every receipt repeats the toolchain, wrapper and manifest inputs, so a
    recorded input that differed once rejects the origin's other receipts
    without rereading them.
    """

    def __init__(self, origin: Path, tree: Path, hashes):
        self.origin = os.fspath(origin.resolve()) + os.sep
        self.tree = tree
        self.hashes = hashes
        self.mapped: dict[str, str] = {}
        self.mismatched: set[tuple[str, str]] = set()

    def map(self, recorded: str) -> str:
        mapped = self.mapped.get(recorded)
        if mapped is None:
            # Resolve as cc_wrap does, so a symlinked toolchain lands on its
            # shared real directory; paths outside the origin stay as recorded.
            mapped = (os.path.realpath(self.tree / recorded[len(self.origin):])
                      if recorded.startswith(self.origin) else recorded)
            self.mapped[recorded] = mapped
        return mapped

    def translate(self, record: dict) -> dict | None:
        """The receipt as the new tree would record it, or None when any input differs."""
        inputs = record.get("inputs") if record.get("schema") == 1 else None
        if not isinstance(inputs, dict) or not self.mismatched.isdisjoint(inputs.items()):
            return None
        translated = {}
        for recorded, expected in inputs.items():
            candidate = self.map(recorded)
            if self.hashes(candidate) != expected:
                self.mismatched.add((recorded, expected))
                return None
            translated[candidate] = expected
        return dict(record, inputs=translated)


def translate_receipt(record: dict, origin: Path, tree: Path, hashes) -> dict | None:
    """One receipt translated from ``origin`` into ``tree`` (see ``_Origin``)."""
    return _Origin(origin, tree, hashes).translate(record)


def seed_base_objects(tree: Path, sources: list[Path], units: list[str]) -> dict[str, Path]:
    """Copy each unit's first base object whose receipt matches ``tree`` exactly."""
    hashes = _Hashes()
    destination = tree / OBJDIFF / "base"
    destination.mkdir(parents=True, exist_ok=True)
    seeded: dict[str, Path] = {}
    for origin in sources:
        base = origin / OBJDIFF / "base"
        if not base.is_dir():
            continue
        translator = _Origin(origin, tree, hashes)
        for unit in units:
            if unit in seeded:
                continue
            obj = base / f"{unit}.obj"
            receipt = base / f"{unit}.obj{RECEIPT_SUFFIX}"
            try:
                translated = translator.translate(json.loads(receipt.read_text()))
                if translated is None:
                    continue
                data = obj.read_bytes()
            except (OSError, ValueError):
                continue
            if hashlib.sha256(data).hexdigest() != translated.get("object_sha256"):
                continue
            (destination / obj.name).write_bytes(data)
            (destination / receipt.name).write_text(json.dumps(translated, sort_keys=True) + "\n")
            seeded[unit] = origin
    return seeded


# --------------------------------------------------------------- seeding

def _copy_tree(source: Path, destination: Path, skip=frozenset()) -> int:
    copied = 0
    for path in sorted(source.rglob("*")):
        relative = path.relative_to(source)
        if relative.parts[0] in skip or not path.is_file():
            continue
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, target)
        copied += 1
    return copied


def seed_comparison_state(seed: Path, tree: Path) -> dict:
    """Retail targets, build/gen and normalized copies from the seed checkout."""
    seed_pin = Project(seed).executable("retail")
    tree_pin = Project(tree).executable("retail")
    if (seed_pin.sha256, seed_pin.size) != (tree_pin.sha256, tree_pin.size):
        raise WorktreeError(f"{seed} pins a different retail executable; not seeding targets")
    if not seed_pin.destination.is_file():
        raise WorktreeError(f"{seed} has no staged retail executable; not seeding targets")
    targets = sorted((seed / OBJDIFF / "target").glob("*.c.obj"))
    if not targets:
        raise WorktreeError(f"{seed} has no retail targets (run `homm3 build` there once)")
    destination = tree / OBJDIFF / "target"
    destination.mkdir(parents=True, exist_ok=True)
    for target in targets:
        shutil.copy2(target, destination / target.name)
    gen = _copy_tree(seed / GEN, tree / GEN, GEN_SKIP) if (seed / GEN).is_dir() else 0
    normalized = (_copy_tree(seed / OBJDIFF / "normalized", tree / OBJDIFF / "normalized")
                  if (seed / OBJDIFF / "normalized").is_dir() else 0)
    newest = max(target.stat().st_mtime for target in targets)
    return {"targets": len(targets), "gen": gen, "normalized": normalized,
            "delinked": time.strftime("%Y-%m-%d %H:%M", time.localtime(newest))}


def _stage_mac_sdk(seed: Path, tree: Path) -> str:
    source = seed / MAC_SDK
    if not source.is_dir():
        return "skipped (seed has no build/mac/sdk; run `homm3 mac sdk PATH`)"
    destination = tree / MAC_SDK
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination, symlinks=False)
    from homm3.mac import sdk
    try:
        sdk.inputs(tree)
    except (ValueError, OSError) as exc:
        shutil.rmtree(destination, ignore_errors=True)
        return f"skipped ({exc})"
    return "copied and verified"


def _link_toolchain(seed: Path, tree: Path, toolchain: Path = TOOLCHAIN,
                    missing: str = "seed has no unpacked toolchain; init will fetch it") -> str:
    source = (seed / toolchain).resolve()
    if not _find_ci(source / "msvc/bin", "cl.exe"):
        return f"not linked ({missing})"
    link = tree / toolchain
    link.parent.mkdir(parents=True, exist_ok=True)
    if link.is_symlink() or link.exists():
        return f"kept existing {link}"
    link.symlink_to(source, target_is_directory=True)
    return f"linked -> {source}"


def _init_arguments(seed: Path) -> list[str]:
    project = Project(seed)
    arguments = []
    for key, option in (("retail", "--exe"), ("dreamcast", "--dreamcast-exe"),
                        ("mac", "--mac-exe")):
        staged = project.executable(key).destination
        if staged.is_file():
            arguments += [option, str(staged)]
    if (seed / MAC_TOOLCHAIN).is_dir():
        arguments += ["--mac-toolchain", str(seed / MAC_TOOLCHAIN)]
    return arguments + ["--no-smoke"]


def _image_sources(seed: Path, tree: Path) -> dict[str, Path | None]:
    """Each other image's executable for the new tree: the seed's staged copy,
    else its `$HOMM3_<KEY>_EXE` override, else None."""
    from homm3.core import images
    project = Project(seed)
    out = {}
    for key in images.images(tree)[1:]:
        executable = project.executable(images.input_key(key))
        override = os.environ.get(executable.env_var)
        out[key] = (executable.destination if executable.destination.is_file()
                    else Path(override).expanduser() if override else None)
    return out


def _stage_images(seed: Path, tree: Path) -> list[str]:
    """Stage every other image (`homm3 --image KEY init`, hash-verified) from
    the seed's staged copy or its `$HOMM3_<KEY>_EXE` override, with the seed's
    SP3 MFC overlay or `$HOMM3_MFC_SP3`. An image with neither is reported:
    a full `homm3 build` there refuses to run until it is staged."""
    lines = []
    mfc = seed / "build/mfc-sp3"
    for key, source in _image_sources(seed, tree).items():
        if source is None:
            lines.append(f"WARNING: image {key}: no staged executable in {seed} and no "
                         f"override; `homm3 build` fails there until `homm3 --image {key} "
                         "init --exe PATH` (or `--skip-image " + key + "`)")
            continue
        extra = ["--mfc-sp3", str(mfc)] if mfc.is_dir() else []
        if not extra and not os.environ.get("HOMM3_MFC_SP3"):
            lines.append(f"WARNING: image {key}: no SP3 MFC overlay in {seed} and no "
                         f"$HOMM3_MFC_SP3; run `homm3 --image {key} init --mfc-sp3 DIR` there")
        rc = _homm3(tree, "--image", key, "init", "--exe", str(source), *extra)
        lines.append(f"image {key}: " + (f"staged from {source}" if rc == 0 else
                                          f"staging failed; run `homm3 --image {key} init` there"))
    return lines


def _units(tree: Path) -> list[str]:
    from homm3 import manifest
    return [row["unit"] for row in manifest.units(tree / "config/units.toml")]


def _normalized_names(unit: str) -> tuple[str, ...]:
    """A unit's comparison copies, symbol sidecars and provenance stamps."""
    return tuple(f"{side}/{name}" for side, stem in (("base", unit), ("target", unit + ".c"))
                 for name in (f"{stem}.obj", f"{stem}.symbols.tsv", f"{stem}.obj.stamp.json"))


def adopt_normalized(tree: Path, seeded: dict[str, Path], seed: Path) -> int:
    """Prefer each adopted object's own normalized copies over the seed's.

    Their stamps name the raw objects, targets, generated tables and tools by
    content, so a copy that does not describe this tree is simply rebuilt.
    """
    copied = 0
    for unit, origin in seeded.items():
        if origin == seed:
            continue
        for name in _normalized_names(unit):
            source = origin / OBJDIFF / "normalized" / name
            if source.is_file():
                target = tree / OBJDIFF / "normalized" / name
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(source, target)
                copied += 1
    return copied


def cmd_new(args) -> int:
    started = time.monotonic()

    def phase(message: str) -> None:
        log(f"{message} ({time.monotonic() - started:.1f}s)")

    repo = common.HOMM3_DIR
    entries = worktrees(repo)
    main_tree = Path(entries[0]["worktree"]) if entries else repo
    seed = Path(args.seed_from).resolve() if args.seed_from else main_tree.resolve()
    if project_root(seed) != seed:
        raise WorktreeError(f"seed {seed} is not a homm3 checkout")
    tree = Path(args.path).expanduser().resolve()
    if tree == seed:
        raise WorktreeError("the new worktree cannot be its own seed")

    command = ["worktree", "add"]
    if args.branch:
        command += ["-b", args.branch]
    command.append(str(tree))
    if args.ref:
        command.append(args.ref)
    _git(repo, *command, capture=False)
    phase(f"created {tree}")

    log(f"seed checkout: {seed}")
    log(f"VC6 toolchain: {_link_toolchain(seed, tree)}")
    log("VC6 RTM compiler: " + _link_toolchain(
        seed, tree, RTM_TOOLCHAIN,
        "seed has no RTM overlay; init builds it from the staged RTM binaries"))
    (tree / "build/mac").mkdir(parents=True, exist_ok=True)
    log(f"Mac SDK: {_stage_mac_sdk(seed, tree)}")
    # The new tree's own init (verified staging, configure, Wine prefix) runs
    # while comparison state is seeded; it never writes the seeded paths.
    init_log = tree / "build/worktree-init.log"
    with init_log.open("w") as stream:
        init = subprocess.Popen([sys.executable, "-m", "homm3", "init", *_init_arguments(seed)],
                                cwd=tree, env=_environment(tree),
                                stdout=stream, stderr=subprocess.STDOUT)
    state, seeded, units = None, {}, _units(tree)
    try:
        if args.no_seed:
            log("not seeded: run `homm3 build` once before `homm3 build --fast`")
        else:
            try:
                state = seed_comparison_state(seed, tree)
            except WorktreeError as exc:
                log(f"not seeded: {exc}; run `homm3 build` once before `--fast`")
        if state:
            log(f"seeded {state['targets']} retail targets (seed delink {state['delinked']}), "
                f"{state['gen']} build/gen files, {state['normalized']} normalized files")
            sources = [seed] + [Path(entry["worktree"]) for entry in entries
                                if "worktree" in entry and Path(entry["worktree"]).resolve()
                                not in (seed, tree) and not entry.get("prunable")]
            seeded = seed_base_objects(tree, sources, units)
            adopt_normalized(tree, seeded, seed)
            phase(f"adopted {len(seeded)}/{len(units)} base objects with matching "
                  f"receipts from {len(set(seeded.values()))} checkout(s)")
    finally:
        init_rc = init.wait()
    if init_rc:
        print(init_log.read_text()[-4000:], file=sys.stderr)
        raise WorktreeError(f"`homm3 init` failed in the new worktree (log: {init_log}); "
                            "fix the reported input and rerun it there")
    phase(f"initialized executables, CodeWarrior tools and Wine prefix (log: {init_log})")
    for line in _stage_images(seed, tree):
        log(line)
    if not state:
        return 0

    missing = [unit for unit in units if unit not in seeded]
    if missing:
        log(f"{len(missing)} unit(s) differ from every checkout and will compile"
            + (": " + ", ".join(missing[:12]) + (" ..." if len(missing) > 12 else "")))
    if _homm3(tree, "configure"):
        raise WorktreeError("configure failed in the new worktree")
    if args.no_objects:
        log("skipped `ninja objects` and the delink; run a full `homm3 build` there "
            "before `--fast` (the seeded targets carry the seed's claims)")
        return 0
    if _run_in(tree, "ninja", "-k", "0", "objects"):
        log("WARNING: some units failed to compile; `homm3 build --fast` needs every "
            "base object - fix them in the new tree")
    phase("ninja objects")
    if args.no_delink:
        if _run_in(tree, sys.executable, "-m", "homm3.build.normalize_objs") or \
                _homm3(tree, "configure"):
            log("WARNING: normalizing comparison copies failed; run `homm3 build` there")
        phase("normalized comparison copies")
        log(f"WARNING: retail targets carry {seed.name}'s claim names from its "
            f"{state['delinked']} delink; run `homm3 delink` there before trusting "
            "or banking scores")
    elif _homm3(tree, "delink"):
        log("WARNING: delinking failed; run `homm3 build` there before `--fast`")
    else:
        phase("delinked retail targets from this tree's claims")
    log(f"ready: cd {tree} && homm3 build --fast <TU>")
    return 0


def cmd_remove(args) -> int:
    repo = common.HOMM3_DIR
    tree = Path(args.path).expanduser().resolve()
    entries = worktrees(repo)
    known = {Path(entry["worktree"]).resolve(): entry for entry in entries if "worktree" in entry}
    if tree not in known:
        raise WorktreeError(f"{tree} is not a worktree of {repo}")
    if entries and Path(entries[0]["worktree"]).resolve() == tree:
        raise WorktreeError("refusing to remove the main worktree")
    status = _git(tree, "status", "--porcelain")
    if status.strip():
        lines = status.rstrip().splitlines()
        raise WorktreeError(f"{tree} has uncommitted changes; commit or discard them first:\n  "
                            + "\n  ".join(lines[:15]) + ("\n  ..." if len(lines) > 15 else ""))
    prefix = tree / "build/wineprefix"
    server = shutil.which("wineserver")
    if prefix.is_dir() and server:
        subprocess.run([server, "-k"], env=dict(os.environ, WINEPREFIX=str(prefix)),
                       check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    # Unlink shared-input symlinks first so nothing can follow them.
    for link in (tree / TOOLCHAIN, tree / RTM_TOOLCHAIN):
        if link.is_symlink():
            link.unlink()
    _git(repo, "worktree", "remove", str(tree), capture=False)
    log(f"removed {tree}")
    branch = known[tree].get("branch")
    if args.delete_branch and isinstance(branch, str):
        name = branch.removeprefix("refs/heads/")
        _git(repo, "branch", "-d", name, capture=False)
        log(f"deleted branch {name}")
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="homm3 worktree", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)
    new = sub.add_parser("new", help="create a linked worktree ready for `homm3 build --fast`")
    new.add_argument("path", help="directory for the new worktree")
    new.add_argument("-b", "--branch", help="create this branch for the worktree")
    new.add_argument("--from", dest="ref", metavar="REF",
                     help="commit-ish to check out (default: git's, the current HEAD)")
    new.add_argument("--seed-from", metavar="DIR",
                     help="checkout supplying inputs and retail targets "
                          "(default: the repository's main worktree)")
    new.add_argument("--no-seed", action="store_true",
                     help="only stage inputs; the first full `homm3 build` creates targets")
    new.add_argument("--no-objects", action="store_true",
                     help="seed, but leave `ninja objects` and the delink to the first build")
    new.add_argument("--no-delink", action="store_true",
                     help="keep the seed's retail targets and build/gen instead of "
                          "delinking this tree's claims (faster; scores may differ)")
    new.set_defaults(fn=cmd_new)
    remove = sub.add_parser("remove", help="remove a clean worktree and stop its Wine server")
    remove.add_argument("path")
    remove.add_argument("--delete-branch", action="store_true",
                        help="also `git branch -d` its branch (refuses unmerged work)")
    remove.set_defaults(fn=cmd_remove)
    args = parser.parse_args(argv)
    try:
        return args.fn(args)
    except WorktreeError as exc:
        print(f"[worktree] ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
