{
    DATA_COMPGEN(0x006827d8, rmgPlayerRed, "red"),
    DATA_COMPGEN(0x006827d0, rmgPlayerBlue, "blue"),
    DATA_COMPGEN(0x006827cc, rmgPlayerTan, "tan"),
    DATA_COMPGEN(0x006827c4, rmgPlayerGreen, "green"),
    DATA_COMPGEN(0x006827bc, rmgPlayerOrange, "orange"),
    DATA_COMPGEN(0x006827b4, rmgPlayerPurple, "purple"),
    DATA_COMPGEN(0x006827ac, rmgPlayerTeal, "teal"),
    DATA_COMPGEN(0x006827a4, rmgPlayerPink, "pink")
}
