{
    {TOWN_CASTLE,     TOWN_RAMPART,    TOWN_NECROPOLIS, eTownNeutral}, // dirt
    {TOWN_STRONGHOLD, eTownNeutral},                                   // sand
    {TOWN_CASTLE,     TOWN_RAMPART,    eTownNeutral},                  // grass
    {TOWN_TOWER,      eTownNeutral},                                   // snow
    {TOWN_FORTRESS,   TOWN_NECROPOLIS, eTownNeutral},                  // swamp
    {TOWN_STRONGHOLD, TOWN_CONFLUX,    eTownNeutral},                  // rough
    {TOWN_DUNGEON,    TOWN_INFERNO,    TOWN_NECROPOLIS, eTownNeutral}, // subterranean
    {TOWN_INFERNO,    eTownNeutral},                                   // lava
    {eTownNeutral}                                                     // water
}
