#ifndef HOMM3_RMG_COLUMNS_H
#define HOMM3_RMG_COLUMNS_H

// rmg.txt and rand_trn.txt rows start after three header rows.
enum ERmgSpreadsheetLayout {
    RMG_FIRST_DATA_ROW = 3
};

// rmg.txt columns. A template's first row holds its name and size range;
// any row may also hold one zone and one connection.
enum ERmgTemplateColumn {
    RMG_TEMPLATE_COLUMN_NAME = 0,
    RMG_TEMPLATE_COLUMN_MINIMUM_SIZE = 1,
    RMG_TEMPLATE_COLUMN_MAXIMUM_SIZE = 2,
    RMG_TEMPLATE_COLUMN_ZONE_INDEX = 3,
    RMG_TEMPLATE_COLUMN_KIND_HUMAN = 4,
    RMG_TEMPLATE_COLUMN_KIND_COMPUTER = 5,
    RMG_TEMPLATE_COLUMN_KIND_TREASURE = 6,
    RMG_TEMPLATE_COLUMN_KIND_JUNCTION = 7,
    RMG_TEMPLATE_COLUMN_SIZE = 8,
    RMG_TEMPLATE_COLUMN_MINIMUM_HUMAN_PLAYERS = 9,
    RMG_TEMPLATE_COLUMN_MAXIMUM_HUMAN_PLAYERS = 10,
    RMG_TEMPLATE_COLUMN_MINIMUM_PLAYERS = 11,
    RMG_TEMPLATE_COLUMN_MAXIMUM_PLAYERS = 12,
    RMG_TEMPLATE_COLUMN_PLAYER_INDEX = 13,
    RMG_TEMPLATE_COLUMN_PLAYER_BASIC_COUNT = 14,
    RMG_TEMPLATE_COLUMN_PLAYER_CASTLE_COUNT = 15,
    RMG_TEMPLATE_COLUMN_PLAYER_BASIC_DENSITY = 16,
    RMG_TEMPLATE_COLUMN_PLAYER_CASTLE_DENSITY = 17,
    RMG_TEMPLATE_COLUMN_NEUTRAL_BASIC_COUNT = 18,
    RMG_TEMPLATE_COLUMN_NEUTRAL_CASTLE_COUNT = 19,
    RMG_TEMPLATE_COLUMN_NEUTRAL_BASIC_DENSITY = 20,
    RMG_TEMPLATE_COLUMN_NEUTRAL_CASTLE_DENSITY = 21,
    RMG_TEMPLATE_COLUMN_NEUTRAL_TOWNS_MATCH_ZONE = 22,
    RMG_TEMPLATE_COLUMN_ALLOWED_TOWNS = 23,      // one per town type
    RMG_TEMPLATE_COLUMN_MINE_COUNTS = 32,        // one per resource
    RMG_TEMPLATE_COLUMN_MINE_DENSITIES = 39,     // one per resource
    RMG_TEMPLATE_COLUMN_USE_NATIVE_TERRAIN = 46,
    RMG_TEMPLATE_COLUMN_ALLOWED_TERRAIN = 47,    // one per land terrain
    RMG_TEMPLATE_COLUMN_MONSTER_STRENGTH = 55,
    RMG_TEMPLATE_COLUMN_GUARDS_MATCH_ZONE = 56,
    RMG_TEMPLATE_COLUMN_ALLOWED_MONSTERS = 57,   // neutral, then one per town type
    // Three columns per treasure tier.
    RMG_TEMPLATE_COLUMN_TREASURE_MINIMUM = 67,
    RMG_TEMPLATE_COLUMN_TREASURE_MAXIMUM = 68,
    RMG_TEMPLATE_COLUMN_TREASURE_DENSITY = 69,
    RMG_TEMPLATE_TREASURE_COLUMN_COUNT = 3,
    RMG_TEMPLATE_COLUMN_LAST_TREASURE_DENSITY = 75,
    RMG_TEMPLATE_COLUMN_CONNECTION_FIRST_ZONE = 76,
    RMG_TEMPLATE_COLUMN_CONNECTION_SECOND_ZONE = 77,
    RMG_TEMPLATE_COLUMN_CONNECTION_VALUE = 78,
    RMG_TEMPLATE_COLUMN_CONNECTION_UNGUARDED = 79,            // "Wide"
    RMG_TEMPLATE_COLUMN_CONNECTION_BORDER_GUARD = 80,         // "Border Guard"
    RMG_TEMPLATE_COLUMN_CONNECTION_MINIMUM_HUMAN_PLAYERS = 81,
    RMG_TEMPLATE_COLUMN_CONNECTION_MAXIMUM_HUMAN_PLAYERS = 82,
    RMG_TEMPLATE_COLUMN_CONNECTION_MINIMUM_PLAYERS = 83,
    RMG_TEMPLATE_COLUMN_CONNECTION_MAXIMUM_PLAYERS = 84
};

// Offsets from a zone's or connection's minimum human players column.
enum ERmgPlayerLimitColumn {
    RMG_PLAYER_LIMIT_MAXIMUM_HUMAN_PLAYERS = 1,
    RMG_PLAYER_LIMIT_MINIMUM_PLAYERS = 2,
    RMG_PLAYER_LIMIT_MAXIMUM_PLAYERS = 3
};

// rand_trn.txt columns. Neighbour scores take one column per rule: all
// adjacent scores, then all blocked scores.
enum ERmgPlacementRuleColumn {
    RMG_PLACEMENT_COLUMN_OBJECT_TYPE = 3,
    RMG_PLACEMENT_COLUMN_SUBTYPE = 4,
    RMG_PLACEMENT_COLUMN_TERRAIN = 6,
    RMG_PLACEMENT_COLUMN_TERRAIN_SCORES = 7,     // dirt through water
    RMG_PLACEMENT_COLUMN_NEIGHBOUR_SCORES = 16
};

#endif
