// spelldefs.h - prototypes of spelldefs.cpp (compiland spelldefs.obj)
// HAND-OWNED after admission - INITIALLY GENERATED by `python3 -m homm3.carve carcass`.
// Class layouts are NOT fabricated from method symbols;
// prototypes stay comments until a retail layout is proven.
#ifndef HOMM3_SPELLDEFS_H
#define HOMM3_SPELLDEFS_H

#include <vector>
#include "armygrp.h"

// Retail spell-class flag roles in SSpellTraits::field_c. Names are
// behavior-derived; values and mastery thresholds are byte-proven by
// SpellTargetsASingleArmy.
enum ESpellTargetFlags {
    SPELL_TARGET_ALWAYS_SINGLE = 0x10,
    SPELL_TARGET_MASS_AT_ADVANCED = 0x20,
    SPELL_TARGET_MASS_AT_EXPERT = 0x40,
    // mark_area_highlights owns the rollover preview for the two area
    // traits carried together by this mask. Retail tests the pair as one
    // value before also admitting Berserk explicitly.
    SPELL_TARGET_MARK_AREA = 0x280
};

unsigned char SpellTargetsASingleArmy(int spell, int sslevel);
unsigned char InitializeSpellTraitsTable();

// Mutable implementation storage filled from sptraits.txt. The public
// akSpellTraits pointer/reference cell is at 0x687f58; retail writes this
// adjacent 81*136-byte backing array directly. Name is provisional because
// only the public DC array name survives.
extern SSpellTraits aSpellTraitsImp[81];

namespace {

// Source-private Dreamcast TAutoStrPtr. Its retail ctor/dtor are ICF-shared
// inline representatives; spelldefs' lazy static arrays are its only storage.
class TAutoStrPtr {
public:
    TAutoStrPtr() : pStr(0) {}
    ~TAutoStrPtr() { delete[] pStr; }
    void set(char* value) { pStr = value; }
    char* get() const { return pStr; }

private:
    char* pStr;
};

}

// --- globals ---
// CODEVIEW(E:\gamedcs\spelldefs.cpp:335, dc 0x14e39c) void InitializeSpellTraits(int id, const std::vector<char* resource);

// --- `anonymous namespace' ---
// CODEVIEW(E:\gamedcs\spelldefs.cpp:320, dc 0x14e78c) void `anonymous namespace'::TAutoStrPtr::TAutoStrPtr();
// CODEVIEW(E:\gamedcs\spelldefs.cpp:321, dc 0x14e794) void `anonymous namespace'::TAutoStrPtr::~TAutoStrPtr();
// CODEVIEW(E:\gamedcs\spelldefs.cpp:323, dc 0x14e7ac) void `anonymous namespace'::TAutoStrPtr::set(char* pStr);
// CODEVIEW(E:\gamedcs\spelldefs.cpp:325, dc 0x14e7b0) char* `anonymous namespace'::TAutoStrPtr::get();

#endif  /* HOMM3_SPELLDEFS_H */
