// textresource.h - prototypes of textresource.cpp (compiland textresource.obj)
// HAND-OWNED after admission - INITIALLY GENERATED by `python3 -m homm3.carve carcass`.
// Class layouts are NOT fabricated from method symbols;
// prototypes stay comments until a retail layout is proven.
#ifndef HOMM3_TEXTRESOURCE_H
#define HOMM3_TEXTRESOURCE_H

// --- TSpreadsheetResource ---
// CODEVIEW(E:\gamedcs\textresource.cpp:177, dc 0x1639ec) void TSpreadsheetResource::TSpreadsheetResource();
// CODEVIEW(E:\gamedcs\textresource.cpp:182, dc 0x163a70) void TSpreadsheetResource::TSpreadsheetResource(const char* name, int size, const char* data);
// CODEVIEW(E:\gamedcs\textresource.cpp:292, dc 0x163c30) void TSpreadsheetResource::~TSpreadsheetResource();
// CODEVIEW(E:\gamedcs\textresource.cpp:178, dc 0x163d2c) void* TSpreadsheetResource::`scalar deleting destructor'(unsigned __flags);

// --- TTextResource ---
// CODEVIEW(E:\gamedcs\textresource.cpp:33, dc 0x163808) void TTextResource::TTextResource();
// CODEVIEW(E:\gamedcs\textresource.cpp:38, dc 0x163858) void TTextResource::TTextResource(const char* name, int size, const char* data);
// CODEVIEW(E:\gamedcs\textresource.cpp:143, dc 0x1639a4) void TTextResource::~TTextResource();
// CODEVIEW(E:\gamedcs\textresource.cpp:34, dc 0x163cf8) void* TTextResource::`scalar deleting destructor'(unsigned __flags);

// --- std ---
// CODEVIEW(E:\gamedcs\textresource.cpp:298, dc 0x163d60) void* std::vector<char *,std::allocator<char *> >::`scalar deleting destructor'(unsigned __flags);
// CODEVIEW(..\stlport\stl_vector.h:181, dc 0x163d94) char** std::vector<char *,std::allocator<char *> >::end();
// CODEVIEW(..\stlport\stl_vector.h:218, dc 0x163d98) void std::vector<char *,std::allocator<char *> >::vector<char *,std::allocator<char *> >(const std::allocator<char* __a);
// CODEVIEW(..\stlport\stl_vector.h:230, dc 0x163db4) void std::vector<char *,std::allocator<char *> >::vector<char *,std::allocator<char *> >(unsigned __n);
// CODEVIEW(..\stlport\stl_vector.h:288, dc 0x163e08) void std::vector<char *,std::allocator<char *> >::~vector<char *,std::allocator<char *> >();
// CODEVIEW(..\stlport\stl_vector.h:505, dc 0x163e30) void std::vector<char *,std::allocator<char *> >::resize(unsigned __new_size);
// CODEVIEW(..\stlport\stl_alloc.h:527, dc 0x163e4c) void std::allocator<char *>::allocator<char *>();
// CODEVIEW(..\stlport\stl_alloc.h:537, dc 0x163e50) void std::allocator<char *>::~allocator<char *>();
// CODEVIEW(..\stlport\stl_vector.h:179, dc 0x163e54) std::vector<char** std::vector<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::begin();
// CODEVIEW(..\stlport\stl_vector.h:181, dc 0x163e58) std::vector<char** std::vector<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::end();
// CODEVIEW(..\stlport\stl_vector.h:218, dc 0x163e5c) void std::vector<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::vector<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >(const std::allocator<std::vector<char* __a);
// CODEVIEW(..\stlport\stl_vector.h:230, dc 0x163e78) void std::vector<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::vector<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >(unsigned __n);
// CODEVIEW(..\stlport\stl_vector.h:288, dc 0x163ecc) void std::vector<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::~vector<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >();
// CODEVIEW(..\stlport\stl_vector.h:505, dc 0x163ef4) void std::vector<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::resize(unsigned __new_size);
// CODEVIEW(..\stlport\stl_alloc.h:527, dc 0x163f10) void std::allocator<std::vector<char *,std::allocator<char *> > *>::allocator<std::vector<char *,std::allocator<char *> > *>();
// CODEVIEW(..\stlport\stl_alloc.h:537, dc 0x163f14) void std::allocator<std::vector<char *,std::allocator<char *> > *>::~allocator<std::vector<char *,std::allocator<char *> > *>();
// CODEVIEW(..\stlport\stl_vector.h:499, dc 0x163f18) void std::vector<char *,std::allocator<char *> >::resize(unsigned __new_size, char** __x);
// CODEVIEW(..\stlport\stl_vector.h:89, dc 0x163f94) void std::_Vector_base<char *,std::allocator<char *> >::_Vector_base<char *,std::allocator<char *> >(const std::allocator<char* __a);
// CODEVIEW(..\stlport\stl_vector.h:94, dc 0x163fc0) void std::_Vector_base<char *,std::allocator<char *> >::_Vector_base<char *,std::allocator<char *> >(unsigned __n, const std::allocator<char* __a);
// CODEVIEW(..\stlport\stl_vector.h:101, dc 0x164008) void std::_Vector_base<char *,std::allocator<char *> >::~_Vector_base<char *,std::allocator<char *> >();
// CODEVIEW(..\stlport\stl_vector.h:499, dc 0x164038) void std::vector<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::resize(unsigned __new_size, std::vector<char** __x);
// CODEVIEW(..\stlport\stl_vector.h:89, dc 0x1640b4) void std::_Vector_base<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::_Vector_base<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >(const std::allocator<std::vector<char* __a);
// CODEVIEW(..\stlport\stl_vector.h:94, dc 0x1640e0) void std::_Vector_base<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::_Vector_base<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >(unsigned __n, const std::allocator<std::vector<char* __a);
// CODEVIEW(..\stlport\stl_vector.h:101, dc 0x164128) void std::_Vector_base<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::~_Vector_base<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >();
// CODEVIEW(..\stlport\stl_bvector.h:101, dc 0x164158) void std::_STL_alloc_proxy<char * *,char *,std::allocator<char *> >::~_STL_alloc_proxy<char * *,char *,std::allocator<char *> >();
// CODEVIEW(..\stlport\stl_bvector.h:101, dc 0x164170) void std::_STL_alloc_proxy<std::vector<char *,std::allocator<char *> > * *,std::vector<char *,std::alloca();
// CODEVIEW(..\stlport\stl_vector.h:472, dc 0x164188) void std::vector<char *,std::allocator<char *> >::insert(char** __pos, unsigned __n, char** __x);
// CODEVIEW(..\stlport\stl_vector.h:490, dc 0x1641a0) char** std::vector<char *,std::allocator<char *> >::erase(char** __first, char** __last);
// CODEVIEW(..\stlport\stl_alloc.h:1004, dc 0x1641dc) void std::_STL_alloc_proxy<char * *,char *,std::allocator<char *> >::_STL_alloc_proxy<char * *,char *,std::allocator<char *> >(const std::allocator<char* __a, char*** __p);
// CODEVIEW(..\stlport\stl_alloc.h:1022, dc 0x1641e8) char** std::_STL_alloc_proxy<char * *,char *,std::allocator<char *> >::allocate(unsigned __n);
// CODEVIEW(..\stlport\stl_alloc.h:1025, dc 0x164210) void std::_STL_alloc_proxy<char * *,char *,std::allocator<char *> >::deallocate(char** __p, unsigned __n);
// CODEVIEW(..\stlport\stl_vector.h:472, dc 0x16423c) void std::vector<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::insert(std::vector<char** __pos, unsigned __n, std::vector<char** __x);
// CODEVIEW(..\stlport\stl_vector.h:490, dc 0x164254) std::vector<char** std::vector<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::erase(std::vector<char** __first, std::vector<char** __last);
// CODEVIEW(..\stlport\stl_alloc.h:1004, dc 0x164290) void std::_STL_alloc_proxy<std::vector<char *,std::allocator<char *> > * *,std::vector<char *,std::alloc(const std::allocator<std::vector<char* __a, std::vector<char*** __p);
// CODEVIEW(..\stlport\stl_alloc.h:1022, dc 0x16429c) std::vector<char** std::_STL_alloc_proxy<std::vector<char *,std::allocator<char *> > * *,std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::allocate(unsigned __n);
// CODEVIEW(..\stlport\stl_alloc.h:1025, dc 0x1642c4) void std::_STL_alloc_proxy<std::vector<char *,std::allocator<char *> > * *,std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::deallocate(std::vector<char** __p, unsigned __n);
// CODEVIEW(..\stlport\stl_alloc.h:547, dc 0x1642f0) char** std::allocator<char *>::allocate(unsigned __n, const void* __formal);
// CODEVIEW(..\stlport\stl_alloc.h:552, dc 0x164314) void std::allocator<char *>::deallocate(char** __p, unsigned __n);
// CODEVIEW(..\stlport\stl_alloc.h:547, dc 0x164330) std::vector<char** std::allocator<std::vector<char *,std::allocator<char *> > *>::allocate(unsigned __n, const void* __formal);
// CODEVIEW(..\stlport\stl_alloc.h:552, dc 0x164354) void std::allocator<std::vector<char *,std::allocator<char *> > *>::deallocate(std::vector<char** __p, unsigned __n);
// CODEVIEW(..\stlport\stl_vector.c:283, dc 0x164370) void std::vector<char *,std::allocator<char *> >::_M_fill_insert(char** __position, unsigned __n, char** __x);
// CODEVIEW(..\stlport\stl_vector.c:283, dc 0x16443c) void std::vector<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::_M_fill_insert(std::vector<char** __position, unsigned __n, std::vector<char** __x);
// CODEVIEW(..\stlport\stl_uninitialized.h:263, dc 0x164508) char** std::uninitialized_fill_n(char** __first, unsigned __n, char** __x);
// CODEVIEW(..\stlport\stl_construct.h:128, dc 0x164540) void std::destroy(char** __first, char** __last);
// CODEVIEW(..\stlport\stl_uninitialized.h:263, dc 0x164570) std::vector<char** std::uninitialized_fill_n(std::vector<char** __first, unsigned __n, std::vector<char** __x);
// CODEVIEW(..\stlport\stl_construct.h:128, dc 0x1645a8) void std::destroy(std::vector<char** __first, std::vector<char** __last);
// CODEVIEW(..\stlport\stl_algobase.h:322, dc 0x1645d8) char** std::copy(char** __first, char** __last, char** __result);
// CODEVIEW(..\stlport\stl_alloc.h:968, dc 0x164628) std::allocator<char* std::__stl_alloc_rebind(std::allocator<char* __a, char** __formal);
// CODEVIEW(..\stlport\stl_algobase.h:322, dc 0x16462c) std::vector<char** std::copy(std::vector<char** __first, std::vector<char** __last, std::vector<char** __result);
// CODEVIEW(..\stlport\stl_alloc.h:968, dc 0x16467c) std::allocator<std::vector<char* std::__stl_alloc_rebind(std::allocator<std::vector<char* __a, std::vector<char** __formal);
// CODEVIEW(..\stlport\stl_vector.c:248, dc 0x164680) void std::vector<char *,std::allocator<char *> >::_M_insert_overflow(char** __position, char** __x, unsigned __fill_len);
// CODEVIEW(..\stlport\stl_uninitialized.h:97, dc 0x16474c) char** std::uninitialized_copy(char** __first, char** __last, char** __result);
// CODEVIEW(..\stlport\stl_algobase.h:442, dc 0x164784) char** std::copy_backward(char** __first, char** __last, char** __result);
// CODEVIEW(..\stlport\stl_algobase.h:495, dc 0x1647d4) void std::fill(char** __first, char** __last, char** __value);
// CODEVIEW(..\stlport\stl_vector.c:248, dc 0x1647ec) void std::vector<std::vector<char *,std::allocator<char *> > *,std::allocator<std::vector<char *,std::allocator<char *> > *> >::_M_insert_overflow(std::vector<char** __position, std::vector<char** __x, unsigned __fill_len);
// CODEVIEW(..\stlport\stl_uninitialized.h:97, dc 0x1648b8) std::vector<char** std::uninitialized_copy(std::vector<char** __first, std::vector<char** __last, std::vector<char** __result);
// CODEVIEW(..\stlport\stl_algobase.h:442, dc 0x1648f0) std::vector<char** std::copy_backward(std::vector<char** __first, std::vector<char** __last, std::vector<char** __result);
// CODEVIEW(..\stlport\stl_algobase.h:495, dc 0x164940) void std::fill(std::vector<char** __first, std::vector<char** __last, std::vector<char** __value);
// CODEVIEW(..\stlport\stl_iterator_base.h:262, dc 0x164958) char** std::value_type(char** __formal);
// CODEVIEW(..\stlport\stl_uninitialized.h:255, dc 0x16495c) char** std::__uninitialized_fill_n(char** __first, unsigned __n, char** __x, char** __formal);
// CODEVIEW(..\stlport\stl_construct.h:121, dc 0x164978) void std::__destroy(char** __first, char** __last, char** __formal);
// CODEVIEW(..\stlport\stl_iterator_base.h:262, dc 0x164994) std::vector<char** std::value_type(std::vector<char** __formal);
// CODEVIEW(..\stlport\stl_uninitialized.h:255, dc 0x164998) std::vector<char** std::__uninitialized_fill_n(std::vector<char** __first, unsigned __n, std::vector<char** __x, std::vector<char** __formal);
// CODEVIEW(..\stlport\stl_construct.h:121, dc 0x1649b4) void std::__destroy(std::vector<char** __first, std::vector<char** __last, std::vector<char** __formal);
// CODEVIEW(..\stlport\stl_iterator_base.h:243, dc 0x1649d0) std::random_access_iterator_tag std::iterator_category(__$ReturnUdt, char** __formal);
// CODEVIEW(..\stlport\stl_iterator_base.h:291, dc 0x1649dc) int* std::distance_type(char** __formal);
// CODEVIEW(..\stlport\stl_algobase.h:209, dc 0x1649e0) char** std::__copy(char** __first, char** __last, char** __result, std::random_access_iterator_tag __formal, int* __formal);
// CODEVIEW(..\stlport\stl_iterator_base.h:243, dc 0x164a00) std::random_access_iterator_tag std::iterator_category(__$ReturnUdt, std::vector<char** __formal);
// CODEVIEW(..\stlport\stl_iterator_base.h:291, dc 0x164a0c) int* std::distance_type(std::vector<char** __formal);
// CODEVIEW(..\stlport\stl_algobase.h:209, dc 0x164a10) std::vector<char** std::__copy(std::vector<char** __first, std::vector<char** __last, std::vector<char** __result, std::random_access_iterator_tag __formal, int* __formal);
// CODEVIEW(..\stlport\stl_construct.h:85, dc 0x164a30) void std::construct(char** __p, char** __value);
// CODEVIEW(..\stlport\stl_uninitialized.h:88, dc 0x164a58) char** std::__uninitialized_copy(char** __first, char** __last, char** __result, char** __formal);
// CODEVIEW(..\stlport\stl_algobase.h:382, dc 0x164a74) char** std::__copy_backward(char** __first, char** __last, char** __result, std::random_access_iterator_tag __formal, int* __formal);
// CODEVIEW(..\stlport\stl_construct.h:85, dc 0x164a98) void std::construct(std::vector<char** __p, std::vector<char** __value);
// CODEVIEW(..\stlport\stl_uninitialized.h:88, dc 0x164ac0) std::vector<char** std::__uninitialized_copy(std::vector<char** __first, std::vector<char** __last, std::vector<char** __result, std::vector<char** __formal);
// CODEVIEW(..\stlport\stl_algobase.h:382, dc 0x164adc) std::vector<char** std::__copy_backward(std::vector<char** __first, std::vector<char** __last, std::vector<char** __result, std::random_access_iterator_tag __formal, int* __formal);
// CODEVIEW(..\stlport\stl_uninitialized.h:231, dc 0x164b00) char** std::__uninitialized_fill_n_aux(char** __first, unsigned __n, char** __x, __true_type __formal);
// CODEVIEW(..\stlport\stl_construct.h:116, dc 0x164b18) void std::__destroy_aux();
// CODEVIEW(..\stlport\stl_uninitialized.h:239, dc 0x164b1c) std::vector<char** std::__uninitialized_fill_n_aux(std::vector<char** __first, unsigned __n, std::vector<char** __x, __false_type __formal);
// CODEVIEW(..\stlport\stl_construct.h:110, dc 0x164b58) void std::__destroy_aux(std::vector<char** __first, std::vector<char** __last, __false_type __formal);
// CODEVIEW(..\stlport\stl_uninitialized.h:60, dc 0x164b88) char** std::__uninitialized_copy_aux(char** __first, char** __last, char** __result, __true_type __formal);
// CODEVIEW(..\stlport\stl_uninitialized.h:70, dc 0x164ba0) std::vector<char** std::__uninitialized_copy_aux(std::vector<char** __first, std::vector<char** __last, std::vector<char** __result, __false_type __formal);
// CODEVIEW(..\stlport\stl_algobase.h:502, dc 0x164bdc) char** std::fill_n(char** __first, unsigned __n, char** __value);
// CODEVIEW(..\stlport\stl_construct.h:59, dc 0x164bf4) void std::destroy(std::vector<char** __pointer);
// CODEVIEW(..\stlport\stl_construct.h:53, dc 0x164c10) void std::__destroy_aux();

#endif  /* HOMM3_TEXTRESOURCE_H */
