#ifndef HOMM3_TRADPOST_WIDGETS_H
#define HOMM3_TRADPOST_WIDGETS_H

extern const char* gResourceNames[7];

enum EMarketWidgetId {
    MARKET_LEFT_PANEL_ID = 5,
    MARKET_RIGHT_PANEL_ID = 7,
    MARKET_LEFT_COUNT_ID = 16,
    MARKET_LEFT_LABEL_ID = 17,
    MARKET_RIGHT_LABEL_ID = 18,
    MARKET_BUY_RIGHT_LABEL_ID = 19,
    MARKET_TITLE_ID = 20,
    MARKET_SELL_WOOD_ID = 0x1c,
    MARKET_SELL_MERCURY_ID,
    MARKET_SELL_ORE_ID,
    MARKET_SELL_SULFUR_ID,
    MARKET_SELL_CRYSTAL_ID,
    MARKET_SELL_GEMS_ID,
    MARKET_SELL_GOLD_ID,
    MARKET_BUY_WOOD_ID = 0x3f,
    MARKET_BUY_MERCURY_ID,
    MARKET_BUY_ORE_ID,
    MARKET_BUY_SULFUR_ID,
    MARKET_BUY_CRYSTAL_ID,
    MARKET_BUY_GEMS_ID,
    MARKET_BUY_GOLD_ID,
    MARKET_COMMAND_ID = 0x7802
};

enum EMarketBuyArtifactSlotId {
    BUY_ARTIFACT_SLOT_0_ID = 0x3f,
    BUY_ARTIFACT_SLOT_1_ID, BUY_ARTIFACT_SLOT_2_ID,
    BUY_ARTIFACT_SLOT_3_ID, BUY_ARTIFACT_SLOT_4_ID,
    BUY_ARTIFACT_SLOT_5_ID, BUY_ARTIFACT_SLOT_6_ID
};

enum EGiveRecipientId {
    GIVE_RECIPIENT_SLOT_0_ID = 0x46,
    GIVE_RECIPIENT_SLOT_1_ID, GIVE_RECIPIENT_SLOT_2_ID,
    GIVE_RECIPIENT_SLOT_3_ID, GIVE_RECIPIENT_SLOT_4_ID,
    GIVE_RECIPIENT_SLOT_5_ID, GIVE_RECIPIENT_SLOT_6_ID
};

#endif
