#ifndef HOMM3_TRADPOST_WIDGETS_H
#define HOMM3_TRADPOST_WIDGETS_H

#include "netmsg.h"

class TGiveNetMsg : public CNetMsg {
public:
    int m_giver;
    int m_resource;
    int m_qty;

    TGiveNetMsg(int giver, int resource, int qty)
        : CNetMsg(0x432, sizeof(TGiveNetMsg)), m_giver(giver),
          m_resource(resource), m_qty(qty) {}
};

int TransmitRemoteData(CNetMsg* pMsg, int toWho, bool compressMsg,
                       bool guaranteed);

extern const char* gResourceNames[7];

enum EMarketSource {
    MARKET_SOURCE_MARKETPLACE = 0,
    MARKET_SOURCE_TRADING_POST = 1,
    MARKET_SOURCE_BLACK_MARKET = 2,
    MARKET_SOURCE_FREELANCER = 3
};

enum EMarketWidgetId {
    MARKET_LEFT_PANEL_ID = 5,
    MARKET_RIGHT_PANEL_ID = 7,
    MARKET_LEFT_COUNT_ID = 16,
    MARKET_LEFT_LABEL_ID = 17,
    MARKET_RIGHT_LABEL_ID = 18,
    MARKET_BUY_RIGHT_LABEL_ID = 19,
    MARKET_TITLE_ID = 20,
    MARKET_SELL_WOOD_ID = 0x1c,
    MARKET_SELL_MERCURY_ID,
    MARKET_SELL_ORE_ID,
    MARKET_SELL_SULFUR_ID,
    MARKET_SELL_CRYSTAL_ID,
    MARKET_SELL_GEMS_ID,
    MARKET_SELL_GOLD_ID,
    MARKET_BUY_WOOD_ID = 0x3f,
    MARKET_BUY_MERCURY_ID,
    MARKET_BUY_ORE_ID,
    MARKET_BUY_SULFUR_ID,
    MARKET_BUY_CRYSTAL_ID,
    MARKET_BUY_GEMS_ID,
    MARKET_BUY_GOLD_ID,
    MARKET_COMMAND_ID = 0x7802
};

enum EMarketBuyArtifactSlotId {
    BUY_ARTIFACT_SLOT_0_ID = 0x3f,
    BUY_ARTIFACT_SLOT_1_ID, BUY_ARTIFACT_SLOT_2_ID,
    BUY_ARTIFACT_SLOT_3_ID, BUY_ARTIFACT_SLOT_4_ID,
    BUY_ARTIFACT_SLOT_5_ID, BUY_ARTIFACT_SLOT_6_ID
};

enum EMarketArtifactSlotId {
    MARKET_ARTIFACT_SLOT_00_ID = 0x6b,
    MARKET_ARTIFACT_SLOT_01_ID, MARKET_ARTIFACT_SLOT_02_ID,
    MARKET_ARTIFACT_SLOT_03_ID, MARKET_ARTIFACT_SLOT_04_ID,
    MARKET_ARTIFACT_SLOT_05_ID, MARKET_ARTIFACT_SLOT_06_ID,
    MARKET_ARTIFACT_SLOT_07_ID, MARKET_ARTIFACT_SLOT_08_ID,
    MARKET_ARTIFACT_SLOT_09_ID, MARKET_ARTIFACT_SLOT_10_ID,
    MARKET_ARTIFACT_SLOT_11_ID, MARKET_ARTIFACT_SLOT_12_ID,
    MARKET_ARTIFACT_SLOT_13_ID, MARKET_ARTIFACT_SLOT_14_ID,
    MARKET_ARTIFACT_SLOT_15_ID, MARKET_ARTIFACT_SLOT_16_ID,
    MARKET_ARTIFACT_SLOT_17_ID, MARKET_ARTIFACT_SLOT_18_ID,
    MARKET_ARTIFACT_SLOT_19_ID, MARKET_ARTIFACT_SLOT_20_ID,
    MARKET_ARTIFACT_SLOT_21_ID, MARKET_ARTIFACT_SLOT_22_ID
};

enum EGiveRecipientId {
    GIVE_RECIPIENT_SLOT_0_ID = 0x46,
    GIVE_RECIPIENT_SLOT_1_ID, GIVE_RECIPIENT_SLOT_2_ID,
    GIVE_RECIPIENT_SLOT_3_ID, GIVE_RECIPIENT_SLOT_4_ID,
    GIVE_RECIPIENT_SLOT_5_ID, GIVE_RECIPIENT_SLOT_6_ID
};

#endif
