#ifndef HOMM3_TRADPOST_WIDGETS_H
#define HOMM3_TRADPOST_WIDGETS_H

extern const char* gResourceNames[7];

enum EMarketWidgetId {
    MARKET_LEFT_PANEL_ID = 5,
    MARKET_RIGHT_PANEL_ID = 7,
    MARKET_LEFT_COUNT_ID = 16,
    MARKET_LEFT_LABEL_ID = 17,
    MARKET_RIGHT_LABEL_ID = 18,
    MARKET_BUY_RIGHT_LABEL_ID = 19,
    MARKET_TITLE_ID = 20,
    MARKET_SELL_WOOD_ID = 0x1c,
    MARKET_SELL_MERCURY_ID,
    MARKET_SELL_ORE_ID,
    MARKET_SELL_SULFUR_ID,
    MARKET_SELL_CRYSTAL_ID,
    MARKET_SELL_GEMS_ID,
    MARKET_SELL_GOLD_ID,
    MARKET_BUY_WOOD_ID = 0x3f,
    MARKET_BUY_MERCURY_ID,
    MARKET_BUY_ORE_ID,
    MARKET_BUY_SULFUR_ID,
    MARKET_BUY_CRYSTAL_ID,
    MARKET_BUY_GEMS_ID,
    MARKET_BUY_GOLD_ID,
    MARKET_COMMAND_ID = 0x7802
};

enum EMarketWidgetCommand {
    MARKET_WIDGET_SELECT = 12,
    MARKET_WIDGET_ACTIVATE = 13,
    MARKET_WIDGET_QUICK_VIEW = 14
};

enum EMarketBuyArtifactSlotId {
    BUY_ARTIFACT_SLOT_0_ID = 0x3f,
    BUY_ARTIFACT_SLOT_1_ID, BUY_ARTIFACT_SLOT_2_ID,
    BUY_ARTIFACT_SLOT_3_ID, BUY_ARTIFACT_SLOT_4_ID,
    BUY_ARTIFACT_SLOT_5_ID, BUY_ARTIFACT_SLOT_6_ID
};

enum ESellArtifactSlotId {
    SELL_ARTIFACT_SLOT_0_ID = 0x6b,
    SELL_ARTIFACT_SLOT_1_ID, SELL_ARTIFACT_SLOT_2_ID,
    SELL_ARTIFACT_SLOT_3_ID, SELL_ARTIFACT_SLOT_4_ID,
    SELL_ARTIFACT_SLOT_5_ID, SELL_ARTIFACT_SLOT_6_ID,
    SELL_ARTIFACT_SLOT_7_ID, SELL_ARTIFACT_SLOT_8_ID,
    SELL_ARTIFACT_SLOT_9_ID, SELL_ARTIFACT_SLOT_10_ID,
    SELL_ARTIFACT_SLOT_11_ID, SELL_ARTIFACT_SLOT_12_ID,
    SELL_ARTIFACT_SLOT_13_ID, SELL_ARTIFACT_SLOT_14_ID,
    SELL_ARTIFACT_SLOT_15_ID, SELL_ARTIFACT_SLOT_16_ID,
    SELL_ARTIFACT_SLOT_17_ID, SELL_ARTIFACT_SLOT_18_ID,
    SELL_ARTIFACT_SLOT_19_ID, SELL_ARTIFACT_SLOT_20_ID,
    SELL_ARTIFACT_SLOT_21_ID, SELL_ARTIFACT_SLOT_22_ID
};

enum EMarketBackpackWidgetId {
    MARKET_BACKPACK_DISPLAY_0_ID = 0x66,
    MARKET_BACKPACK_PREVIOUS_ID = 0x82,
    MARKET_BACKPACK_NEXT_ID = 0x83
};

enum EMarketGeneralTextId {
    MARKET_GENERAL_TEXT_UNTRADEABLE_ARTIFACT = 22
};

enum {
    MARKET_EQUIPPED_ARTIFACT_SLOTS = 18,
    MARKET_VISIBLE_BACKPACK_SLOTS = 5
};

enum ESellCreatureSlotId {
    SELL_CREATURE_SLOT_0_ID = 0x8b,
    SELL_CREATURE_SLOT_1_ID, SELL_CREATURE_SLOT_2_ID,
    SELL_CREATURE_SLOT_3_ID, SELL_CREATURE_SLOT_4_ID,
    SELL_CREATURE_SLOT_5_ID, SELL_CREATURE_SLOT_6_ID
};

enum { MARKET_CREATURE_TYPE_LIMIT = 150 };

enum EGiveRecipientId {
    GIVE_RECIPIENT_SLOT_0_ID = 0x46,
    GIVE_RECIPIENT_SLOT_1_ID, GIVE_RECIPIENT_SLOT_2_ID,
    GIVE_RECIPIENT_SLOT_3_ID, GIVE_RECIPIENT_SLOT_4_ID,
    GIVE_RECIPIENT_SLOT_5_ID, GIVE_RECIPIENT_SLOT_6_ID
};

#endif
