mode = "paired_bodies"
flags = ["-O3", "-proc", "750", "-nolink"]
helpers = []
source_helpers = [
    "valueOfBuilding",
    "getRequirements",
    "getFullCost",
    "markValues",
    "maxBuyableCreatures",
    "type_AI_creature_swapper::normalizeAlignment",
    "calculateImprovement",
    "type_AI_creature_purchaser::set(TCreatureType newType, short* newAmount)",
    "attemptTeleport",
]
