mode = "paired_bodies"
flags = ["-O3", "-proc", "750", "-nolink"]
helpers = []
source_helpers = [
    "spellIsExpertOnMagicTerrain",
    "type_AI_combat_parameters::simulateSingleAttack",
    "type_AI_attack_hex_chooser::getAttackTime",
    "type_AI_spellcaster::initialize",
    "type_AI_spellcaster::type_AI_spellcaster(type_AI_spellcaster* parent, combatManager* combat, long side, unsigned char creatureSpell)",
    "type_AI_spellcaster::considerAreaEffect",
    "type_AI_spellcaster::considerMassDamage",
    "type_AI_spellcaster::getAttackBoostValue(const army* ourArmy, const army* enemy, long oldDamage, long duration, double increase) const",
    "type_AI_spellcaster::considerSummon",
    "type_AI_spellcaster::setWorstEnemies",
    "type_AI_spellcaster::addEnemy",
    "type_AI_spellcaster::checkSimulation",
    "type_AI_spellcaster::spellsNotRequired",
]
