mode = "paired_bodies"
flags = ["-O3", "-proc", "750", "-nolink"]
helpers = []
source_helpers = [
  "type_event_record::type_event_record",
  "type_record_move_hero::type_record_move_hero",
  "type_record_teleport::type_record_teleport",
  "type_record_claim_mine::type_record_claim_mine",
  "type_record_claim_town::type_record_claim_town",
]
