mode = "paired_bodies"
flags = ["-O3", "-proc", "750", "-nolink"]
helpers = []
source_helpers = [
    "advManager::doEventFreeArtifact",
    "advManager::doArtifactSkillRequirement",
    "addReward",
    "advManager::doEventBorderGate",
]
