mode = "paired_bodies"
flags = ["-O3", "-proc", "750", "-nolink"]
helpers = []
source_helpers = [
    "NewfullMap::saveSeerList",
    "NewfullMap::saveQuestGuardList",
    "readMapCreatureId",
    "readSavedCreatureId",
    "NewfullMap::readRandomDwellingData",
    "NewfullMap::readRandomDwellingLevelData",
    "NewfullMap::readRandomDwellingFactionData",
]
