mode = "paired_bodies"
flags = ["-O3", "-proc", "750", "-nolink"]
helpers = []
source_helpers = [
    "onMySide",
    "incrementHourGlass",
    "checkForTown",
    "upgradeCreatures",
    "valueOfBlackMarket",
    "buySpecialBuilding",
    "visitWarFactory",
    "getBestHero",
    "shouldGarrisonTown(const hero* currentHero, const town* currentTown)",
    "valueOfArena",
    "valueOfMapArtifact",
    "valueOfBlackBox",
    "valueOfUniversity(const hero* currentHero, NewmapCell* cell)",
    "moveAllHeroes",
    "type_spellvalue::getSummoningValue",
    "type_spellvalue::fillCreatureValueList",
    "type_spellvalue::getValueOfIncrease",
    "computeUpgradeValue",
    "valueOfSpell(const hero* currentHero, SpellID spell)",
    "aiValueOfEvent(const hero* currentHero, type_point point, long& moveCost)",
]
