mode = "paired_bodies"
flags = ["-O3", "-proc", "750", "-nolink"]
helpers = []
source_helpers = [
    "checkForTown",
    "upgradeCreatures",
    "valueOfBlackMarket",
    "buySpecialBuilding",
    "visitWarFactory",
    "getBestHero",
    "shouldGarrisonTown(const hero* currentHero, const town* currentTown)",
    "valueOfArena",
    "valueOfMapArtifact",
    "valueOfBlackBox",
    "valueOfUniversity(const hero* currentHero, NewmapCell* cell)",
    "aiValueOfEvent(const hero* currentHero, type_point point, long& moveCost)",
]
