// advspells.cpp - E:\gamedcs\advspells.cpp (compiland advspells.obj)
// HAND-OWNED after admission - INITIALLY GENERATED by `python3 -m homm3.carve carcass`; prototypes are Dreamcast CodeView evidence.
// 23 functions in link order; 20 compiler-generated $-thunks omitted.
#include <va.h>
#include "advmgr.h"
#include "advspells.h"
#include "armygrp.h"
#include "cursor.h"
#include "dimensiondoorwindow.h"
#include "exec.h"
#include "findpath.h"
#include "game.h"
#include "kb.h"
#include "misc.h"
#include "mousemgr.h"
#include "soundmgr.h"
#include "spellbookwindow.h"
#include "towngatewindow.h"
#include "winmgr.h"

// VC6's own <xutility> reference-returning max, declared file-locally for
// the reason ai_combat.cpp's copy records at length: retail materialises
// BOTH operands into stack temps and selects between their ADDRESSES,
// which is what a by-value parameter does and what the real `const _Ty&`
// signature cannot. advManager::TownGate 0x41d564..0x41d57b is this TU's
// witness - `mov [ebp+8],0` for one operand, a copy of the just-stored
// movePoints into the dead cost slot for the other, then `lea`/`lea` and
// a load through the winner.
template <class _TYPE>
// Before normalization (locals): _X, _Y.
inline const _TYPE& cppMax(_TYPE x, _TYPE y)
{
    return (x < y ? y : x);
}

// E:\gamedcs\advspells.cpp:47
VA(0x0041c2f0, 0x192)  // retail-expanded body, dc 0x2194c
void advManager::checkCastSpell()
{
    if (g_game->getCurrHeroId() == -1)
        return;

    mobilizeCurrHero(0, 0, 1);
    completeDraw(0);
    updateScreen(0, 0);
    g_mouseManager->setPointer(0, mouseManager::ADVENTURE_SET);

    // dc 0x2194c calls `game::GetCurrHero` here (byte-flat, 2026-08-15);
    // this had been the four-line `heroes[currHeroId]` expansion.
    hero* currentHero = g_game->getCurrHero();
    {
        TSpellbookWindow spellbook(currentHero, 0,
                                   TSpellbookWindow::eContextAdventure,
                                   currentHero->getSpecialTerrain());
        spellbook.doModal(0);
    }

    if (g_windowManager->m_dialogReturn == DIALOG_RETURN_CANCEL)
        return;

    TAdventureObjectType objectType = currentHero->heroFn004E4EC0();
    if (objectType == CURSED_GROUND) {
        if (g_spellTraits[g_windowManager->m_dialogReturn].m_level > 1) {
            normalDialog(
                g_generalText->getText(
                    GENERAL_TEXT_CURSED_GROUND_HIGH_LEVEL_SPELL),
                1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
        } else {
            castSpell(g_windowManager->m_dialogReturn);
        }
    } else if (objectType == GARRISON) {
        normalDialog(g_generalText->getText(
                         GENERAL_TEXT_GARRISON_ADVENTURE_SPELL),
                     1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
    } else {
        castSpell(g_windowManager->m_dialogReturn);
    }

    updBottomView(1, 1, 1);
}


// E:\gamedcs\advspells.cpp:93
// The dispatcher, and the ONE place every adventure spell is charged from.
// Ten ascending cases through a jump table; four of the arms are Dreamcast
// handlers retail has no body for, expanded here because each has exactly
// this one call site - which is what makes 1028 bytes out of the DC's 344.
// Each arm re-derives its own `who` because each inlined handler opens with
// its own game::GetHero, and the two ViewWorld arms hand their own case
// value to both ViewWorld and GetManaCost.
VA(0x0041c490, 0x404)  // linkorder + anchor-callee hero::Fly / get_spell_level, dc 0x21a2c
void advManager::castSpell(int whichSpell)
{
    hero* who = g_game->getHero(g_currentPlayer->m_currHeroId);
    if (who == 0)
        return;

    TSkillMastery level
        = who->getSpellLevel(whichSpell, who->getSpecialTerrain());

    switch (whichSpell) {
    case SPELL_SUMMON_BOAT:
        summonBoat(level);
        break;
    case SPELL_SCUTTLE_BOAT:
        skuttleBoat(level);
        break;
    case SPELL_VISIONS:
        identify(level);
        break;
    case SPELL_VIEW_EARTH:
        launchSample(DATA_COMPGEN(0x006604C4, castSpellViewSample,
                                   "view.wav"),
                      -1, 3);
        viewWorld(SPELL_VIEW_EARTH, level);
        who->useSpell(who->getManaCost(SPELL_VIEW_EARTH, 0,
                                       who->getSpecialTerrain()));
        break;
    case SPELL_DISGUISE:
        disguise(level);
        break;
    case SPELL_VIEW_AIR:
        launchSample(DATA_COMPGEN(0x006604C4, castSpellViewSample,
                                   "view.wav"),
                      -1, 3);
        viewWorld(SPELL_VIEW_AIR, level);
        who->useSpell(who->getManaCost(SPELL_VIEW_AIR, 0,
                                       who->getSpecialTerrain()));
        break;
    case SPELL_FLY:
        flight(level);
        break;
    case SPELL_WATER_WALK:
        waterWalk(level);
        break;
    case SPELL_DIMENSION_DOOR:
        dimensionDoor(level);
        break;
    case SPELL_TOWN_PORTAL:
        townGate(level);
        break;
    }
}

// E:\gamedcs\advspells.cpp:171
// Summon Boat. The caster must be ashore; the spell then looks for the
// first free water tile in the eight-neighbour order findpath's
// normalDirTable fixes, rolls against the mastery row, and either MOVES the
// hero's own summonable boat there (fizzling it out of its old square first,
// but only while that square is on the displayed 19x17 radar window) or, at
// advanced mastery and above, builds a new one.
//
// The old-position visibility test is what the two SLimitData clips are
// for: retail keeps the boat's former cell out of the fizzle when it is off
// the current view, which is why the first fizzle block carries no sample
// and the second one does.
//
// Residual (91.1002%): two classes, both recorded rather than ground.
//  * The three refusal blocks. Retail gives each dialog its OWN epilogue
//    and sends every silent (not-a-local-human) exit to the function's
//    final one; our CL cross-jumps them onto one shared block placed after
//    the first dialog, which shifts the whole later block layout. This is
//    the merged-return class. Writing `return;` INSIDE the `if` as well as
//    after it is byte-flat, so it is not source-reachable from here.
//  * `[ebp+8]` reloads inside the radar-window test: retail keeps the
//    extracted origin in ECX across `movsx edx,dx` and stores it back,
//    where we spill and re-read - one extra instruction in each of two
//    blocks. Register pressure, not a spelling.
// Also measured: `break` out of the search loop plus a post-loop
// `direction == MAP_DIRECTION_COUNT` test scores 91.4864 - HIGHER - but it
// emits a compare retail does not have (32 branches against retail's 31)
// and leaves 12 exact blocks against this version's 14. The `goto` is the
// faithful shape: retail's loop simply falls out into the message.
// Byte-flat: `radarOrigin.z == theBoat->z` operand order (91.09).
VA(0x0041c8a0, 0x54D)  // anchor-callee hero::find_summonable_boat + game::CreateBoat, dc 0x21b84
void advManager::summonBoat(int level)
{
    const SSpellTraits* traits = &g_spellTraits[SPELL_SUMMON_BOAT];

    hero* who = g_game->getHero(g_currentPlayer->m_currHeroId);
    if (who == 0)
        return;

    if (getCell(who->getLocation())->m_groundSet == eTerrainWater) {
        if (g_game->isLocalHuman(who->m_owner)) {
            sprintf(g_text,
                    g_generalText->getText(
                        GENERAL_TEXT_SUMMON_BOAT_ALREADY_AT_SEA_FORMAT),
                    who->m_name);
            normalDialog(g_text, 1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
        }
        return;
    }

    int destX;
    int destY;
    int direction;
    for (direction = 0; direction < MAP_DIRECTION_COUNT; direction++) {
        destX = who->m_x + g_normalDirTable[direction].m_x;
        destY = who->m_y + g_normalDirTable[direction].m_y;
        if (destX >= 0 && destX < g_mapWidth && destY >= 0
            && destY < g_mapHeight) {
            NewmapCell* cell = getCell(type_point(destX, destY, who->m_z));
            if (cell->m_typeValue == 0 && cell->m_groundSet == eTerrainWater)
                goto found;
        }
    }
    if (g_game->isLocalHuman(who->m_owner)) {
        normalDialog(
            g_generalText->getText(GENERAL_TEXT_SUMMON_BOAT_NO_WATER),
            1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
    }
    return;

found:
    if (random(1, 100) <= traits->m_masteryBonus[level]) {
        boat* theBoat = who->findSummonableBoat();
        if (theBoat != 0) {
            theBoat->restoreCell();
            // Only fizzle the boat's OLD square while it is on the radar
            // window - 19 cells across and 17 down from radarOrigin.
            if (theBoat->m_z == m_radarOrigin.m_z
                && theBoat->m_x >= m_radarOrigin.m_x
                && theBoat->m_x < m_radarOrigin.m_x + 19
                && theBoat->m_y >= m_radarOrigin.m_y
                && theBoat->m_y < m_radarOrigin.m_y + 17) {
                int oldX = theBoat->m_x - m_radarOrigin.m_x;
                int oldY = theBoat->m_y - m_radarOrigin.m_y;
                SLimitData oldLimits(32 * oldX - 32, 32 * oldY - 32,
                                     32 * (oldX + 3), 32 * (oldY + 2));
                oldLimits.clip(g_advMapViewLimits);
                g_windowManager->saveFizzleSourceX(
                    oldLimits.m_minX, oldLimits.m_minY, oldLimits.width(),
                    oldLimits.height());
                completeDraw(0);
                g_windowManager->fizzleForwardX(
                    oldLimits.m_minX, oldLimits.m_minY, oldLimits.width(),
                    oldLimits.height(), -1);
            }
            theBoat->m_x = destX;
            theBoat->m_y = destY;
            theBoat->m_z = who->m_z;
            theBoat->obscureCell();
        } else {
            if (level < 2
                || g_game->createBoat(destX, destY, who->m_z, who->m_owner, 0, 0)
                       < 0) {
                if (g_game->isLocalHuman(who->m_owner)) {
                    normalDialog(
                        g_generalText->getText(
                            GENERAL_TEXT_SUMMON_BOAT_NONE_AVAILABLE),
                        1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
                }
                return;
            }
        }

        int cellX = destX - m_radarOrigin.m_x;
        int cellY = destY - m_radarOrigin.m_y;
        SLimitData limits(32 * cellX - 32, 32 * cellY - 32,
                          32 * (cellX + 3), 32 * (cellY + 2));
        limits.clip(g_advMapViewLimits);

        SAMPLE2 sample = loadPlaySample(traits->m_sample);
        g_windowManager->saveFizzleSourceX(limits.m_minX, limits.m_minY,
                                           limits.width(), limits.height());
        completeDraw(0);
        g_windowManager->fizzleForwardX(limits.m_minX, limits.m_minY,
                                        limits.width(), limits.height(), -1);
        updateScreen(0, 0);
        reseed(0, 0);
        waitEndSample(sample, -1);
    } else if (g_game->isLocalHuman(who->m_owner)) {
        sprintf(g_text,
                g_generalText->getText(GENERAL_TEXT_SUMMON_BOAT_FAILED_FORMAT),
                who->m_name);
        normalDialog(g_text, 1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
    }

    who->useSpell(who->getManaCost(SPELL_SUMMON_BOAT, 0,
                                   who->getSpecialTerrain()));
}


// E:\gamedcs\advspells.cpp:328
// The Scuttle Boat handler. TSkuttleBoatWindow picks the target; a
// cancelled pick (dialogReturn 0) posts the same general-text row 732
// DimensionDoor posts and charges nothing. Otherwise the mastery roll
// decides, and BOTH outcomes fall through to the shared UseSpell tail -
// retail charges the mana whether or not the boat actually sank.
// Residual (98.4651%): a pure callee-saved transposition - retail binds
// `this` to EBX and the shared zero to EDI, we bind them the other way
// round, and the swap propagates through the rect math (ebx->edi x15,
// edi->ebx x6). why-reg --model reports the definition slots and their
// ORDER agreeing on both sides with only the bindings permuted, i.e. C1
// handle state rather than a spelling; its one model-filtered candidate
// (swap the cellX/cellY declarations) doubles the distance. Tried and
// rejected, both byte-flat: splitting `hero* who` into a declaration plus
// a later assignment to make it the earliest call-crossing pseudo, and
// the const-receiver cast below (which buys the right callee NAME and no
// bytes). 18/18 blocks exact, branches clean, call streams positionally
// identical.
VA(0x0041cdf0, 0x29D)  // anchor-vtable TSkuttleBoatWindow ctor/dtor, dc 0x22054
void advManager::skuttleBoat(int level)
{
    const SSpellTraits* traits = &g_spellTraits[SPELL_SCUTTLE_BOAT];

    {
        TSkuttleBoatWindow window;
        window.doModal(0);
    }

    if (g_windowManager->m_dialogReturn == 0) {
        normalDialog(
            g_generalText->getText(GENERAL_TEXT_ADVENTURE_SPELL_NO_TARGET),
            1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
        return;
    }

    hero* who = g_currentPlayer->m_currHeroId != -1
                    ? &g_game->m_heroes[g_currentPlayer->m_currHeroId]
                    : 0;

    if (random(1, 100)
        <= g_spellTraits[SPELL_SCUTTLE_BOAT].m_masteryBonus[level]) {
        // The CONST get_map_center overload is the one retail calls here
        // (?get_map_center@advManager@@QBE...); /OPT:ICF folded the pair onto
        // one row, so the receiver cast costs no bytes and buys the name.
        boat& theBoat = g_game->m_boats[
            getCell(static_cast<const advManager*>(this)->getMapCenter())
                ->m_extraInfo];
        theBoat.restoreCell();

        // The fizzle covers the boat's sprite footprint: one cell of slack
        // left and above, three cells wide and two deep, in 32-pixel map
        // cells relative to the current radar origin.
        int cellX = theBoat.m_x - m_radarOrigin.m_x;
        int cellY = theBoat.m_y - m_radarOrigin.m_y;
        SLimitData limits(32 * cellX - 32, 32 * cellY - 32,
                          32 * (cellX + 3), 32 * (cellY + 2));
        limits.clip(g_advMapViewLimits);

        SAMPLE2 sample = loadPlaySample(traits->m_sample);
        g_windowManager->saveFizzleSourceX(limits.m_minX, limits.m_minY,
                                           limits.width(), limits.height());
        completeDraw(0);
        g_windowManager->fizzleForwardX(limits.m_minX, limits.m_minY,
                                        limits.width(), limits.height(), -1);
        theBoat.m_allocated = 0;
        reseed(0, 0);
        waitEndSample(sample, -1);
    } else if (g_game->isLocalHuman(who->m_owner)) {
        sprintf(g_text,
                g_generalText->getText(
                    GENERAL_TEXT_SCUTTLE_BOAT_FAILED_FORMAT),
                who->m_name);
        normalDialog(g_text, 1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
    }

    who->useSpell(who->getManaCost(SPELL_SCUTTLE_BOAT, 0,
                                   who->getSpecialTerrain()));
}

// E:\gamedcs\advspells.cpp:397
// The order-map over advspells.obj's seven retail bodies is settled by
// three constructor calls, not by size: 0x41cdf0 builds a
// TSkuttleBoatWindow, THIS body builds a TDimensionDoorWindow and 0x41d360
// builds a TTownGateWindow, which fixes SkuttleBoat / DimensionDoor /
// TownGate against the Dreamcast's own advspells.cpp line order. The four
// small DC handlers between TownGate and TeleportTo (Identify 220 B,
// WaterWalk 122 B, Disguise 90 B, Flight 236 B) have no retail slot at all
// and no gap to hide in: their 668 bytes are what makes CastSpell 1028
// against the DC's 344, and 0x41c490 calls hero::Fly - Flight's own body -
// with no out-of-line Flight anywhere in the image.
VA(0x0041d090, 0x2C6)  // anchor-vtable TDimensionDoorWindow ctor/dtor + anchor-callee TeleportTo, dc 0x2225c
void advManager::dimensionDoor(int level)
{
    const SSpellTraits* traits = &g_spellTraits[SPELL_DIMENSION_DOOR];
    hero* who = g_currentPlayer->m_currHeroId != -1
                    ? &g_game->m_heroes[g_currentPlayer->m_currHeroId]
                    : 0;
    if (who->m_movePoints <= 0) {
        if (g_game->isLocalHuman(who->m_owner)) {
            normalDialog(
                g_generalText->getText(GENERAL_TEXT_SPELL_NEEDS_MOVEMENT),
                1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
        }
        return;
    }

    TSkillMastery mastery = who->getSpellLevel(SPELL_DIMENSION_DOOR,
                                                 who->getSpecialTerrain());
    if (who->m_dWalkSpellsCast >= traits->m_masteryBonus[mastery]) {
        if (g_game->isLocalHuman(who->m_owner)) {
            sprintf(g_text,
                    g_generalText->getText(
                        GENERAL_TEXT_DIMENSION_DOOR_LIMIT_FORMAT),
                    who->m_name);
            normalDialog(g_text, 1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
        }
        return;
    }

    {
        TDimensionDoorWindow window;
        window.doModal(0);
    }

    type_point destination = getMapCenter();
    if (destination.isValid() && g_windowManager->m_dialogReturn == 1) {
        NewmapCell* cell = getCell(destination);
        if (((who->m_flags & 0x40000) != 0
             && cell->m_groundSet != eTerrainWater)
            || ((who->m_flags & 0x40000) == 0
                && cell->m_groundSet == eTerrainWater)) {
            if (g_game->isLocalHuman(who->m_owner)) {
                normalDialog(
                    g_generalText->getText(
                        GENERAL_TEXT_DIMENSION_DOOR_BLOCKED),
                    1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
            }
            updateRadar(1, 1, 0, 0, 0);
        } else {
            teleportTo(who, destination, traits->m_sample, 0, 1, 0);
        }
        who->m_movePoints -= level == eMasteryExpert ? 200 : 300;
        if (who->m_movePoints < 0)
            who->m_movePoints = 0;
        who->useSpell(who->getManaCost(SPELL_DIMENSION_DOOR, 0,
                                       who->getSpecialTerrain()));
        m_advWindow->updateHeroLocator(-1, 1, 1);
        reseed(0, 0);
        ++who->m_dWalkSpellsCast;
        return;
    }

    updateRadar(1, 1, 0, 0, 0);
    normalDialog(
        g_generalText->getText(GENERAL_TEXT_ADVENTURE_SPELL_NO_TARGET),
        1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
}

// E:\gamedcs\advspells.cpp:485
// Town Portal. Three refusals up front (no movement, no team town, cast
// from a boat), then the destination: at advanced/expert mastery a
// TTownGateWindow lists every eligible town, at novice/basic the caster is
// sent to the NEAREST one, chosen by squared map distance with no z term.
//
// The two loops that pick a town both spell the team test as
// game::OnSameTeam - retail expands its `||` guard, the two teamInfo byte
// loads off gpGame+0x1f879 and the `sete` verbatim - and both reach the
// record through game::GetTown, whose -1 arm survives as the
// `inc/neg/sbb/and` mask even though the index can never be -1 here.
//
// The AddTown call is the row src/towngatewindow.cpp currently claims as
// VA_COMPGEN(0x005c2400, VECTOR_INSERT, widget): retail reaches it
// THISCALL on the window with ONE stack argument and its body works on
// `this + 0x60`, i.e. TTownGateWindow::Towns with push_back expanded into
// it. That is AddTown, not a free vector COMDAT - see the lane report.
//
// Residual (99.0409%): one scheduling hunk inside the FIRST
// DistanceSquared expansion - retail extracts p2->x fully (load/shl/movsx)
// before loading this->x, we load both units and then process them. The dy
// half already agrees. Measured and rejected: the folded
// `(x-p2->x)*(x-p2->x) + ...` body (95.20), `return dy*dy + dx*dx`
// (byte-flat), and swapping the receiver to
// `townLocation.DistanceSquared(&heroLocation)` (98.22). Declaring `dy`
// BEFORE `dx` is what took it 98.21 -> 99.04. Everything else is
// reloc-NAME only: gpGeneralText, TeleportTo's own stub and the AddTown
// mislabel, all of which the ratchet report ignores.
VA(0x0041d360, 0x5C8)  // anchor-vtable TTownGateWindow ctor/dtor, dc 0x22510
void advManager::townGate(int level)
{
    const SSpellTraits* traits = &g_spellTraits[SPELL_TOWN_PORTAL];
    int movementCost[4] = {300, 300, 300, 200};
    hero* who = g_currentPlayer->m_currHeroId != -1
                    ? &g_game->m_heroes[g_currentPlayer->m_currHeroId]
                    : 0;

    int cost = movementCost[level];
    if (who->m_movePoints < cost) {
        if (g_game->isLocalHuman(who->m_owner)) {
            normalDialog(
                g_generalText->getText(GENERAL_TEXT_SPELL_NEEDS_MOVEMENT),
                1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
        }
        return;
    }

    int numTowns = 0;
    for (unsigned i = 0; i < g_game->m_towns.size(); i++) {
        if (g_game->onSameTeam(who->m_owner, g_game->m_towns[i].m_owner))
            numTowns++;
    }
    if (numTowns == 0) {
        if (g_game->isLocalHuman(who->m_owner)) {
            normalDialog(
                g_generalText->getText(GENERAL_TEXT_TOWN_PORTAL_NO_TOWN),
                1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
        }
        return;
    }

    if ((who->m_flags & 0x40000) != 0) {
        if (g_game->isLocalHuman(who->m_owner)) {
            normalDialog(
                g_generalText->getText(GENERAL_TEXT_SPELL_NOT_FROM_BOAT),
                1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
        }
        return;
    }

    int selectedTown;
    if (level >= 2) {
        TTownGateWindow window(1);
        for (unsigned i = 0; i < g_game->m_towns.size(); i++) {
            if (g_game->onSameTeam(who->m_owner, g_game->m_towns[i].m_owner)
                && g_game->getTown(i)->m_visitingHeroId == -1) {
                window.addTown(i);
            }
        }
        window.doModal();
        selectedTown = g_windowManager->m_dialogReturn;
    } else {
        type_point heroLocation = who->getLocation();
        int nearest = -1;
        int nearestDistance = 0x7fffffff;
        for (unsigned i = 0; i < g_game->m_towns.size(); i++) {
            if (g_game->onSameTeam(who->m_owner, g_game->m_towns[i].m_owner)) {
                type_point townLocation = g_game->getTown(i)->getLocation();
                if (heroLocation.distanceSquared(&townLocation)
                    < nearestDistance) {
                    nearest = i;
                    nearestDistance
                        = heroLocation.distanceSquared(&townLocation);
                }
            }
        }
        selectedTown = nearest;
    }

    if (selectedTown == -1)
        return;

    town* destination = &g_game->m_towns[selectedTown];
    if (destination->m_visitingHeroId != -1) {
        if (g_game->isLocalHuman(who->m_owner)) {
            normalDialog(
                g_generalText->getText(
                    GENERAL_TEXT_TOWN_PORTAL_TOWN_OCCUPIED),
                1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
        }
        return;
    }

    teleportTo(who, destination->getLocation(), traits->m_sample, 0, 1, 0);
    destination->giveSpells(0);
    who->m_movePoints -= cost;
    who->m_movePoints = cppMax(who->m_movePoints, 0);
    who->useSpell(who->getManaCost(SPELL_TOWN_PORTAL, 0,
                                   who->getSpecialTerrain()));
    m_advWindow->updateHeroLocator(-1, 1, 1);
    if (g_game->m_mapHeader.m_victoryCondition.checkForArtifactTransportWin(
            who, destination->getLocation())) {
        checkEndGame(0);
    }
}

// E:\gamedcs\advspells.cpp:605
// Visions. Raises the caster's own visions level, posts the confirmation
// line and charges the mana; the sample runs across all of it.
DC_ONLY(0x228e8, 0xDC)
void advManager::identify(int level)
{
    hero* who = g_currentPlayer->m_currHeroId != -1
                    ? &g_game->m_heroes[g_currentPlayer->m_currHeroId]
                    : 0;
    SAMPLE2 sample = loadPlaySample(g_spellTraits[SPELL_VISIONS].m_sample);
    who->m_visionsPower = level;
    if (g_game->isLocalHuman(who->m_owner)) {
        normalDialog(g_generalText->getText(GENERAL_TEXT_VISIONS_CAST),
                     1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
    }
    who->useSpell(who->getManaCost(SPELL_VISIONS, 0,
                                   who->getSpecialTerrain()));
    waitEndSample(sample, -1);
}

// E:\gamedcs\advspells.cpp:629
// Water Walk. hero::CanWalkOnWater is the whole gate - already walking, or
// wearing the boots (artifact 0x5a), and nothing happens; aboard a boat the
// helper answers no and the spell runs.
DC_ONLY(0x229c4, 0x7A)
void advManager::waterWalk(int level)
{
    const SSpellTraits* traits = &g_spellTraits[SPELL_WATER_WALK];
    hero* who = g_currentPlayer->m_currHeroId != -1
                    ? &g_game->m_heroes[g_currentPlayer->m_currHeroId]
                    : 0;
    if (who->canWalkOnWater(0))
        return;

    SAMPLE2 sample = loadPlaySample(traits->m_sample);
    who->walkOnWater(level);
    reseed(0, 0);
    who->useSpell(who->getManaCost(SPELL_WATER_WALK, 0,
                                   who->getSpecialTerrain()));
    waitEndSample(sample, -1);
}

// E:\gamedcs\advspells.cpp:654
// Disguise. The shortest of the four: set the level, charge, wait.
DC_ONLY(0x22a40, 0x5A)
void advManager::disguise(int level)
{
    hero* who = g_currentPlayer->m_currHeroId != -1
                    ? &g_game->m_heroes[g_currentPlayer->m_currHeroId]
                    : 0;
    SAMPLE2 sample = loadPlaySample(g_spellTraits[SPELL_DISGUISE].m_sample);
    who->m_disguiseLevel = level;
    who->useSpell(who->getManaCost(SPELL_DISGUISE, 0,
                                   who->getSpecialTerrain()));
    waitEndSample(sample, -1);
}

// E:\gamedcs\advspells.cpp:674
// Fly. hero::IsFlying gates it exactly as CanWalkOnWater gates Water Walk,
// but the boat case is not silent here - it gets its own refusal line, and
// retail re-reads the boat bit for that second test rather than reusing the
// one IsFlying already made. hero::Fly charges the mana itself.
DC_ONLY(0x22a9c, 0xEC)
void advManager::flight(int level)
{
    const SSpellTraits* traits = &g_spellTraits[SPELL_FLY];
    hero* who = g_currentPlayer->m_currHeroId != -1
                    ? &g_game->m_heroes[g_currentPlayer->m_currHeroId]
                    : 0;
    if (who->isFlying(0))
        return;

    if ((who->m_flags & 0x40000) != 0) {
        normalDialog(
            g_generalText->getText(GENERAL_TEXT_SPELL_NOT_WHILE_ON_BOAT),
            1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
        return;
    }

    SAMPLE2 sample = loadPlaySample(traits->m_sample);
    who->fly(level);
    reseed(0, 0);
    waitEndSample(sample, -1);
}

// E:\gamedcs\advspells.cpp:703
// The shared teleport primitive: Dimension Door, Town Portal, both lith
// handlers and townmgr's DoTownGate all land here. gCompleteDrawEnabled is
// SAVED at entry and RESTORED at exit, and in between it is this body's own
// working "did anything visible change" flag - which is why almost every
// block below is gated on it.
//
// Its three parameters do three different jobs: bIsRemoteMove means another
// machine's hero, so no map-change packet, no recentring and no fizzle -
// just re-obscure the cell; is_replay only suppresses the packet; and
// draw_changes decides whether the sample plays and whether the visibility
// scan runs at all.
VA(0x0041d930, 0x464)  // anchor-import telptout.wav + arity ret 0x18, dc 0x22b88
void advManager::teleportTo(hero* who, type_point destination,
                            // Before normalization (locals): sample_name, bIsRemoteMove,
                            // draw_changes, is_replay.
                            const char* sampleName,
                            unsigned char isRemoteMove,
                            unsigned char drawChanges,
                            unsigned char isReplay)
{
    int savedCompleteDraw = g_completeDrawEnabled;
    if (!drawChanges)
        g_completeDrawEnabled = 0;

    if (!isRemoteMove && !isReplay) {
        CMCTeleportHero mapChange(who->m_id, destination);
        sendMapChange(&mapChange);
        g_game->recordTeleport(who, destination);
    }

    NewmapCell* destinationCell = getCell(destination);
    getCell(who->getLocation());

    unsigned char wasMobile = m_curHeroMobile;
    setHeroContext(who->m_id, 0, 0, drawChanges);

    SAMPLE2 sample;
    sample.m_playSample = 0;
    if (drawChanges || g_currentPlayer->isLocalHuman()) {
        sample = loadPlaySample(sampleName);
        completeDraw(0);
        if (drawChanges && !g_currentPlayer->isLocalHuman()) {
            if ((g_unnamed698790 == 0
                 && mapExtraPosAndAdjacentsSet(who->m_x, who->m_y, who->m_z,
                                               g_mapVisibilityBit))
                || mapExtraPosAndAdjacentsSet(destination.m_x, destination.m_y,
                                              destination.m_z,
                                              g_mapVisibilityBit)) {
                g_completeDrawEnabled = 1;
            } else {
                g_completeDrawEnabled = 0;
            }
        }
    }
    if (g_completeDrawEnabled)
        hideRoute(1, 1, 1);

    if (!isRemoteMove) {
        if (g_completeDrawEnabled || g_currentPlayer->isLocalHuman()) {
            // The map view is 19x17 cells, so the origin lands nine left
            // and eight up from the arrival square.
            m_radarOrigin.m_x = destination.m_x - 9;
            m_radarOrigin.m_y = destination.m_y - 8;
            m_radarOrigin.m_z = destination.m_z;
            m_advWindow->setElevationToggleImage(m_radarOrigin.m_z);
        }
    } else {
        who->restoreCell();
    }

    who->m_x = destination.m_x;
    who->m_y = destination.m_y;
    who->m_z = destination.m_z;
    g_game->setVisibility(destination.m_x, destination.m_y, destination.m_z,
                          g_netLocalGamePos, who->getVisibility(),
                          isRemoteMove);

    if ((g_completeDrawEnabled || g_currentPlayer->isLocalHuman())
        && !isRemoteMove) {
        if (g_completeDrawEnabled) {
            g_windowManager->saveFizzleSourceX(8, 8, 0x250, 0x220);
            g_advManager->redrawAdvScreen(0, 0);
            g_windowManager->fizzleForwardX(8, 8, 0x250, 0x220, -1);
            if (sample.m_playSample != 0)
                waitEndSample(sample, -1);
        }
    } else {
        m_drawCursor = 0;
        if (isRemoteMove)
            who->obscureCell();
    }

    if (!wasMobile)
        demobilizeCurrHero(0, drawChanges);

    if (g_completeDrawEnabled) {
        setEnvironmentOrigin(type_point(m_radarOrigin.m_x + 9, m_radarOrigin.m_y + 8,
                                        m_radarOrigin.m_z),
                             1);
    }

    if (destinationCell->m_groundSet != m_lastTerrain && g_completeDrawEnabled) {
        m_lastTerrain = destinationCell->m_groundSet;
        g_soundManager->switchAmbientMusic(g_terrainMusicIds[m_lastTerrain]);
    }

    reseed(0, 0);
    if (g_completeDrawEnabled) {
        updateRadar(1, 1, 0, 0, 0);
        completeDraw(0);
        forceNewHover();
    }

    g_completeDrawEnabled = savedCompleteDraw;
}

#if 0  // @carcass: remaining untouched bodies (continued)
// E:\gamedcs\struct.h:120
DC_ONLY(0x22fe4, 0x2E)
int type_point::distanceSquared(const type_point* p2)
{
    // @stub
}

// E:\gamedcs\struct.h:277
DC_ONLY(0x23014, 0xA)
int SLimitData::Width()
{
    // @stub
}

// E:\gamedcs\struct.h:280
DC_ONLY(0x23020, 0xA)
int SLimitData::Height()
{
    // @stub
}

// E:\gamedcs\struct.h:306
DC_ONLY(0x2302c, 0x2C)
void SLimitData::clip(const SLimitData* clip_limits)
{
    // @stub
}

// E:\gamedcs\Hero.h:707
DC_ONLY(0x23058, 0x34)
int hero::getManaCost(int iWhichSpell)
{
    // @stub
}

// E:\gamedcs\Hero.h:718
DC_ONLY(0x2308c, 0x30)
TSkillMastery hero::getSpellLevel(SpellID spell)
{
    // @stub
}

// E:\gamedcs\WinMgr.h:181
DC_ONLY(0x230bc, 0x48)
void heroWindowManager::SaveFizzleSource(const SLimitData* limits)
{
    // @stub
}

// E:\gamedcs\WinMgr.h:187
DC_ONLY(0x23104, 0x50)
void heroWindowManager::FizzleForward(const SLimitData* limits, int fadeTime)
{
    // @stub
}

// E:\gamedcs\netmsg.h:532
DC_ONLY(0x23154, 0x1C)
void CMapChange::CMapChange(eRS_Messages id, unsigned long size)
{
    // @stub
}

// E:\gamedcs\netmsg.h:563
DC_ONLY(0x23170, 0x54)
void CMCTeleportHero::CMCTeleportHero(signed char heroId, type_point point)
{
    // @stub
}

// ..\stlport\stl_limits.h:140
DC_ONLY(0x231c4, 0xC)
int std::_Integer_limits<int,-2147483648,2147483647,-1>::max()
{
    // @stub
}

// ..\stlport\stl_vector.h:195
DC_ONLY(0x231d0, 0x20)
unsigned std::vector<town,std::allocator<town> >::size()
{
    // @stub
}
#endif  // @carcass
