// army.cpp - E:\gamedcs\army.cpp (compiland army.obj)
// HAND-OWNED after admission - INITIALLY GENERATED by `python3 -m homm3.carve carcass`; prototypes are Dreamcast CodeView evidence.
// 182 functions in link order; 20 compiler-generated $-thunks omitted.
#include <va.h>
#include "army.h"
#include "armygrp.h"
#include "cmbtmgr.h"
#include "hero.h"
#include "sample.h"
#include "soundmgr.h"
#include "town.h"

// VC6 <xutility>'s reference-returning min/max, taken BY VALUE - the
// orientation byte-proven engine-wide (findpath.cpp carries the
// measurement; the `const _TYPE&` signature was refuted there). The
// operand landing in the HIGHER stack slot is _Y: every army.obj site
// below (get_total_hit_points, set_AI_expected_damage,
// get_average_damage, ComputeBaseDamage) reproduces that placement
// together with the branch polarity the retail body emits.
template <class _TYPE>
inline const _TYPE& _cpp_min(_TYPE _X, _TYPE _Y)
{
    return (_Y < _X ? _Y : _X);
}

template <class _TYPE>
inline const _TYPE& _cpp_max(_TYPE _X, _TYPE _Y)
{
    return (_X < _Y ? _Y : _X);
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:52
DC_ONLY(0x436b8, 0xF4)
void army::army()
{
    // @stub
}

// E:\gamedcs\army.cpp:77
DC_ONLY(0x437ac, 0x84)
void army::set_retaliation_count()
{
    // @stub
}

// E:\gamedcs\army.cpp:93
#endif  // @carcass

VA(0x0043d540, 0x34)  // anchor-global, dc 0x43830
void army::play_sample(army::TSampleID id)
{
    if (!static_cast<const combatManager*>(gpCombatManager)->IsQuickCombat()
        && armySample[id]) {
        gpSoundManager->MemorySample(armySample[id]);
    }
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:101
#endif  // @carcass

VA(0x0043d580, 0x37)  // anchor-global, dc 0x4386c
void army::stop_sample(army::TSampleID id)
{
    if (!static_cast<const combatManager*>(gpCombatManager)->IsQuickCombat()
        && armySample[id]) {
        gpSoundManager->StopSample(armySample[id]->field_1c);
    }
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:109
DC_ONLY(0x438a8, 0x3E)
void army::WaitSample(army::TSampleID which)
{
    // @stub
}

// E:\gamedcs\army.cpp:117
DC_ONLY(0x438e8, 0xC8)
void army::InitClean()
{
    // @stub
}

// E:\gamedcs\army.cpp:150
DC_ONLY(0x439b0, 0x3EA)
void army::initialize(TCreatureType type, long number, const hero* owner, long new_group, long new_index, long new_grid_index)
{
    // @stub
}

// E:\gamedcs\army.cpp:261
DC_ONLY(0x43d9c, 0xE4)
void army::Init(int armyId, int newNumTroops, const hero* owner, int side, int inIndex, int iGridIndex, int iOrigPos)
{
    // @stub
}

// E:\gamedcs\army.cpp:288
DC_ONLY(0x43e80, 0x3CA)
void army::LoadResources()
{
    // @stub
}

// E:\gamedcs\army.cpp:477
DC_ONLY(0x4424c, 0xCC)
void army::FreeResources()
{
    // @stub
}

// E:\gamedcs\army.cpp:507
#endif  // @carcass

// The DC six-argument signature is exact except that its final bool is a
// full magic-terrain mode in retail. The body and its selector table prove
// Cursed Ground (2), Clover Field (5), the Halfling minimum, both Hourglass
// hero gates, and the four timed-modifier fields adjacent to SetMorale's.
// Residual (97.0115%): all executable code agrees except the Halfling's
// dedicated minimum tail. Retail emits `mov eax,1; mov [luck],eax`; the
// direct guard below emits `mov [luck],1` and one alignment NOP. Naming the
// constant is byte-neutral; reference and by-value selector forms disturb
// the proven CFG (81.60% / 81.71%), so the natural guard is retained.
VA(0x0043df20, 0xDD)  // anchor-global + complete body, dc 0x44318
void army::SetLuck(const hero* ownerHero, const armyGroup* ownerGroup,
                   const town* ownerTown, const hero* otherHero,
                   const armyGroup* otherGroup, int magicTerrain)
{
    int value = 0;
    if (magicTerrain == MAGIC_TERRAIN_CURSED_GROUND)
        goto store_luck;
    if (ownerHero
        && const_cast<hero*>(ownerHero)->IsWieldingArtifact(
            ARTIFACT_HOURGLASS_OF_THE_EVIL_HOUR)) {
        goto store_luck;
    }
    if (otherHero
        && const_cast<hero*>(otherHero)->IsWieldingArtifact(
            ARTIFACT_HOURGLASS_OF_THE_EVIL_HOUR)) {
        goto store_luck;
    }

    if (ownerGroup) {
        value = const_cast<armyGroup*>(ownerGroup)->GetLuck(
            ownerHero, ownerTown, otherHero, otherGroup, 0, 0);
    }
    if (luckBonusRounds)
        value += luckBonus;
    if (luckPenaltyRounds)
        value -= luckPenalty;

    if (magicTerrain == MAGIC_TERRAIN_CLOVER_FIELD) {
        switch (monInfoTownType) {
        case TOWN_CASTLE:
        case TOWN_RAMPART:
        case TOWN_TOWER:
        case TOWN_INFERNO:
        case TOWN_NECROPOLIS:
        case TOWN_DUNGEON:
            goto no_clover_bonus;
        case TOWN_STRONGHOLD:
        case TOWN_FORTRESS:
        case TOWN_CONFLUX:
            value += 2;
            break;
        }
no_clover_bonus:
        ;
    }

    if (creatureType == CREATURE_HALFLING && value < 1) {
        luck = 1;
        return;
    }
store_luck:
    luck = value;
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:540
#endif  // @carcass

// Retail corrects the DC signature with a seventh, byte-wide alignment gate:
// the sole live caller passes it after the magic-terrain mode and the body
// forwards it to armyGroup::GetMorale. The two compressed switch tables at
// 0x43e10c/0x43e124 match GetArmyMorale's Holy Ground / Evil Fog partition.
// Residual (97.5194%): every branch, call, member access and both selector
// tables agree. The two executable deltas are instruction-selection twins:
// `cmp ownerGroup,0` vs retail's `test`, and `mov [morale],0` vs retail's
// `xor eax,eax; mov [morale],eax`. A branch-result local merges the retail-
// duplicated exits (91.75%), a four-byte memset is worse (95.81%), and `false`
// plus `value-value` both fold byte-identically to the retained direct zero.
VA(0x0043e000, 0x139)  // dc-bracket forced + body/caller proof, dc 0x443b4
void army::SetMorale(const hero* ownerHero, const armyGroup* ownerGroup,
                     const town* ownerTown, const hero* otherHero,
                     const armyGroup* otherGroup, int magicTerrain,
                     unsigned char groupAlignments)
{
    int value = 0;
    if (magicTerrain == MAGIC_TERRAIN_CURSED_GROUND || (Is(17) & 1)) {
        morale = value;
        return;
    }

    if (ownerGroup) {
        value = const_cast<armyGroup*>(ownerGroup)->GetMorale(
            ownerHero, ownerTown, otherHero, otherGroup, 0,
            groupAlignments, 0);
    }
    if (moraleBonusRounds)
        value += moraleBonus;
    if (moralePenaltyRounds)
        value -= moralePenalty;

    if (magicTerrain == MAGIC_TERRAIN_HOLY_GROUND) {
        switch (monInfoTownType) {
        case TOWN_CASTLE:
        case TOWN_RAMPART:
        case TOWN_TOWER:
            ++value;
            break;
        case TOWN_INFERNO:
        case TOWN_NECROPOLIS:
        case TOWN_DUNGEON:
            --value;
            break;
        case TOWN_STRONGHOLD:
        case TOWN_FORTRESS:
        case TOWN_CONFLUX:
            goto holy_done;
        }
holy_done:
        ;
    }
    if (magicTerrain == MAGIC_TERRAIN_EVIL_FOG) {
        switch (monInfoTownType) {
        case TOWN_CASTLE:
        case TOWN_RAMPART:
        case TOWN_TOWER:
            --value;
            break;
        case TOWN_INFERNO:
        case TOWN_NECROPOLIS:
        case TOWN_DUNGEON:
            ++value;
            break;
        case TOWN_STRONGHOLD:
        case TOWN_FORTRESS:
        case TOWN_CONFLUX:
            goto evil_done;
        }
evil_done:
        ;
    }

    if ((creatureType == CREATURE_MINOTAUR
         || creatureType == CREATURE_MINOTAUR_KING)
        && value < 1) {
        value = 1;
    }
    if (ownerHero
        && const_cast<hero*>(ownerHero)->IsWieldingArtifact(
            ARTIFACT_SPIRIT_OF_OPPRESSION)
        && value > 0) {
        value = 0;
    }
    if (otherHero
        && const_cast<hero*>(otherHero)->IsWieldingArtifact(
            ARTIFACT_SPIRIT_OF_OPPRESSION)
        && value > 0) {
        morale = 0;
    } else {
        morale = value;
    }
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:596
// RETAIL_LOCATED(0x0043e140, 0x8C0)  // anchor-global, dc 0x444a8
void army::DrawToBuffer(int x, int y, int bNumBoxOnly)
{
    // @stub
}

// E:\gamedcs\army.cpp:891
DC_ONLY(0x44d50, 0xC2)
double army::ComputeKarma()
{
    // @stub
}

// E:\gamedcs\army.cpp:917
DC_ONLY(0x44e14, 0xAC)
unsigned char add_item(std::vector<army* array, army* arg)
{
    // @stub
}

// E:\gamedcs\army.cpp:930
DC_ONLY(0x44ec0, 0x4A)
void erase_item(std::vector<army* array, const army* arg)
{
    // @stub
}

// E:\gamedcs\army.cpp:948
// RETAIL_LOCATED(0x0043ea70, 0x1DD)  // anchor-global, dc 0x44f0c
void army::add_aura()
{
    // @stub
}

// E:\gamedcs\army.cpp:988
// RETAIL_LOCATED(0x0043ec50, 0x1B4)  // anchor-global, dc 0x45000
void army::remove_aura()
{
    // @stub
}

// E:\gamedcs\army.cpp:1010
// RETAIL_LOCATED(0x0043ee10, 0x1C2)  // anchor-global, dc 0x450bc
void army::remove_binding()
{
    // @stub
}

// E:\gamedcs\army.cpp:1034
DC_ONLY(0x45164, 0xA0)
unsigned char army::set_inside_area_effect(unsigned char arg)
{
    // @stub
}

// E:\gamedcs\army.cpp:1062
DC_ONLY(0x45204, 0x50)
void army::EndWalk()
{
    // @stub
}

// E:\gamedcs\army.cpp:1087
// RETAIL_LOCATED(0x0043f0b0, 0x206)  // anchor-global, dc 0x45254
void army::Walk(int direction, unsigned char end_walk, unsigned char initial_walk)
{
    // @stub
}

// E:\gamedcs\army.cpp:1171
// RETAIL_LOCATED(0x0043f2c0, 0x63B)  // anchor-bracket, dc 0x453c8
void army::animate_missile(army* armyToAttack)
{
    // @stub
}

// E:\gamedcs\army.cpp:1356
// RETAIL_LOCATED(0x0043f900, 0x7F9)  // dc-bracket forced, dc 0x458a0
void army::range_attack(army* armyToAttack)
{
    // @stub
}

// WITHDRAWN 2026-08-14: the `dc-bracket forced` run 0x440100 /
// 0x440140 / 0x440160 was mapped onto the DC rows range_attack() /
// get_clockwise / get_counter_clockwise purely by ORDER, and all
// three pairings are wrong. Retail's three slots are 62 / 31 / 422 B
// against DC's 336 / 70 / 70 - ratios 0.18, 0.44 and 6.03, every one
// outside the 0.3-2.5 band - and the bodies refute them outright:
//   0x440100 takes TWO fastcall register arguments (`cmp edx, 1` with
//     no prior load) and indexes akCreatureTypeTraits by ecx for the
//     +0x14 / +0x18 name pair, i.e. it is the creature-NAME accessor
//     the HD crossbuild also names army::GetName(count) at this exact
//     rva. `army::range_attack()` is a member with no arguments and
//     cannot use edx.
//   0x440140 is a bare `ret`, so it takes NO stack argument;
//     `get_clockwise(long direction)` would be `ret 4`.
//   0x440160 (422 B) is what the HD crossbuild names range_attack()
//     here, and 422/336 = 1.26 against the DC row - so the whole run
//     is shifted, not merely mislabelled.
// DC's get_clockwise / get_counter_clockwise have no retail slot in
// this bracket at all (0x440160 + 0x1a6 = 0x440306, and the next
// carve row is 0x440310): retail inlined or dropped both.

// E:\gamedcs\army.cpp:1541
// RETAIL_LOCATED(0x00440100, 0x3E)  // anchor-global (HD masked-byte
//     identity + body: akCreatureTypeTraits +0x14/+0x18 name pair,
//     two fastcall register arguments), retail-only slot
const char* army::GetName(long count)
{
    // @stub
}
#endif  // @carcass

// The 31-byte slot between GetName and range_attack(), and the ONE
// body in this TU that answers "whose stack is this right now": the
// same five instructions appear inlined verbatim in get_controller
// (0x442690), is_enemy (0x442880) and ComputeBaseDamage (0x443160),
// all later in the link order, which is the /Ob2 extern-linkage case
// (out-of-line copy emitted unconditionally, inlined at every site).
// Arity refutes the carcass's `get_clockwise(long)` outright - this
// is a bare `ret`. Name is NH3API's army::get_controlling_side, whose
// own spelling of is_enemy (`get_controlling_side() != other->group`)
// is exactly the asymmetric compare retail emits there.
VA(0x00440140, 0x1F)  // anchor-callee + body identity, retail-only slot
int army::get_controlling_side() const
{
    if (hypnotizeFlag)
        return 1 - combatSide;
    return combatSide;
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:1541
// RETAIL_LOCATED(0x00440160, 0x1A6)  // anchor-global (HD masked-byte
//     identity), dc 0x45e70 -- the DC row the carcass had on 0x440100
void army::range_attack()
{
    // @stub
}

// E:\gamedcs\army.cpp:1665
// RETAIL_LOCATED(0x00440310, 0x1EB)  // anchor-global, dc 0x46050
void army::do_multi_head_attack(unsigned attackMask, int* damage, int* killed, long* fire_damage)
{
    // @stub
}

// E:\gamedcs\army.cpp:1717
// RETAIL_LOCATED(0x00440500, 0x4B4)  // anchor-global, dc 0x461a0
unsigned char army::check_special_attack(army* target)
{
    // @stub
}

// E:\gamedcs\army.cpp:1846
// RETAIL_LOCATED(0x004409c0, 0x1F9)  // anchor-global, dc 0x464e0
void army::do_fire_shield(long damage)
{
    // @stub
}

// E:\gamedcs\army.cpp:1896
// RETAIL_LOCATED(0x00440bc0, 0xA41)  // anchor-global, dc 0x46658
void army::do_post_attack(army* target, int iDamage, int iKilled, int total_life)
{
    // @stub
}

// E:\gamedcs\army.cpp:2044
// RETAIL_LOCATED(0x00441610, 0x6A0)  // corroborates, dc 0x46bec
unsigned char army::do_attack(army* armyToAttack, int direction)
{
    // @stub
}

// E:\gamedcs\army.cpp:2217
// RETAIL_LOCATED(0x00441cb0, 0x2BE)  // corroborates, dc 0x46fb0
void army::do_attack(int direction)
{
    // @stub
}

// E:\gamedcs\army.cpp:2358
// RETAIL_LOCATED(0x00441f70, 0x26)  // linkorder, dc 0x47270
unsigned char army::check_obstacle_attacks(unsigned char is_walking)
{
    // @stub
}

// E:\gamedcs\army.cpp:2386
// RETAIL_LOCATED(0x00441fa0, 0x461)  // anchor-global, dc 0x472f4
unsigned char army::WalkTo(int destIndex, unsigned char restore_facing)
{
    // @stub
}

// E:\gamedcs\army.cpp:2528
DC_ONLY(0x475ec, 0xA4)
void army::CheckLuck()
{
    // @stub
}

// E:\gamedcs\army.cpp:2575
// RETAIL_LOCATED(0x00442410, 0x13B)  // anchor-global, dc 0x47690
long army::get_adjusted_attack(const army* enemy, unsigned char ranged_attack)
{
    // @stub
}

// E:\gamedcs\army.cpp:2623
#endif  // @carcass

VA(0x00442550, 0x35)  // linkorder, dc 0x477b8
long army::get_attack_modifier(const army* enemy,
                               unsigned char ranged_attack) const
{
    return get_adjusted_attack(enemy, ranged_attack)
        - akCreatureTypeTraits[creatureType].attackSkill;
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:2633
#endif  // @carcass

VA(0x00442590, 0xC2)  // anchor-global, dc 0x477e8
long army::get_adjusted_defense(const army* enemy,
                                unsigned char frenzy_included)
{
    if (frenzy_included && frenzyRounds)
        return 0;
    long defense = defenseSkill;
    if (enemy) {
        if (enemy->creatureType == ARMY_CREATURE_BEHEMOTH)
            defense = static_cast<long>(defense - defense * 0.4f);
        else if (enemy->creatureType == ARMY_CREATURE_ANCIENT_BEHEMOTH)
            defense = static_cast<long>(defense - defense * 0.8f);
    }
    if (gpCombatManager->field_53a8) {
        int second_hex;
        if (creatureId & 1)
            second_hex = gridIndex + (facing ? 1 : -1);
        else
            second_hex = -1;
        if (gpCombatManager->IsInMoat(gridIndex, 0)
            || gpCombatManager->IsInMoat(second_hex, 0))
            defense -= 3;
    }
    return defense;
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:2670
DC_ONLY(0x478c8, 0x32)
long army::get_defense_modifier()
{
    // @stub
}

// E:\gamedcs\army.cpp:2680
DC_ONLY(0x478fc, 0x8)
double army::get_defense_damage_modifier(unsigned char ranged_attack)
{
    // @stub
}

// E:\gamedcs\army.cpp:2691
DC_ONLY(0x47904, 0x1E)
hero* army::get_controller()
{
    // @stub
}

// E:\gamedcs\army.cpp:2698
DC_ONLY(0x47924, 0x1E)
hero* army::get_owner()
{
    // @stub
}

// E:\gamedcs\army.cpp:2708
DC_ONLY(0x47944, 0xD0)
unsigned char is_natural_enemy(TCreatureType attacker, TCreatureType defender)
{
    // @stub
}

// E:\gamedcs\army.cpp:2740
// Located 2026-08-08 from a call site, not from the roster order: the
// ai_tactical pricer get_curse_value (0x43b370) calls this address with
// `mov ecx, enemy` and NO stack arguments and consumes st(0) as a
// double divisor, which is the no-argument overload's exact shape - the
// five-argument sibling two rows down is `ret 0x10`. The carve row is
// 0x4426f0/139 B, it sits in the DC roster's own order (2708
// is_natural_enemy -> 2740 this -> 2756 the five-argument overload ->
// 2790 can_shoot, all of whose retail slots are consecutive), and the
// HD crossbuild names the same body at its own 0x442410.
#endif  // @carcass

VA(0x004426f0, 0x8B)  // anchor-callee, dc 0x47a14
double army::get_average_damage() const
{
    if (blessRounds)
        return blessAmount + maxDamage;
    if (curseRounds)
        return _cpp_max(minDamage - curseAmount, 1);
    return (maxDamage + minDamage) / 2.0;
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:2756
// The carve slot immediately before is_enemy (0x442880), matching the
// DC roster's immediately-preceding row; ai_tactical's
// AI_get_attack_damage (0x435980) and the attack-hex chooser ctor
// (0x4360c0) both call it with EXACTLY this five-argument shape
// (enemy, ranged, count, limit_damage=1, distance) on a this in ecx.
// RETAIL_LOCATED(0x00442780, 0x100)  // anchor-callee, dc 0x47af8
long army::get_average_damage(const army* enemy, unsigned char ranged_attack, long amount, unsigned char limit_damage, long distance) const
{
    // @stub
}

// E:\gamedcs\army.cpp:2776
// Located by the DC-order slot directly before can_shoot (claimed
// 0x4428f0) and the body: null/self reject, berserk (+0x284) returns
// true for everyone, hypnotize (+0x288) flips the effective side, then
// an effective-side inequality on +0xf4. path.cpp's ValidAttack
// criteria-1 arm calls it on the target cell's army.
#endif  // @carcass

VA(0x00442880, 0x68)  // anchor-callee, dc 0x47bcc
unsigned char army::is_enemy(const army* arg)
{
    if (!arg)
        return 0;
    if (this == arg)
        return 0;
    if (!berserkFlag && !arg->berserkFlag)
        return get_controlling_side() != arg->combatSide;
    return 1;
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:2790
// RETAIL_LOCATED(0x004428f0, 0xF6)  // anchor-global, dc 0x47c04
unsigned char army::can_shoot(const army* excluded) const
{
    // @stub
}

// E:\gamedcs\army.cpp:2804
#endif  // @carcass

VA(0x004429f0, 0x5C)  // anchor-global, dc 0x47c74
unsigned char army::enemy_is_adjacent(const army* excluded)
{
    if (gpCombatManager->enemy_is_adjacent(this, gridIndex, excluded))
        return 1;
    if (creatureId & 1) {
        // The second hex has to be a STATEMENT: folded into the call's
        // argument list it costs 10.6 points (89.40%), and naming only
        // the +-1 delta 6.4 (93.57%) - retail loads both halves before
        // it spills `excluded`, which is what the named local buys.
        int hex = gridIndex + (facing ? 1 : -1);
        return gpCombatManager->enemy_is_adjacent(this, hex, excluded);
    }
    return 0;
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:2820
// RETAIL_LOCATED(0x00442a50, 0x410)  // anchor-global, dc 0x47cf4
double army::get_unit_combat_value(long lowest_attack, long lowest_defense, unsigned char ranged, const army* excluded) const
{
    // @stub
}

// E:\gamedcs\army.cpp:2910
// RETAIL_LOCATED(0x00442e60, 0x169)  // anchor-global, dc 0x48168
long army::get_total_combat_value(long lowest_attack, long lowest_defense) const
{
    // @stub
}

// E:\gamedcs\army.cpp:2928
#endif  // @carcass

VA(0x00442fd0, 0xA9)  // anchor-global, dc 0x482f0
long army::get_loss_combat_value(long lowest_attack, long lowest_defense,
                                 unsigned char ranged, long damage,
                                 unsigned char kills_only) const
{
    double value = get_unit_combat_value(lowest_attack, lowest_defense,
                                         ranged, 0);
    if (Is(23) & 1)
        return static_cast<long>(numTroops * value / 5.0);
    if (kills_only)
        value = 1000.0;
    long lost = 0;
    if (damage % hitPoints + topCreatureDamage >= hitPoints)
        lost = topCreatureDamage;
    return static_cast<long>((lost + damage) * value / hitPoints);
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:2960
#endif  // @carcass

VA(0x00443080, 0x50)  // anchor-global, dc 0x48454
long army::get_total_hit_points(unsigned char simulated) const
{
    long total;
    if (Is(23) & 1)
        total = 1;
    else
        total = hitPoints * numTroops - topCreatureDamage;
    if (simulated)
        total = _cpp_max(total - AI_expected_damage, 0);
    return total;
}

// E:\gamedcs\army.cpp:2982
VA(0x004430d0, 0x56)  // anchor-global, dc 0x484a0
void army::set_AI_expected_damage(long arg)
{
    AI_expected_damage = _cpp_min(arg, get_total_hit_points(0));
}

// E:\gamedcs\army.cpp:2988
VA(0x00443130, 0x25)  // decorated identity + exact field/constant loads
float army::get_fire_shield_strength() const
{
    if (fireShieldRounds)
        return fireShieldStrength;
    if (creatureType == CREATURE_EFREET_SULTAN)
        return DATA_COMPGEN(0x0063b8b4, innateFireShieldStrength, 0.2f);
    return DATA_COMPGEN(0x0063ac64, zeroFireShieldStrength, 0.0f);
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:3002
// RETAIL_LOCATED(0x00443160, 0x1BF)  // anchor-global, dc 0x48524
int army::ComputeBaseDamage(unsigned char simulate_only)
{
    // @stub
}

// E:\gamedcs\army.cpp:3076
// RETAIL_LOCATED(0x00443840, 0x344)  // anchor-global, dc 0x4868c
int army::ComputeAttackerDamageBonuses(int base_damage, unsigned char is_shooting, army* defender, unsigned char simulate_only, long distance)
{
    // @stub
}

// E:\gamedcs\army.cpp:3230
DC_ONLY(0x48c10, 0x50)
int army::ComputeDefenderDamageBonuses(int base_damage)
{
    // @stub
}

// E:\gamedcs\army.cpp:3243
// RETAIL_LOCATED(0x00443b90, 0x1FE)  // anchor-global, dc 0x48c60
double army::ComputeAttackerDamageReduction(const army* defender, unsigned char is_shooting)
{
    // @stub
}

// E:\gamedcs\army.cpp:3319
#endif  // @carcass

VA(0x00443d90, 0x9C)  // anchor-global, dc 0x48fc4
double army::ComputeDefenderDamageReduction(unsigned char is_shooting)
{
    double reduction = 1.0;
    if (is_shooting) {
        if (airShieldRounds)
            reduction = airShieldFactor;
    } else {
        if (shieldRounds)
            reduction = shieldFactor;
    }
    if (disabled_2b0)
        reduction *= 0.5;
    hero* casting_hero = gpCombatManager->heroes[get_controlling_side()];
    if (casting_hero)
        reduction *= casting_hero->GetDefenseFactor();
    return reduction;
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:3356
// RETAIL_LOCATED(0x00443f40, 0x14F)  // anchor-global, dc 0x490f4
long army::adjust_damage(army* enemy, long base_damage, unsigned char bIsShot, unsigned char simulated, long distance, long* fire_damage)
{
    // @stub
}

// E:\gamedcs\army.cpp:3406
DC_ONLY(0x49260, 0x68)
long army::DamageEnemy(army* enemy, int* iDamage, int* iKilled, unsigned char bIsShot)
{
    // @stub
}

// E:\gamedcs\army.cpp:3441
#endif  // @carcass

VA(0x00444090, 0x8F)  // anchor-global, dc 0x492c8
int army::Damage(int damage)
{
    int total = damage + topCreatureDamage;
    int killed = total / hitPoints;
    topCreatureDamage = total % hitPoints;
    if (Is(23) & 1) {
        killed = numTroops;
        topCreatureDamage = 0;
    }
    field_e9 = 1;
    if (killed > 0)
        numTroopsToShowOverride = numTroops;
    if (killed > numTroops)
        killed = numTroops;
    numTroops -= killed;
    if (numTroops <= 0)
        field_ea = 1;
    CancelIndividualSpell(62);
    CancelIndividualSpell(70);
    CancelIndividualSpell(74);
    return killed;
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:3481
DC_ONLY(0x4935c, 0x44)
unsigned long army::Strength()
{
    // @stub
}

// E:\gamedcs\army.cpp:3492
DC_ONLY(0x493a0, 0x2F4)
void army::ProcessDeath(int bFadeElementals)
{
    // @stub
}

// E:\gamedcs\army.cpp:3631
#endif  // @carcass

VA(0x004444d0, 0x3B)  // decorated identity + CancelIndividualSpell edges
void army::CancelSpellType(int iSpellType)
{
    switch (iSpellType) {
    case ARMY_CANCEL_SPELLS_AFTER_ATTACK:
        CancelIndividualSpell(59);
        break;
    case ARMY_CANCEL_SPELLS_AFTER_DAMAGE:
        CancelIndividualSpell(62);
        CancelIndividualSpell(70);
        CancelIndividualSpell(74);
        break;
    }
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:3660
DC_ONLY(0x496dc, 0x6A)
void army::adjust_hitpoints()
{
    // @stub
}

// E:\gamedcs\army.cpp:3675
// RETAIL_LOCATED(0x00444510, 0x3DB)  // anchor-global, dc 0x49748
void army::CancelIndividualSpell(int spell)
{
    // @stub
}

// E:\gamedcs\army.cpp:3802
DC_ONLY(0x499ac, 0x3A)
void army::CancelAllSpells()
{
    // @stub
}

// E:\gamedcs\army.cpp:3816
// RETAIL_LOCATED(0x004448f0, 0xB99)  // anchor-global, dc 0x499e8
void army::SetSpellInfluence(int spell, int power, TSkillMastery mastery, const hero* casting_hero)
{
    // @stub
}

// E:\gamedcs\army.cpp:4129
DC_ONLY(0x4a2e8, 0x5E)
void army::DecrementSpellRounds()
{
    // @stub
}

// E:\gamedcs\army.cpp:4158
// RETAIL_LOCATED(0x00445490, 0x23B)  // anchor-global, dc 0x4a348
void army::get_berserk_targets(std::vector<army* armies)
{
    // @stub
}

// E:\gamedcs\army.cpp:4208
// RETAIL_LOCATED(0x004456d0, 0x164)  // anchor-global, dc 0x4a480
void army::GoBerserk()
{
    // @stub
}

// E:\gamedcs\army.cpp:4249
#endif  // @carcass

VA(0x00445840, 0x66)  // corroborates, dc 0x4a598
long army::get_attack_direction(long our_hex, const army* enemy,
                                long enemy_hex) const
{
    long second_hex = enemy_hex;
    if (enemy->creatureId & 1)
        second_hex = enemy_hex + (enemy->facing ? 1 : -1);
    for (long direction = 0; direction < 8; direction++) {
        if (direction < COMBAT_DIRECTION_COUNT || (creatureId & 1)) {
            long hex = get_adjacent_hex(our_hex, direction);
            if (hex == enemy_hex || hex == second_hex)
                return direction;
        }
    }
    return -1;
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:4273
#endif  // @carcass

VA(0x004458b0, 0x9D)  // corroborates, dc 0x4a610
long army::get_attack_direction(long our_hex, const army* enemy)
{
    // The loop bound has to be tested at the BOTTOM of an unbounded
    // loop: a plain `for (d = 0; d < 8; d++)` costs 4.68 points, all of
    // it block layout - retail emits `jge <exit>; jmp <top>` and puts
    // the `return direction` epilogue AHEAD of `return best`, which is
    // what returning `best` from inside the loop buys. `enemy` is also
    // the LEFT operand of the identity compare (0.26).
    long best = -1;
    long direction = 0;
    for (;;) {
        if (direction < COMBAT_DIRECTION_COUNT || (creatureId & 1)) {
            long hex = get_adjacent_hex(our_hex, direction);
            if (hex >= 0 && hex < COMBAT_GRID_CELLS
                && enemy == gpCombatManager->cells[hex].get_army()) {
                if (direction >= COMBAT_DIRECTION_COUNT)
                    return direction;
                if ((facing == 0) == (direction >= 3))
                    return direction;
                if (best == -1)
                    best = direction;
            }
        }
        direction++;
        if (direction >= 8)
            return best;
    }
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:4303
// RETAIL_LOCATED(0x00445950, 0x107)  // anchor-global, dc 0x4a6a4
unsigned char army::simple_move(int hex, unsigned char restore_facing)
{
    // @stub
}

// E:\gamedcs\army.cpp:4356
// RETAIL_LOCATED(0x00445a60, 0x26D)  // anchor-global, dc 0x4a7ac
unsigned char army::attack_hex(int hex, unsigned char restore_facing)
{
    // @stub
}

// E:\gamedcs\army.cpp:4427
// The old link-order join placed move_to at 0x445cd0; decorated-symbol and
// call-edge evidence instead prove its retail body at 0x445d10 below.
unsigned char army::move_to(int hex, unsigned char restore_facing)
{
    // @stub
}

// E:\gamedcs\army.cpp:4436
DC_ONLY(0x4a8c8, 0xB2)
TWallTargetId choose_wall_target(TWallTargetId wall, const TWallTargetId* targets, long count)
{
    // @stub
}

#endif  // @carcass

// E:\gamedcs\army.cpp:4427
VA(0x00445d10, 0x14)  // exact x86/DC decorated identity + simple_move edge
unsigned char army::move_to(int hex, unsigned char restore_facing)
{
    return simple_move(hex, restore_facing);
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:4471
// RETAIL_LOCATED(0x00445d30, 0x189)  // anchor-global, dc 0x4a97c
void army::AttackWall(int iTargetGridIndex)
{
    // @stub
}

// E:\gamedcs\army.cpp:4526
// RETAIL_LOCATED(0x00445ec0, 0x10C)  // dc-callgraph unique, dc 0x4aa3c
void army::attack_wall(TWallTargetId wall, const type_ballistics_traits* ballistics)
{
    // @stub
}

// E:\gamedcs\army.cpp:4577
DC_ONLY(0x4aacc, 0x5A4)
void army::attack_wall(TWallTargetId wall, long levelsDestroyed)
{
    // @stub
}

// E:\gamedcs\army.cpp:4739
DC_ONLY(0x4b070, 0xDA)
void army::Cure(int level, int iSpellPower, const hero* casting_hero)
{
    // @stub
}

// E:\gamedcs\army.cpp:4773
DC_ONLY(0x4b14c, 0x24)
int army::MidY()
{
    // @stub
}

// E:\gamedcs\army.cpp:4779
DC_ONLY(0x4b170, 0x20)
int army::TopY()
{
    // @stub
}

// E:\gamedcs\army.cpp:4784
DC_ONLY(0x4b190, 0x16)
int army::BottomY()
{
    // @stub
}

// E:\gamedcs\army.cpp:4790
DC_ONLY(0x4b1a8, 0x64)
int army::MidX()
{
    // @stub
}

// E:\gamedcs\army.cpp:4800
DC_ONLY(0x4b20c, 0x6C)
int army::RightX()
{
    // @stub
}

// E:\gamedcs\army.cpp:4812
DC_ONLY(0x4b278, 0x6C)
int army::LeftX()
{
    // @stub
}

// E:\gamedcs\army.cpp:4825
DC_ONLY(0x4b2e4, 0x6E)
int army::FrontX()
{
    // @stub
}

// E:\gamedcs\army.cpp:4839
#endif  // @carcass

// The 30-byte slot immediately before is_adjacent (0x4466c0), the same
// neighbour the DC roster has, and the body is the two-hex second cell
// verbatim: bit 0 of creatureId gates it, then gridIndex plus
// (facing ? 1 : -1). ai_tactical's find_attack_hex (0x436840) calls it
// as a no-argument thiscall on the enemy stack.
VA(0x004466a0, 0x1E)  // anchor-callee, dc 0x4b354
int army::get_second_grid_index() const
{
    if (!(creatureId & 1))
        return gridIndex;
    return gridIndex + (facing ? 1 : -1);
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:4850
DC_ONLY(0x4b398, 0x4E)
unsigned char army::is_adjacent(int arg)
{
    // @stub
}

// E:\gamedcs\army.cpp:4864
DC_ONLY(0x4b3e8, 0x3E)
unsigned char army::is_adjacent(const army* other_army)
{
    // @stub
}

// E:\gamedcs\army.cpp:4881
DC_ONLY(0x4b428, 0x2A)
int army::OtherArmyAdjacent(int OAgroup, int OAindex)
{
    // @stub
}

// E:\gamedcs\army.cpp:4891
// RETAIL_LOCATED(0x00446720, 0x107)  // anchor-global, dc 0x4b454
void army::Turn(unsigned char play_animation)
{
    // @stub
}

// E:\gamedcs\army.cpp:4956
// RETAIL_LOCATED(0x00446830, 0x103)  // anchor-global, dc 0x4b558
void army::SetupAnimation()
{
    // @stub
}

// E:\gamedcs\army.cpp:4995
// RETAIL_LOCATED(0x00446940, 0x2FE)  // anchor-bracket, dc 0x4b624
void army::PlayAnimation(int sequence, int nframes, int start_frame)
{
    // @stub
}

// E:\gamedcs\army.cpp:5096
// RETAIL_LOCATED(0x00446c40, 0x1E1)  // anchor-global, dc 0x4b8c4
int army::CanFit(int destIndex, int bAllowShifting, int* iNewDestIndex)
{
    // @stub
}

// E:\gamedcs\army.cpp:5177
// RETAIL_LOCATED(0x00446e30, 0x2E1)  // linkorder, dc 0x4ba88
void army::new_turn()
{
    // @stub
}

// E:\gamedcs\army.cpp:5238
// RETAIL_LOCATED(0x00447120, 0x20A)  // linkorder, dc 0x4bc84
void army::ResetRound()
{
    // @stub
}

// E:\gamedcs\army.cpp:5300
#endif  // @carcass

VA(0x00447330, 0x9C)  // anchor-global, dc 0x4bd80
long army::get_resurrection_size(const army* target)
{
    if (creatureType == CREATURE_ARCHANGEL) {
        int missing = target->origNumTroops - target->numTroops;
        int raised = numTroops * 100 / target->hitPoints;
        return _cpp_min(raised, missing);
    }
    int total_life = target->hitPoints * target->origNumTroops;
    int raised = _cpp_min(total_life, numTroops * 50)
        / akCreatureTypeTraits[ARMY_CREATURE_DEMON].hitPoints;
    return _cpp_min(raised, target->origNumTroops);
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:5324
// RETAIL_LOCATED(0x004473d0, 0x13D)  // anchor-bracket, dc 0x4be64
unsigned char army::can_cast_resurrect(long hex)
{
    // @stub
}

// E:\gamedcs\army.cpp:5359
// RETAIL_LOCATED(0x004476c0, 0x3BA)  // anchor-global, dc 0x4beec
unsigned char army::can_cast_spell(long hex)
{
    // @stub
}

// E:\gamedcs\army.cpp:5396
DC_ONLY(0x4c004, 0x80)
void army::cast_resurrect(long hex)
{
    // @stub
}

// E:\gamedcs\army.cpp:5419
DC_ONLY(0x4c084, 0x6C)
void army::cast_demonic_resurrect(long hex)
{
    // @stub
}

// E:\gamedcs\army.cpp:5433
DC_ONLY(0x4c0f0, 0x64)
unsigned char group_has_melee(long group)
{
    // @stub
}

// E:\gamedcs\army.cpp:5451
DC_ONLY(0x4c154, 0x64)
unsigned char group_has_shooters(long group)
{
    // @stub
}

// E:\gamedcs\army.cpp:5469
DC_ONLY(0x4c1b8, 0x56)
unsigned char group_has_dragons(long group)
{
    // @stub
}

// E:\gamedcs\army.cpp:5488
// RETAIL_LOCATED(0x00447a80, 0x429)  // dc-callgraph unique, dc 0x4c210
unsigned char is_valid_caliph_spell(SpellID spell, const army* target)
{
    // @stub
}

// E:\gamedcs\army.cpp:5546
// RETAIL_LOCATED(0x00447eb0, 0x21)  // anchor-global, dc 0x4c374
long army::get_valid_caliph_spells(const army* target)
{
    // @stub
}

// E:\gamedcs\army.cpp:5564
// RETAIL_LOCATED(0x00447ee0, 0xF8)  // dc-callgraph unique, dc 0x4c3ac
void army::cast_caliph_spell(long hex)
{
    // @stub
}

// E:\gamedcs\army.cpp:5601
// RETAIL_LOCATED(0x00448260, 0x582)  // anchor-global, dc 0x4c468
void army::cast_spell(long hex)
{
    // @stub
}

#endif  // @carcass

// Complete-only helper: retail first takes the active Magic Mirror backlash
// percentage, then floors Faerie Dragons at the spell's base mastery value.
// NH3API supplies the name only after the retail body/address are fixed by
// this army.obj bracket and the unique whole-function identity.
VA(0x004487f0, 0x43)  // retail-only SoD helper; body-identity mapped
int army::get_mirror_effect() const
{
    int effect = 0;
    if (magicMirrorRounds > 0)
        effect = backlashChance;
    if (creatureType == CREATURE_FAERIE_DRAGON) {
        const SSpellTraits* mirrorTraits =
            &akSpellTraits[SPELL_MAGIC_MIRROR];
        int current = effect;
        int innate = mirrorTraits->mastery_bonus[0];
        const int& selected = current < innate ? innate : current;
        return selected;
    }
    return effect;
}

#if 0  // @carcass

// E:\gamedcs\army.cpp:5717
DC_ONLY(0x4c778, 0xB4)
void army::consider_attack(const army* enemy, long value, long attack_distance)
{
    // @stub
}

// E:\gamedcs\army.cpp:5757
// RETAIL_LOCATED(0x00448ab0, 0x114)  // anchor-global, dc 0x4c82c
long army::get_multi_head_directions(long our_hex, const army* enemy, long enemy_hex) const
{
    // @stub
}

// E:\gamedcs\army.cpp:5779
// RETAIL_LOCATED(0x00448bd0, 0xF6)  // anchor-bracket, dc 0x4c898
long army::get_AI_target_time(long speed) const
{
    // @stub
}

// E:\gamedcs\army.cpp:5790
#endif  // @carcass

VA(0x00448cd0, 0x4B)  // anchor-global, dc 0x4c918
int army::GetSpeed() const
{
    int speed = field_c4;
    if (slowRounds) {
        if (Is(6) & 1)
            return 0;
        speed = static_cast<long>(speed * slowFactor);
        if (speed <= 0)
            speed = 1;
    }
    return speed;
}

#if 0  // @carcass

// E:\gamedcs\struct.h:315
DC_ONLY(0x4c968, 0x2C)
void SLimitData::Include(const SLimitData* include_limits)
{
    // @stub
}

// E:\gamedcs\struct.h:438
DC_ONLY(0x4c994, 0x2C)
unsigned long GameTime::NextFrameTime(unsigned long this_frame, long interval)
{
    // @stub
}

// E:\gamedcs\includes.h:117
DC_ONLY(0x4c9c0, 0x2C)
double min(double a, double b)
{
    // @stub
}

// E:\gamedcs\Army.h:760
DC_ONLY(0x4c9ec, 0x20)
unsigned char army::NeedToTurn(int direction)
{
    // @stub
}

// E:\gamedcs\Army.h:810
DC_ONLY(0x4ca0c, 0x20)
const char* army::GetName()
{
    // @stub
}

// E:\gamedcs\Army.h:815
DC_ONLY(0x4ca2c, 0x18)
const char* army::GetName(int count)
{
    // @stub
}

// E:\gamedcs\Army.h:869
DC_ONLY(0x4ca44, 0x1C)
long army::get_attack_direction(const army* enemy)
{
    // @stub
}

// E:\gamedcs\Army.h:875
DC_ONLY(0x4ca60, 0x1C)
unsigned char army::LeavesNoBody()
{
    // @stub
}

// E:\gamedcs\Bitmap16.h:156
DC_ONLY(0x4ca7c, 0x10)
const unsigned short* Bitmap16Bit::GetMap(int x, int y)
{
    // @stub
}

// E:\gamedcs\Bitmap16.h:162
DC_ONLY(0x4ca8c, 0x90)
void Bitmap16Bit::Draw(int sx, int sy, int sw, int sh, Bitmap16Bit* dst, int dx, int dy, unsigned char alpha)
{
    // @stub
}

// E:\gamedcs\Bitmap16.h:168
DC_ONLY(0x4cb1c, 0x74)
void Bitmap16Bit::Grab(const Bitmap16Bit* src, int sx, int sy)
{
    // @stub
}

// E:\gamedcs\CSpriteFrame.h:87
DC_ONLY(0x4cb90, 0x4)
int CSpriteFrame::GetCroppedWidth()
{
    // @stub
}

// E:\gamedcs\CSpriteFrame.h:89
DC_ONLY(0x4cb94, 0x4)
int CSpriteFrame::GetCroppedX()
{
    // @stub
}

// E:\gamedcs\CSpriteFrame.h:90
DC_ONLY(0x4cb98, 0x4)
int CSpriteFrame::GetCroppedY()
{
    // @stub
}

// E:\gamedcs\CSprite.h:148
DC_ONLY(0x4cb9c, 0x44)
int CSprite::GetCroppedX(int seq, int frame)
{
    // @stub
}

// E:\gamedcs\CSprite.h:149
DC_ONLY(0x4cbe0, 0x44)
int CSprite::GetCroppedY(int seq, int frame)
{
    // @stub
}

// E:\gamedcs\CSprite.h:150
DC_ONLY(0x4cc24, 0x44)
int CSprite::GetCroppedWidth(int seq, int frame)
{
    // @stub
}

// E:\gamedcs\HexCell.h:90
DC_ONLY(0x4cc68, 0xA)
unsigned char hexcell::HasArmy()
{
    // @stub
}

// E:\gamedcs\CmbtMgr.h:1555
DC_ONLY(0x4cc74, 0x18)
void combatManager::MarkCreatureEffect(int group, int index)
{
    // @stub
}

// E:\gamedcs\TownMgr.h:745
DC_ONLY(0x4cc8c, 0x10)
TTerrainType townManager::GetNativeTerrain(int type)
{
    // @stub
}

// ..\stlport\stl_deque.h:568
DC_ONLY(0x4cc9c, 0x20)
std::_Deque_iterator<enum std::deque<enum SpellID,std::allocator<enum SpellID>,0>::begin(__$ReturnUdt)
{
    // @stub
}

// ..\stlport\stl_deque.h:569
DC_ONLY(0x4ccbc, 0x20)
std::_Deque_iterator<enum std::deque<enum SpellID,std::allocator<enum SpellID>,0>::end(__$ReturnUdt)
{
    // @stub
}

// ..\stlport\stl_deque.h:615
DC_ONLY(0x4ccdc, 0x1C)
void std::deque<enum SpellID,std::allocator<enum SpellID>,0>::deque<enum SpellID,std::allocator<enum SpellID>,0>(const std::allocator<enum* __a)
{
    // @stub
}

// ..\stlport\stl_deque.h:765
DC_ONLY(0x4ccf8, 0x3C)
void std::deque<enum SpellID,std::allocator<enum SpellID>,0>::push_back(const SpellID* __t)
{
    // @stub
}

// ..\stlport\stl_deque.h:896
DC_ONLY(0x4cd34, 0x104)
std::_Deque_iterator<enum std::deque<enum SpellID,std::allocator<enum SpellID>,0>::erase(__$ReturnUdt, std::_Deque_iterator<enum __pos)
{
    // @stub
}

// ..\stlport\stl_alloc.h:527
DC_ONLY(0x4ce38, 0x4)
void std::allocator<enum SpellID>::allocator<enum SpellID>()
{
    // @stub
}

// ..\stlport\stl_vector.h:480
DC_ONLY(0x4ce3c, 0x4C)
army** std::vector<army *,std::allocator<army *> >::erase(army** __position)
{
    // @stub
}

// ..\stlport\stl_vector.h:506
DC_ONLY(0x4ce88, 0x38)
void std::vector<army *,std::allocator<army *> >::clear()
{
    // @stub
}

// ..\stlport\stl_deque.h:806
DC_ONLY(0x4cec0, 0x34)
void std::deque<enum SpellID,std::allocator<enum SpellID>,0>::pop_back()
{
    // @stub
}

// ..\stlport\stl_deque.h:816
DC_ONLY(0x4cef4, 0x38)
void std::deque<enum SpellID,std::allocator<enum SpellID>,0>::pop_front()
{
    // @stub
}

// ..\stlport\stl_deque.h:301
DC_ONLY(0x4cf2c, 0x3C)
std::_Deque_iterator<enum std::_Deque_iterator<enum SpellID,std::_Nonconst_traits<enum SpellID>,std::_Buf_size_traits<enum SpellID,0> >::operator+(__$ReturnUdt, int __n)
{
    // @stub
}

// ..\stlport\stl_vector.h:490
DC_ONLY(0x4cf68, 0x3C)
army** std::vector<army *,std::allocator<army *> >::erase(army** __first, army** __last)
{
    // @stub
}

// ..\stlport\stl_deque.h:299
DC_ONLY(0x4cfa4, 0x1C)
std::_Deque_iterator<enum* std::_Deque_iterator<enum SpellID,std::_Nonconst_traits<enum SpellID>,std::_Buf_size_traits<enum SpellID,0> >::operator+=(int __n)
{
    // @stub
}

// ..\stlport\stl_deque.h:218
DC_ONLY(0x4cfc0, 0x84)
void std::_Deque_iterator_base<enum SpellID,std::_Buf_size_traits<enum SpellID,0> >::_M_advance(int __n)
{
    // @stub
}

// E:\gamedcs\DC_precompiledheaders.h:41
DC_ONLY(0x4d044, 0x38)
const double* _cpp_min(const double* _X, const double* _Y)
{
    // @stub
}

// ..\stlport\stl_deque.c:318
DC_ONLY(0x4d07c, 0x84)
void std::deque<enum SpellID,std::allocator<enum SpellID>,0>::clear()
{
    // @stub
}

// ..\stlport\stl_deque.c:364
DC_ONLY(0x4d100, 0x54)
void std::deque<enum SpellID,std::allocator<enum SpellID>,0>::_M_push_back_aux(const SpellID* __t)
{
    // @stub
}

// ..\stlport\stl_deque.c:430
DC_ONLY(0x4d154, 0x40)
void std::deque<enum SpellID,std::allocator<enum SpellID>,0>::_M_pop_back_aux()
{
    // @stub
}

// ..\stlport\stl_deque.c:444
DC_ONLY(0x4d194, 0x40)
void std::deque<enum SpellID,std::allocator<enum SpellID>,0>::_M_pop_front_aux()
{
    // @stub
}

// ..\stlport\stl_algo.h:102
DC_ONLY(0x4d1d4, 0x1C)
army** std::find(army** __first, army** __last, army** __val)
{
    // @stub
}

// ..\stlport\stl_algo.h:102
DC_ONLY(0x4d1f0, 0x6C)
std::_Deque_iterator<enum std::find(__$ReturnUdt, std::_Deque_iterator<enum __first, std::_Deque_iterator<enum __last, const SpellID* __val)
{
    // @stub
}

// ..\stlport\stl_algobase.h:137
DC_ONLY(0x4d25c, 0xE)
const float* std::max(const float* __a, const float* __b)
{
    // @stub
}

// ..\stlport\stl_algobase.h:442
DC_ONLY(0x4d26c, 0x98)
std::_Deque_iterator<enum std::copy_backward(__$ReturnUdt, std::_Deque_iterator<enum __first, std::_Deque_iterator<enum __last, std::_Deque_iterator<enum __result)
{
    // @stub
}

// ..\stlport\stl_algobase.h:322
DC_ONLY(0x4d304, 0x98)
std::_Deque_iterator<enum std::copy(__$ReturnUdt, std::_Deque_iterator<enum __first, std::_Deque_iterator<enum __last, std::_Deque_iterator<enum __result)
{
    // @stub
}

// ..\stlport\stl_algobase.h:322
DC_ONLY(0x4d39c, 0x50)
army** std::copy(army** __first, army** __last, army** __result)
{
    // @stub
}

// ..\stlport\stl_construct.h:128
DC_ONLY(0x4d3ec, 0x30)
void std::destroy(SpellID* __first, SpellID* __last)
{
    // @stub
}

// ..\stlport\stl_deque.h:1145
DC_ONLY(0x4d41c, 0x30)
void std::deque<enum SpellID,std::allocator<enum SpellID>,0>::_M_reserve_map_at_back(unsigned __nodes_to_add)
{
    // @stub
}

// ..\stlport\stl_deque.c:731
DC_ONLY(0x4d44c, 0x110)
void std::deque<enum SpellID,std::allocator<enum SpellID>,0>::_M_reallocate_map(unsigned __nodes_to_add, unsigned char __add_at_front)
{
    // @stub
}

// ..\stlport\stl_algo.h:66
DC_ONLY(0x4d55c, 0x16)
army** std::find(army** __first, army** __last, army** __val, std::input_iterator_tag __formal)
{
    // @stub
}

// ..\stlport\stl_algo.h:66
DC_ONLY(0x4d574, 0x60)
std::_Deque_iterator<enum std::find(__$ReturnUdt, std::_Deque_iterator<enum __first, std::_Deque_iterator<enum __last, const SpellID* __val, std::input_iterator_tag __formal)
{
    // @stub
}

// ..\stlport\stl_deque.h:419
DC_ONLY(0x4d5d4, 0xC)
std::random_access_iterator_tag std::iterator_category(__$ReturnUdt, const std::_Deque_iterator<enum* __formal)
{
    // @stub
}

// ..\stlport\stl_deque.h:425
DC_ONLY(0x4d5e0, 0x4)
int* std::distance_type(const std::_Deque_iterator<enum* __formal)
{
    // @stub
}

// ..\stlport\stl_algobase.h:382
DC_ONLY(0x4d5e4, 0x78)
std::_Deque_iterator<enum std::__copy_backward(__$ReturnUdt, std::_Deque_iterator<enum __first, std::_Deque_iterator<enum __last, std::_Deque_iterator<enum __result, std::random_access_iterator_tag __formal, int* __formal)
{
    // @stub
}

// ..\stlport\stl_algobase.h:209
DC_ONLY(0x4d65c, 0x78)
std::_Deque_iterator<enum std::__copy(__$ReturnUdt, std::_Deque_iterator<enum __first, std::_Deque_iterator<enum __last, std::_Deque_iterator<enum __result, std::random_access_iterator_tag __formal, int* __formal)
{
    // @stub
}

// ..\stlport\stl_algobase.h:209
DC_ONLY(0x4d6d4, 0x1E)
army** std::__copy(army** __first, army** __last, army** __result, std::random_access_iterator_tag __formal, int* __formal)
{
    // @stub
}

// ..\stlport\stl_iterator_base.h:262
DC_ONLY(0x4d6f4, 0x4)
SpellID* std::value_type(const SpellID* __formal)
{
    // @stub
}

// ..\stlport\stl_construct.h:121
DC_ONLY(0x4d6f8, 0x1C)
void std::__destroy(SpellID* __first, SpellID* __last, SpellID* __formal)
{
    // @stub
}

// ..\stlport\stl_deque.h:292
DC_ONLY(0x4d714, 0x1C)
std::_Deque_iterator<enum* std::_Deque_iterator<enum SpellID,std::_Nonconst_traits<enum SpellID>,std::_Buf_size_traits<enum SpellID,0> >::operator--()
{
    // @stub
}

// ..\stlport\stl_deque.h:208
DC_ONLY(0x4d730, 0x30)
void std::_Deque_iterator_base<enum SpellID,std::_Buf_size_traits<enum SpellID,0> >::_M_decrement()
{
    // @stub
}

// ..\stlport\stl_algobase.h:322
DC_ONLY(0x4d760, 0x50)
SpellID** std::copy(SpellID** __first, SpellID** __last, SpellID** __result)
{
    // @stub
}

// ..\stlport\stl_algobase.h:442
DC_ONLY(0x4d7b0, 0x50)
SpellID** std::copy_backward(SpellID** __first, SpellID** __last, SpellID** __result)
{
    // @stub
}

// ..\stlport\stl_construct.h:110
DC_ONLY(0x4d800, 0x30)
void std::__destroy_aux(SpellID* __first, SpellID* __last, __false_type __formal)
{
    // @stub
}

// ..\stlport\stl_iterator_base.h:243
DC_ONLY(0x4d830, 0xC)
std::random_access_iterator_tag std::iterator_category(__$ReturnUdt, SpellID** __formal)
{
    // @stub
}

// ..\stlport\stl_iterator_base.h:291
DC_ONLY(0x4d83c, 0x4)
int* std::distance_type(SpellID** __formal)
{
    // @stub
}

// ..\stlport\stl_algobase.h:209
DC_ONLY(0x4d840, 0x1E)
SpellID** std::__copy(SpellID** __first, SpellID** __last, SpellID** __result, std::random_access_iterator_tag __formal, int* __formal)
{
    // @stub
}

// ..\stlport\stl_algobase.h:382
DC_ONLY(0x4d860, 0x22)
SpellID** std::__copy_backward(SpellID** __first, SpellID** __last, SpellID** __result, std::random_access_iterator_tag __formal, int* __formal)
{
    // @stub
}

#endif  // @carcass
