// campaignwindow.cpp - E:\gamedcs\campaignwindow.cpp (compiland campaignwindow.obj)
// HAND-OWNED after admission - INITIALLY GENERATED by `python3 -m homm3.carve carcass`; prototypes are Dreamcast CodeView evidence.
// 6 functions in link order; 20 compiler-generated $-thunks omitted.
#include <va.h>
#include <string.h>
#include "binkmanager.h"
#include "campaignwindow.h"
#include "game.h"
#include "message.h"
#include "soundmgr.h"
#include "widget.h"
#include "winmgr.h"

// Source-private in the Dreamcast compiland. Retail's constructor stores the
// active dialog here and its destructor clears it before destroying the base.
DATA(0x00694e2c) static TCampaignWindow* gpCampaignWindow;

// Complete-only campaign-preview table at retail 0x66c498. Each 0x50-byte
// row has eight descriptor dwords followed by a 12-dword snapshot of the
// consecutive Bink state beginning at gBinkVideo. The constructor/helper own
// the initialized rows; this TU view intentionally makes no DATA claim yet.

// E:\gamedcs\campaignwindow.cpp:78
//
// Dreamcast emits it out of line (dc 0x5b53c, 0x34 B); retail has no slot for
// it, because /Ob2 expands it at all three call sites. The expansion is
// register-visible and is what the handler's EBX is: the inlined `this` is
// loaded once from gpCampaignWindow ahead of the sweep and reused by every
// GetWidget in it, where a direct global load would be reloaded per call.
// Spelled `inline` so no out-of-line copy is emitted here either.
inline void TCampaignWindow::HideText()
{
    for (int line = PREVIEW_FIRST_ID; line <= PREVIEW_LAST_ID; ++line) {
        widget* text = GetWidget(line);
        if (text)
            text->send_message(widget::WIDGET_CLEAR_STATUS,
                widget::WIDGET_ACTIVE | widget::WIDGET_DRAWN);
    }
}

// E:\gamedcs\campaignwindow.cpp:86
//
// DECODE MAP (read off retail 0x45ea40; the whole body is resolved - what is
// missing is MODELLING, not reading, and the four items it needs are listed
// at the end). `ret 8` against two parameters: +8 `unsigned char newGame`,
// +0xc `int newCampaign`, both slots reused as temps once dead. EH frame with
// twelve unwind states, `sub esp, 0x8c`.
//
//   base          heroWindow(0, 0, 0x320, 0x258, 0) - the full 800x600
//                 screen - then vtable 0x63bca4, gpCampaignWindow = this,
//                 this+0x4c = 0 and this+0x50 = -1.
//   newGame arm   `gpGame->campaign = SCampaign();`. A default-constructed
//                 temporary is built at [ebp-0x98], assigned into
//                 gpGame->campaign (+0x1f458) and destroyed; BOTH the
//                 assignment and the destruction are inlined member by
//                 member, which is what makes this the most informative
//                 40 bytes in the function:
//                   +0x00/+0x01/+0x02 bytes, +0x04/+0x08 dwords,
//                   +0x0c byte, +0x10 dword - copied straight;
//                   +0x14 `assign(that, 0, npos)` through 0x404860 with the
//                     npos word at 0x63a60c, i.e. +0x14 is a std::string.
//                     CORRECTION for game.h: SCampaign models that slot as
//                     `char campaignFilename[0x10]`. The width is right and
//                     the type is not - the teardown confirms it by calling
//                     basic_string::_Tidy(true) on temp+0x14. Left alone
//                     here because game.h is shared and nothing compiled
//                     needs the member yet.
//                   +0x24 twenty-one bytes copied by an inlined byte loop -
//                     campaignCompleted[21], already named;
//                   +0x3c, +0x4c, +0x5c, +0x6c: four sub-object
//                     assignments (0x45f5e0, 0x45f810, 0x45f9e0, 0x50ac00).
//                     So game.h's pad_3c[0x20] hides TWO assignable members
//                     (+0x3c, +0x4c), mapScores is the +0x5c one, and
//                     pad_6c[0x10] is a fourth - a vector, since the
//                     teardown destroys [temp+0x70, temp+0x74) and frees
//                     temp+0x70 before zeroing all three words.
//                   the destructor order is the mirror: ~vector(+0x6c),
//                     0x46a650(+0x5c), 0x45f7b0(+0x4c), 0x45f560(+0x3c),
//                     ~string(+0x14).
//   availability  this+0x60..0x74 is a 21-byte block, zeroed as five dwords
//                 plus a byte, then filled by a three-way switch on
//                 newCampaign that also seeds firstCampaign (+0x78):
//                   0  -> +0x78 = 0;  +0x60/+0x62/+0x64 = 1;
//                         completed[0] && [2] && [4] -> +0x61 = +0x65 = 1;
//                         completed[1] && [5]        -> +0x63 = 1;
//                         completed[3]               -> +0x66 = 1.
//                   1  -> +0x78 = 7;  +0x67..+0x6a, +0x6c, +0x6b = 1;
//                         then `for (i = 7; i <= 12; i++)` clears +0x6b and
//                         breaks on the first `!completed[i] && i != 11`.
//                   2  -> +0x78 = 0xd; +0x6d..+0x70 = 1;
//                         completed[13..16] all -> +0x71 = 1;
//                         completed[17]         -> +0x72 = 1;
//                         completed[18]         -> +0x73 = 1;
//                 every gate reads gpGame->campaign.campaignCompleted, whose
//                 element 0 is the 0x1f47c the disassembly shows.
//   widgets       Widgets.reserve(77) - inlined, the 0x134 allocation - then
//                 in order:
//                   bitmapBorder16(0, 0, 0x320, 0x258, 100,
//                       newCampaign == 2 ? "campbkx2.pcx" : "campback.pcx",
//                       0x800);
//                   button(0x292, 0x1e0, 0x84, 0x6a,
//                       DIALOG_RETURN_SPLIT_CANCEL, "cmpscan.def",
//                       0, 1, 0, 0, 2);
//                   `for (i = 0; i < 20; i++) if (available[i]) <0x45e7c0>(i);`
//                       - a thiscall member on this window carrying the
//                       BinkPause import: the per-row preview opener;
//                   the "no scenario" plate, guarded by
//                       (newCampaign == 0 && !this->m66) || newCampaign == 1
//                       || (newCampaign == 2 && !this->m73):
//                       bitmapBorder16(0x181, 0x191, 0xee, 0x8f, 100,
//                           "campnosc.pcx", 0x800);
//                   the forward plate, guarded by !this->m6b && newCampaign
//                       == 1: bitmapBorder16(0x1e, 0x19e, 0xcc, 0x77, 100,
//                           "camp1fwX.pcx", 0x800);
//                   then `last = newCampaign == 0 ? 6 : newCampaign == 1 ?
//                       12 : 19` and one pass per campaign row,
//                       `for (i = firstCampaign; i <= last; i++)`, walking
//                       gCampaignPreviews with the 0x50 stride from base
//                       0x66c49c (note: +4 into the carved 0x66c498 table)
//                       and a SECOND eight-byte-stride table at 0x6a5f88
//                       whose first word is the row's caption:
//                         if (completed[i]) bitmapBorder(row[0] + 6,
//                             row[1] + 0x4a, 0x2a, 0x28,
//                             i - firstCampaign + 0x80, "CampChk.pcx",
//                             0x800);
//                         textWidget(row[2], row[3], row[4], 0x22,
//                             caption[i], "medfont.fnt",
//                             font::HEADING_HIGHLIGHT,
//                             i - firstCampaign + PREVIEW_FIRST_ID,
//                             5, 0, 8);
//                       so the check marks answer 128..134, a range the
//                       header's EOtherWidgetIDs roster does not yet name.
//   tail          the usual AddWidget/MemError sweep over begin()..end(),
//                 then `for (id = 101; id <= 107; id++)` GetWidget(id) and,
//                 when non-null, send_message(6, 6) - HideText, inlined
//                 exactly as the header already records.
//
// Left as a carcass deliberately. Reading it is done; landing it needs four
// modelling decisions that all touch shared headers, and none of them should
// be taken in a lane that is also holding army.h open:
//   1. TCampaignWindow's pad_4c must become +0x4c/+0x50 scalars and a
//      21-byte availability array at +0x60 (firstCampaign at +0x78 is
//      already there).
//   2. gCampaignPreviews needs its real 0x50-byte row type; this body reads
//      five dwords of it, at +0, +4, +8, +0xc and +0x10 of the 0x66c49c
//      view.
//   3. The caption table at 0x6a5f88 needs a name and a claim.
//   4. game.h's SCampaign::campaignFilename must become a std::string, and
//      pad_3c/pad_6c must be split into the three assignable sub-objects the
//      inlined operator= proves.
#if 0  // @carcass
VA(0x0045ea40, 0x692)  // campbkx2.pcx + vtable/global stores; Complete adds newGame, dc 0x5b570
TCampaignWindow::TCampaignWindow(unsigned char newGame, int newCampaign)
{
    // @stub
}
#endif

// Retail emits the compiler-generated wrapper immediately after the
// constructor; Dreamcast appends it to the compiland.
VA_COMPGEN(0x0045f0e0, 0x21, SCALAR_DELETING_DTOR, TCampaignWindow)

// E:\gamedcs\campaignwindow.cpp:261
VA(0x0045f210, 0xAE)  // six preview-state closes + global/widget teardown, dc 0x5bd00
TCampaignWindow::~TCampaignWindow()
{
    // Six Complete campaign previews retain independent copies of the Bink
    // globals. Restore each live copy, close it, then preserve the cleared
    // state back into its row.
    for (int preview = 0; preview < 6; ++preview) {
        int* savedBinkState = gCampaignPreviews + 8 + preview * 20;
        if (*savedBinkState) {
            memcpy(&gBinkVideo, savedBinkState, 12 * sizeof(int));
            CloseBinkVideo();
            memcpy(savedBinkState, &gBinkVideo, 12 * sizeof(int));
        }
    }

    gpCampaignWindow = 0;
    for (widget** it = Widgets.begin(); it != Widgets.end(); ++it) {
        if (*it)
            delete *it;
    }
}

// E:\gamedcs\campaignwindow.cpp:284
VA(0x0045f2c0, 0x2C)  // StartMP3/MainMenu + handler address-take, dc 0x5bd68
void TCampaignWindow::DoModal()
{
    gpSoundManager->StartMP3("MainMenu", 0, 1);
    gpWindowManager->DoDialog(this, CampaignWindowHandler, 0);
}

// File-static hover latch: the handler is its only image-wide reader and
// writer, and it sits in the four bytes between the last gCampaignPreviews
// row and the campaign-filename table.
DATA(0x0066cad8) static int lastCampaignHoverID;

// E:\gamedcs\campaignwindow.cpp:291
//
// Residual (81.6%): D-family block placement only - the shared end-dialog
// join. Retail gives the fall-through into it to the widget arm (`jne
// consume`, then straight into the tail) and sends the campaign-pick and
// key-down arms back with `jmp`s; our CL sinks the same three-predecessor
// join past the key-down arm, costing one `jmp` at the widget arm and
// re-aligning everything downstream. Both layouts spend exactly two
// unconditional jumps, so it is an internal tie-break on IL block creation
// order rather than a spelling - tried and rejected: forward `goto
// pick_campaign` with the arm parked behind the `ret` (VC6 folds the branch
// and hoists the arm back, 75.4), inverted arms `if (id <= LAST) {...} else
// if (...)` (75.4), the three-site inlined-helper spelling that would let
// tail-merge pick the surviving copy (VC6 constant-folds the key-down
// copy's dialogReturn and merges only the epilogue, 80.1), `goto` inside
// the switch case (81.6), explicit `goto end_dialog` in both arms (81.6),
// if/else-if chain (81.6). `if (id == CANCEL) goto end_dialog; goto
// consume;` and plain `return MESSAGE_DISPATCH_CONSUME` both reach 84.5 but
// only by DUPLICATING the consume epilogue, which retail does not have
// (retail's body has exactly two `ret`s) - alignment luck, not a match, so
// both are rejected. Everything else in the body is register-exact.
VA(0x0045f2f0, 0x26C)  // DoModal address-take + Complete video/widget CFG, dc 0x5bd94
int CampaignWindowHandler(message& msg)
{
    if (gBinkDirty) {
        gpCampaignWindow->DrawWindow(0, 0x80, 0x86);
        gpWindowManager->UpdateScreen(gBinkX, gBinkY,
            gBinkUpdateWidth, gBinkUpdateHeight);
    }

    if (msg.id == MESSAGE_WIDGET) {
        if (msg.codeX != widget::WIDGET_DESELECT)
            goto consume;
        {
            int id = msg.codeY;
            if (id < TCampaignWindow::CAMPAIGN_FIRST_ID)
                goto consume;
            if (id > TCampaignWindow::CAMPAIGN_LAST_ID) {
                if (id != DIALOG_RETURN_CANCEL)
                    goto consume;
            } else {
                gpGame->campaign.select_campaign(
                    id - TCampaignWindow::CAMPAIGN_FIRST_ID,
                    gCampaignFileNames[
                        id - TCampaignWindow::CAMPAIGN_FIRST_ID]);
                gBinkPaused = 1;
                _BinkPause(gBinkVideo, 1);
            }
        }
end_dialog:
        msg.id = MESSAGE_WIDGET;
        gpWindowManager->dialogReturn = msg.codeY;
        msg.codeY = widget::WIDGET_END_DIALOG;
        msg.codeX = widget::WIDGET_END_DIALOG;
        return MESSAGE_DISPATCH_FORWARD;
    }

    if (msg.id == MESSAGE_KEY_DOWN) {
        switch (msg.codeX) {
        case TCampaignWindow::DIALOG_CLOSE_KEY:
            msg.codeY = DIALOG_RETURN_CANCEL;
            break;
        default:
            goto consume;
        }
        goto end_dialog;
    }

    if (msg.id != MESSAGE_MOUSE_MOVE)
        goto consume;

    {
        int hoverID = gpCampaignWindow->findWidget(msg.mouseX, msg.mouseY);
        if (hoverID == lastCampaignHoverID)
            goto consume;
        lastCampaignHoverID = hoverID;

        if (hoverID >= TCampaignWindow::CAMPAIGN_FIRST_ID
                && hoverID <= TCampaignWindow::CAMPAIGN_LAST_ID) {
            int* preview = gCampaignPreviews
                + (hoverID - TCampaignWindow::CAMPAIGN_FIRST_ID) * 20;
            gpCampaignWindow->HideText();
            gpCampaignWindow->GetWidget(hoverID
                    - gpCampaignWindow->firstCampaign - 7)->send_message(
                widget::WIDGET_SET_STATUS,
                widget::WIDGET_ACTIVE | widget::WIDGET_DRAWN);
            memcpy(&gBinkVideo, preview + 8, 12 * sizeof(int));
            gBinkPaused = 0;
            _BinkPause(gBinkVideo, 0);
            BinkManager::RestartBink();
        } else {
            gBinkPaused = 1;
            _BinkPause(gBinkVideo, 1);
            gpCampaignWindow->HideText();
        }

        if (hoverID == DIALOG_RETURN_CANCEL)
            gpCampaignWindow->GetWidget(DIALOG_RETURN_CANCEL)->send_message(
                widget::WIDGET_SET_STATUS, widget::WIDGET_HIGHLIGHTED);
        else
            gpCampaignWindow->GetWidget(DIALOG_RETURN_CANCEL)->send_message(
                widget::WIDGET_CLEAR_STATUS, widget::WIDGET_HIGHLIGHTED);
        gpCampaignWindow->DrawWindow(0, 0xffff0001, 0xffff);
        gpWindowManager->UpdateScreen(0, 0, WINDOW_SCREEN_WIDTH,
            WINDOW_SCREEN_HEIGHT);
    }

consume:
    return MESSAGE_DISPATCH_CONSUME;
}

// E:\gamedcs\campaignwindow.cpp:258
#if 0  // @carcass -- represented by VA_COMPGEN above
DC_ONLY(0x5bf44, 0x34)
void* TCampaignWindow::`scalar deleting destructor'(unsigned __flags)
{
    // @stub
}
#endif
