// event_record.cpp - E:\gamedcs\event_record.cpp (compiland event_record.obj)
// HAND-OWNED after admission - INITIALLY GENERATED by `python3 -m homm3.carve carcass`; prototypes are Dreamcast CodeView evidence.
// 213 functions in link order; 20 compiler-generated $-thunks omitted.
#include <va.h>
#include "event_record.h"
#include "game.h"
#include "abstractfile.h"

#if 0  // @carcass

// E:\gamedcs\event_record.cpp:36
DC_ONLY(0x8c624, 0x34)
void type_event_record::type_event_record()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:44
DC_ONLY(0x8c658, 0x20)
void type_event_record::~type_event_record()
{
    // @stub
}

#endif  // @carcass

// E:\gamedcs\event_record.cpp:51
VA(0x0049a5e0, 0x1D)  // anchor-vtable, dc 0x8c678
unsigned char type_event_record::load(TAbstractFile* infile, int version)
{
    return infile->Read(&player_id, 1) == 1;
}

// E:\gamedcs\event_record.cpp:60
VA(0x0049a600, 0x1D)  // anchor-vtable, dc 0x8c698
unsigned char type_event_record::save(TAbstractFile* outfile)
{
    return outfile->Write(&player_id, 1) == 1;
}

#if 0  // @carcass

// E:\gamedcs\event_record.cpp:65
DC_ONLY(0x8c6b8, 0x50)
void set_player(char new_player)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:81
DC_ONLY(0x8c708, 0x4)
void type_event_record::replay()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:88
DC_ONLY(0x8c70c, 0x4)
void type_event_record::undo()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:96
DC_ONLY(0x8c710, 0xAE)
void type_record_move_hero::type_record_move_hero(hero* _hero, char _direction, type_point _destination)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:108
DC_ONLY(0x8c7c0, 0x26)
type_event_record* type_record_move_hero::create()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:116
#endif  // @carcass
VA(0x0049a680, 0x6)  // anchor-vtable, dc 0x8c7e8
type_event_record_type type_record_move_hero::get_type()
{
    return RECORD_MOVE_HERO;
}
#if 0  // @carcass

// E:\gamedcs\event_record.cpp:124
DC_ONLY(0x8c7ec, 0xCE)
unsigned char type_record_move_hero::load(void* infile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:145
DC_ONLY(0x8c8bc, 0x60)
unsigned char type_record_move_hero::save(void* outfile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:161
DC_ONLY(0x8c91c, 0xCE)
void type_record_move_hero::replay(unsigned char draw)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:186
DC_ONLY(0x8c9ec, 0x66)
void type_record_move_hero::undo()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:204
DC_ONLY(0x8ca54, 0x70)
void type_record_teleport::type_record_teleport(hero* _hero, type_point _destination)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:211
DC_ONLY(0x8cac4, 0x26)
type_event_record* type_record_teleport::create()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:219
#endif  // @carcass
VA(0x0049a9b0, 0x6)  // anchor-vtable, dc 0x8caec
type_event_record_type type_record_teleport::get_type()
{
    return RECORD_TELEPORT;
}
#if 0  // @carcass

// E:\gamedcs\event_record.cpp:227
DC_ONLY(0x8caf0, 0x3C)
void type_record_teleport::replay(unsigned char draw)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:237
DC_ONLY(0x8cb2c, 0x5C)
void type_record_claim_mine::type_record_claim_mine(long _id, char _owner)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:247
DC_ONLY(0x8cb88, 0x26)
type_event_record* type_record_claim_mine::create()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:255
DC_ONLY(0x8cbb0, 0x4)
type_event_record_type type_record_claim_mine::get_type()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:263
DC_ONLY(0x8cbb4, 0x66)
unsigned char type_record_claim_mine::load(void* infile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:279
DC_ONLY(0x8cc1c, 0x4E)
unsigned char type_record_claim_mine::save(void* outfile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:292
DC_ONLY(0x8cc6c, 0x6C)
void type_record_claim_mine::replay(unsigned char draw)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:312
#endif  // @carcass
VA(0x0049abc0, 0x19)  // anchor-vtable, dc 0x8ccd8
void type_record_claim_mine::undo()
{
    gpGame->mines[id].playerOwner = old_owner;
}
#if 0  // @carcass

// E:\gamedcs\event_record.cpp:321
DC_ONLY(0x8ccfc, 0x60)
void type_record_claim_town::type_record_claim_town(long _id, char _new_owner)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:331
DC_ONLY(0x8cd5c, 0x26)
type_event_record* type_record_claim_town::create()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:339
DC_ONLY(0x8cd84, 0x54)
type_event_record_type type_record_claim_town::get_type()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:347
DC_ONLY(0x8cdd8, 0x70)
void type_record_claim_town::replay(unsigned char draw)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:367
#endif  // @carcass
VA(0x0049aca0, 0x1D)  // anchor-vtable, dc 0x8ce48
void type_record_claim_town::undo()
{
    gpGame->towns[id].owner = old_owner;
}
#if 0  // @carcass

// E:\gamedcs\event_record.cpp:376
DC_ONLY(0x8ce74, 0x3A)
void type_record_hide_boat::type_record_hide_boat(boat* _current_boat)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:384
DC_ONLY(0x8ceb0, 0x26)
type_event_record* type_record_hide_boat::create()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:392
#endif  // @carcass
VA(0x0049acf0, 0x6)  // anchor-vtable, dc 0x8ced8
type_event_record_type type_record_hide_boat::get_type()
{
    return RECORD_HIDE_BOAT;
}
#if 0  // @carcass

// E:\gamedcs\event_record.cpp:400
DC_ONLY(0x8cedc, 0x4E)
unsigned char type_record_hide_boat::load(void* infile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:415
DC_ONLY(0x8cf2c, 0x36)
unsigned char type_record_hide_boat::save(void* outfile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:427
DC_ONLY(0x8cf64, 0x2E)
void type_record_hide_boat::replay(unsigned char draw)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:440
DC_ONLY(0x8cf94, 0x12)
void type_record_hide_boat::undo()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:449
DC_ONLY(0x8cfa8, 0x9A)
void type_record_show_boat::type_record_show_boat(boat* _current_boat, type_point _location)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:458
DC_ONLY(0x8d044, 0x26)
type_event_record* type_record_show_boat::create()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:466
#endif  // @carcass
VA(0x0049af30, 0x6)  // anchor-vtable, dc 0x8d06c
type_event_record_type type_record_show_boat::get_type()
{
    return RECORD_SHOW_BOAT;
}
#if 0  // @carcass

// E:\gamedcs\event_record.cpp:474
DC_ONLY(0x8d070, 0xA0)
unsigned char type_record_show_boat::load(void* infile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:488
DC_ONLY(0x8d110, 0x3A)
unsigned char type_record_show_boat::save(void* outfile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:500
DC_ONLY(0x8d14c, 0x8A)
void type_record_show_boat::replay(unsigned char draw)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:520
DC_ONLY(0x8d1d8, 0x46)
void type_record_show_boat::undo()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:533
DC_ONLY(0x8d220, 0x70)
void type_record_erase::type_record_erase(type_point _location, long _object_id, unsigned long _extra_info, long _object_index)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:544
DC_ONLY(0x8d290, 0x26)
type_event_record* type_record_erase::create()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:552
#endif  // @carcass
VA(0x0049b180, 0x6)  // anchor-vtable, dc 0x8d2b8
type_event_record_type type_record_erase::get_type()
{
    return RECORD_ERASE;
}
#if 0  // @carcass

// E:\gamedcs\event_record.cpp:560
DC_ONLY(0x8d2bc, 0x7A)
unsigned char type_record_erase::load(void* infile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:578
DC_ONLY(0x8d338, 0x90)
unsigned char type_record_erase::save(void* outfile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:592
DC_ONLY(0x8d3c8, 0xA4)
void type_record_erase::replay(unsigned char draw)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:614
DC_ONLY(0x8d46c, 0x42)
void type_record_erase::undo()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:628
DC_ONLY(0x8d4b0, 0x50)
void type_record_hide_hero::type_record_hide_hero(hero* _hero, char _owner)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:638
DC_ONLY(0x8d500, 0x26)
type_event_record* type_record_hide_hero::create()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:646
DC_ONLY(0x8d528, 0x4)
type_event_record_type type_record_hide_hero::get_type()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:654
DC_ONLY(0x8d52c, 0x72)
unsigned char type_record_hide_hero::load(void* infile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:673
DC_ONLY(0x8d5a0, 0x4E)
unsigned char type_record_hide_hero::save(void* outfile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:687
DC_ONLY(0x8d5f0, 0x96)
void type_record_hide_hero::replay(unsigned char draw)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:712
DC_ONLY(0x8d688, 0x80)
void type_record_hide_hero::undo()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:725
DC_ONLY(0x8d708, 0xB6)
void type_record_show_hero::type_record_show_hero(hero* _hero, char _owner, type_point _location, unsigned char _is_boat)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:736
DC_ONLY(0x8d7c0, 0x26)
type_event_record* type_record_show_hero::create()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:744
DC_ONLY(0x8d7e8, 0x4)
type_event_record_type type_record_show_hero::get_type()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:752
DC_ONLY(0x8d7ec, 0x72)
unsigned char type_record_show_hero::load(void* infile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:770
DC_ONLY(0x8d860, 0x52)
unsigned char type_record_show_hero::save(void* outfile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:784
DC_ONLY(0x8d8b4, 0x140)
void type_record_show_hero::replay(unsigned char draw)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:817
DC_ONLY(0x8d9f4, 0x8C)
void type_record_show_hero::undo()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:842
DC_ONLY(0x8da80, 0x40)
void type_record_player_death::type_record_player_death(char _player_id)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:850
DC_ONLY(0x8dac0, 0x26)
type_event_record* type_record_player_death::create()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:858
#endif  // @carcass
VA(0x0049ba30, 0x6)  // anchor-vtable, dc 0x8dae8
type_event_record_type type_record_player_death::get_type()
{
    return RECORD_PLAYER_DEATH;
}

// E:\gamedcs\event_record.cpp:866
VA(0x0049ba40, 0x3D)  // anchor-vtable, dc 0x8daec
unsigned char type_record_player_death::load(TAbstractFile* infile, int version)
{
    if (infile->Read(&player_id, 1) != 1)
        return 0;
    unsigned char ok = infile->Read(&extra, 1) == 1;
    return ok;
}

// E:\gamedcs\event_record.cpp:878
VA(0x0049ba80, 0x30)  // anchor-vtable, dc 0x8db2c
unsigned char type_record_player_death::save(TAbstractFile* outfile)
{
    outfile->Write(&player_id, 1);
    unsigned char ok = outfile->Write(&extra, 1) == 1;
    return ok;
}
#if 0  // @carcass

// E:\gamedcs\event_record.cpp:889
DC_ONLY(0x8db94, 0x8A)
void type_record_player_death::replay(unsigned char draw)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:905
DC_ONLY(0x8dc20, 0x4)
void type_record_player_death::undo()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:912
DC_ONLY(0x8dc24, 0x8C)
void type_record_shroud::type_record_shroud()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:919
DC_ONLY(0x8dcb0, 0x24)
type_event_record* type_record_shroud::create()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:927
#endif  // @carcass
VA(0x0049bc80, 0x6)  // anchor-vtable, dc 0x8dcd4
type_event_record_type type_record_shroud::get_type()
{
    return RECORD_SHROUD;
}
#if 0  // @carcass

// E:\gamedcs\event_record.cpp:935
DC_ONLY(0x8dcd8, 0xB0)
unsigned char type_record_shroud::load(void* infile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:960
DC_ONLY(0x8dd88, 0x62)
unsigned char type_record_shroud::save(void* outfile)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:978
DC_ONLY(0x8ddec, 0x84)
void type_record_shroud::add_change(int x, int y, int z, short old_value, short new_value)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:993
DC_ONLY(0x8de70, 0xF0)
void type_record_shroud::replay(unsigned char draw)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1018
DC_ONLY(0x8df60, 0x7E)
void type_record_shroud::undo()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1034
DC_ONLY(0x8dfe0, 0x78)
void game::record_claim_mine(long id, long new_owner)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1049
DC_ONLY(0x8e058, 0x60)
void game::record_claim_town(long id, long new_owner)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1061
DC_ONLY(0x8e0b8, 0x4E)
void game::record_erase_object(NewmapCell* cell, type_point point)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1071
DC_ONLY(0x8e108, 0x3E)
void game::record_hide_boat(boat* current_boat)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1079
DC_ONLY(0x8e148, 0x44)
void game::record_hide_hero(hero* current_hero, char old_owner)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1087
DC_ONLY(0x8e18c, 0x42)
void game::record_show_boat(boat* current_boat, type_point point)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1096
DC_ONLY(0x8e1d0, 0xA0)
void game::record_show_hero(hero* current_hero, char owner, type_point location, unsigned char is_boat)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1106
DC_ONLY(0x8e270, 0x4A)
void game::record_move(hero* current_hero, int direction, type_point destination)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1115
DC_ONLY(0x8e2bc, 0x3C)
void game::record_player_death(char player_id)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1123
DC_ONLY(0x8e2f8, 0x42)
void game::record_teleport(hero* current_hero, type_point destination)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1136
// RETAIL_LOCATED(0x0049d160, 0x268)  // anchor-global, dc 0x8e33c
void game::SetVisibility(const int startX, const int startY, const int z, const int whichPlayer, int range, unsigned char remote_move)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1189
// RETAIL_LOCATED(0x0049d3d0, 0x260)  // anchor-global, dc 0x8e54c
void game::ResetVisibility(int start_x, int start_y, int z, int whichPlayer, int range)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1239
#endif  // @carcass
VA(0x0049d630, 0x8C)  // linkorder dc-label, dc 0x8e730
void game::clear_event_records()
{
    int i = eventRecords.size();
    while (i-- != 0)
        delete eventRecords[i];
    eventRecords.clear();
}
#if 0  // @carcass

// E:\gamedcs\event_record.cpp:1251
DC_ONLY(0x8e77c, 0xB2)
void game::clear_event_records(char player_id)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1282
DC_ONLY(0x8e830, 0x258)
void game::play_recorded_events()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1367
DC_ONLY(0x8ea88, 0x46)
unsigned char game::replay_available()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:1380
DC_ONLY(0x8ead0, 0xF4)
unsigned char game::load_recorded_events(void* infile)
{
    // @stub
}

// E:\gamedcs\event_record.h:64
DC_ONLY(0x8ec5c, 0x4)
char type_event_record::get_player_id()
{
    // @stub
}

// E:\gamedcs\event_record.h:85
DC_ONLY(0x8ec60, 0x6C)
void type_record_move_hero::type_record_move_hero()
{
    // @stub
}

// E:\gamedcs\event_record.h:85
DC_ONLY(0x8eccc, 0x34)
void* type_record_move_hero::`scalar deleting destructor'(unsigned __flags)
{
    // @stub
}

// E:\gamedcs\event_record.h:85
DC_ONLY(0x8ed00, 0x18)
void type_record_move_hero::~type_record_move_hero()
{
    // @stub
}

// E:\gamedcs\event_record.h:108
DC_ONLY(0x8ed18, 0x3C)
void type_record_teleport::type_record_teleport()
{
    // @stub
}

// E:\gamedcs\event_record.h:108
DC_ONLY(0x8ed54, 0x34)
void* type_record_teleport::`scalar deleting destructor'(unsigned __flags)
{
    // @stub
}

// E:\gamedcs\event_record.h:108
DC_ONLY(0x8ed88, 0x18)
void type_record_teleport::~type_record_teleport()
{
    // @stub
}

// E:\gamedcs\event_record.h:128
DC_ONLY(0x8eda0, 0x3C)
void type_record_claim_mine::type_record_claim_mine()
{
    // @stub
}

// E:\gamedcs\event_record.h:128
DC_ONLY(0x8eddc, 0x34)
void* type_record_claim_mine::`scalar deleting destructor'(unsigned __flags)
{
    // @stub
}

// E:\gamedcs\event_record.h:128
DC_ONLY(0x8ee10, 0x18)
void type_record_claim_mine::~type_record_claim_mine()
{
    // @stub
}

// E:\gamedcs\event_record.h:149
DC_ONLY(0x8ee28, 0x3C)
void type_record_claim_town::type_record_claim_town()
{
    // @stub
}

// E:\gamedcs\event_record.h:149
DC_ONLY(0x8ee64, 0x34)
void* type_record_claim_town::`scalar deleting destructor'(unsigned __flags)
{
    // @stub
}

// E:\gamedcs\event_record.h:149
DC_ONLY(0x8ee98, 0x18)
void type_record_claim_town::~type_record_claim_town()
{
    // @stub
}

// E:\gamedcs\event_record.h:169
DC_ONLY(0x8eeb0, 0x3C)
void type_record_hide_boat::type_record_hide_boat()
{
    // @stub
}

// E:\gamedcs\event_record.h:169
DC_ONLY(0x8eeec, 0x34)
void* type_record_hide_boat::`scalar deleting destructor'(unsigned __flags)
{
    // @stub
}

// E:\gamedcs\event_record.h:169
DC_ONLY(0x8ef20, 0x18)
void type_record_hide_boat::~type_record_hide_boat()
{
    // @stub
}

// E:\gamedcs\event_record.h:190
DC_ONLY(0x8ef38, 0x6C)
void type_record_show_boat::type_record_show_boat()
{
    // @stub
}

// E:\gamedcs\event_record.h:190
DC_ONLY(0x8efa4, 0x34)
void* type_record_show_boat::`scalar deleting destructor'(unsigned __flags)
{
    // @stub
}

// E:\gamedcs\event_record.h:190
DC_ONLY(0x8efd8, 0x18)
void type_record_show_boat::~type_record_show_boat()
{
    // @stub
}

// E:\gamedcs\event_record.h:214
DC_ONLY(0x8eff0, 0x54)
void type_record_erase::type_record_erase()
{
    // @stub
}

// E:\gamedcs\event_record.h:214
DC_ONLY(0x8f044, 0x34)
void* type_record_erase::`scalar deleting destructor'(unsigned __flags)
{
    // @stub
}

// E:\gamedcs\event_record.h:214
DC_ONLY(0x8f078, 0x18)
void type_record_erase::~type_record_erase()
{
    // @stub
}

// E:\gamedcs\event_record.h:238
DC_ONLY(0x8f090, 0x3C)
void type_record_hide_hero::type_record_hide_hero()
{
    // @stub
}

// E:\gamedcs\event_record.h:238
DC_ONLY(0x8f0cc, 0x34)
void* type_record_hide_hero::`scalar deleting destructor'(unsigned __flags)
{
    // @stub
}

// E:\gamedcs\event_record.h:238
DC_ONLY(0x8f100, 0x18)
void type_record_hide_hero::~type_record_hide_hero()
{
    // @stub
}

// E:\gamedcs\event_record.h:262
DC_ONLY(0x8f118, 0x6C)
void type_record_show_hero::type_record_show_hero()
{
    // @stub
}

// E:\gamedcs\event_record.h:262
DC_ONLY(0x8f184, 0x34)
void* type_record_show_hero::`scalar deleting destructor'(unsigned __flags)
{
    // @stub
}

// E:\gamedcs\event_record.h:262
DC_ONLY(0x8f1b8, 0x18)
void type_record_show_hero::~type_record_show_hero()
{
    // @stub
}

// E:\gamedcs\event_record.h:286
DC_ONLY(0x8f1d0, 0x3C)
void type_record_player_death::type_record_player_death()
{
    // @stub
}

// E:\gamedcs\event_record.h:286
DC_ONLY(0x8f20c, 0x34)
void* type_record_player_death::`scalar deleting destructor'(unsigned __flags)
{
    // @stub
}

// E:\gamedcs\event_record.h:286
DC_ONLY(0x8f240, 0x18)
void type_record_player_death::~type_record_player_death()
{
    // @stub
}

// E:\gamedcs\event_record.h:319
DC_ONLY(0x8f258, 0x18)
long type_record_shroud::get_change_count()
{
    // @stub
}

// E:\gamedcs\game.h:877
DC_ONLY(0x8f270, 0x58)
unsigned char game::GetTeamMask(int playerNum)
{
    // @stub
}

// E:\gamedcs\netmsg.h:577
DC_ONLY(0x8f2c8, 0x34)
void CMCClaimMine::CMCClaimMine(signed char mineId, int playerPos)
{
    // @stub
}

// E:\gamedcs\netmsg.h:591
DC_ONLY(0x8f2fc, 0x34)
void CMCClaimTown::CMCClaimTown(signed char townId, int playerPos)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:38
DC_ONLY(0x8f330, 0x34)
void* type_event_record::`scalar deleting destructor'(unsigned __flags)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:913
DC_ONLY(0x8f364, 0x34)
void* type_record_shroud::`scalar deleting destructor'(unsigned __flags)
{
    // @stub
}

// E:\gamedcs\event_record.cpp:913
DC_ONLY(0x8f398, 0x28)
void type_record_shroud::~type_record_shroud()
{
    // @stub
}

// E:\gamedcs\event_record.cpp:953
DC_ONLY(0x8f3c0, 0x28)
void type_record_shroud::type_shroud_change::type_shroud_change()
{
    // @stub
}

// ..\stlport\stl_vector.h:195
DC_ONLY(0x8f3e8, 0xC)
unsigned std::vector<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::size()
{
    // @stub
}

// ..\stlport\stl_vector.h:203
DC_ONLY(0x8f3f4, 0x20)
type_record_shroud::type_shroud_change* std::vector<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::operator[](unsigned __n)
{
    // @stub
}

// ..\stlport\stl_vector.h:218
DC_ONLY(0x8f414, 0x1C)
void std::vector<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::vector<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >(const std::allocator<type_record_shroud::type_shroud_change>* __a)
{
    // @stub
}

// ..\stlport\stl_vector.h:288
DC_ONLY(0x8f430, 0x28)
void std::vector<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::~vector<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >()
{
    // @stub
}

// ..\stlport\stl_vector.h:368
DC_ONLY(0x8f458, 0x3C)
void std::vector<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::push_back(const type_record_shroud::type_shroud_change* __x)
{
    // @stub
}

// ..\stlport\stl_vector.h:506
DC_ONLY(0x8f494, 0x38)
void std::vector<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::clear()
{
    // @stub
}

// ..\stlport\stl_alloc.h:527
DC_ONLY(0x8f4cc, 0x4)
void std::allocator<type_record_shroud::type_shroud_change>::allocator<type_record_shroud::type_shroud_change>()
{
    // @stub
}

// ..\stlport\stl_alloc.h:537
DC_ONLY(0x8f4d0, 0x4)
void std::allocator<type_record_shroud::type_shroud_change>::~allocator<type_record_shroud::type_shroud_change>()
{
    // @stub
}

// ..\stlport\stl_vector.h:179
DC_ONLY(0x8f4d4, 0x4)
type_event_record** std::vector<type_event_record *,std::allocator<type_event_record *> >::begin()
{
    // @stub
}

// ..\stlport\stl_vector.h:195
DC_ONLY(0x8f4d8, 0xC)
unsigned std::vector<type_event_record *,std::allocator<type_event_record *> >::size()
{
    // @stub
}

// ..\stlport\stl_vector.h:203
DC_ONLY(0x8f4e4, 0x20)
type_event_record** std::vector<type_event_record *,std::allocator<type_event_record *> >::operator[](unsigned __n)
{
    // @stub
}

// ..\stlport\stl_vector.h:204
DC_ONLY(0x8f504, 0x20)
type_event_record** std::vector<type_event_record *,std::allocator<type_event_record *> >::operator[](unsigned __n)
{
    // @stub
}

// ..\stlport\stl_vector.h:368
DC_ONLY(0x8f524, 0x3C)
void std::vector<type_event_record *,std::allocator<type_event_record *> >::push_back(type_event_record** __x)
{
    // @stub
}

// ..\stlport\stl_vector.h:490
DC_ONLY(0x8f560, 0x3C)
type_event_record** std::vector<type_event_record *,std::allocator<type_event_record *> >::erase(type_event_record** __first, type_event_record** __last)
{
    // @stub
}

// ..\stlport\stl_vector.h:506
DC_ONLY(0x8f59c, 0x38)
void std::vector<type_event_record *,std::allocator<type_event_record *> >::clear()
{
    // @stub
}

// ..\stlport\stl_vector.h:179
DC_ONLY(0x8f5d4, 0x4)
type_record_shroud::type_shroud_change* std::vector<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::begin()
{
    // @stub
}

// ..\stlport\stl_vector.h:181
DC_ONLY(0x8f5d8, 0x4)
type_record_shroud::type_shroud_change* std::vector<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::end()
{
    // @stub
}

// ..\stlport\stl_vector.h:490
DC_ONLY(0x8f5dc, 0x3C)
type_record_shroud::type_shroud_change* std::vector<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::erase(type_record_shroud::type_shroud_change* __first, type_record_shroud::type_shroud_change* __last)
{
    // @stub
}

// ..\stlport\stl_vector.h:89
DC_ONLY(0x8f618, 0x2C)
void std::_Vector_base<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::_Vector_base<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >(const std::allocator<type_record_shroud::type_shroud_change>* __a)
{
    // @stub
}

// ..\stlport\stl_vector.h:101
DC_ONLY(0x8f644, 0x30)
void std::_Vector_base<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::~_Vector_base<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >()
{
    // @stub
}

// ..\stlport\stl_vector.h:180
DC_ONLY(0x8f674, 0x4)
type_event_record** std::vector<type_event_record *,std::allocator<type_event_record *> >::begin()
{
    // @stub
}

// ..\stlport\stl_vector.h:181
DC_ONLY(0x8f678, 0x4)
type_event_record** std::vector<type_event_record *,std::allocator<type_event_record *> >::end()
{
    // @stub
}

// ..\stlport\stl_string.h:181
DC_ONLY(0x8f67c, 0x18)
void std::_STL_alloc_proxy<type_record_shroud::type_shroud_chan()
{
    // @stub
}

// ..\stlport\stl_alloc.h:1004
DC_ONLY(0x8f694, 0xC)
void std::_STL_alloc_proxy<type_record_shroud::type_shroud_cha(const std::allocator<type_record_shroud::type_shroud_change>* __a, type_record_shroud::type_shroud_change** __p)
{
    // @stub
}

// ..\stlport\stl_alloc.h:1025
DC_ONLY(0x8f6a0, 0x2C)
void std::_STL_alloc_proxy<type_record_shroud::type_shroud_change *,type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::deallocate(type_record_shroud::type_shroud_change* __p, unsigned __n)
{
    // @stub
}

// ..\stlport\stl_alloc.h:552
DC_ONLY(0x8f6cc, 0x1C)
void std::allocator<type_record_shroud::type_shroud_change>::deallocate(type_record_shroud::type_shroud_change* __p, unsigned __n)
{
    // @stub
}

// ..\stlport\stl_vector.c:248
DC_ONLY(0x8f6e8, 0xD0)
void std::vector<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::_M_insert_overflow(type_record_shroud::type_shroud_change* __position, const type_record_shroud::type_shroud_change* __x, unsigned __fill_len)
{
    // @stub
}

// ..\stlport\stl_vector.c:68
DC_ONLY(0x8f7b8, 0x98)
void std::vector<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::reserve(unsigned __n)
{
    // @stub
}

// ..\stlport\stl_vector.c:248
DC_ONLY(0x8f850, 0xCC)
void std::vector<type_event_record *,std::allocator<type_event_record *> >::_M_insert_overflow(type_event_record** __position, type_event_record** __x, unsigned __fill_len)
{
    // @stub
}

// ..\stlport\stl_vector.c:68
DC_ONLY(0x8f91c, 0x94)
void std::vector<type_event_record *,std::allocator<type_event_record *> >::reserve(unsigned __n)
{
    // @stub
}

// ..\stlport\stl_construct.h:128
DC_ONLY(0x8f9b0, 0x30)
void std::destroy(type_record_shroud::type_shroud_change* __first, type_record_shroud::type_shroud_change* __last)
{
    // @stub
}

// ..\stlport\stl_construct.h:85
DC_ONLY(0x8f9e0, 0x3C)
void std::construct(type_record_shroud::type_shroud_change* __p, const type_record_shroud::type_shroud_change* __value)
{
    // @stub
}

// ..\stlport\stl_construct.h:85
DC_ONLY(0x8fa1c, 0x28)
void std::construct(type_event_record** __p, type_event_record** __value)
{
    // @stub
}

// ..\stlport\stl_algobase.h:322
DC_ONLY(0x8fa44, 0x50)
type_event_record** std::copy(type_event_record** __first, type_event_record** __last, type_event_record** __result)
{
    // @stub
}

// ..\stlport\stl_construct.h:128
DC_ONLY(0x8fa94, 0x30)
void std::destroy(type_event_record** __first, type_event_record** __last)
{
    // @stub
}

// ..\stlport\stl_algobase.h:322
DC_ONLY(0x8fac4, 0x50)
type_record_shroud::type_shroud_change* std::copy(type_record_shroud::type_shroud_change* __first, type_record_shroud::type_shroud_change* __last, type_record_shroud::type_shroud_change* __result)
{
    // @stub
}

// ..\stlport\stl_alloc.h:968
DC_ONLY(0x8fb14, 0x4)
std::allocator<type_record_shroud::type_shroud_change>* std::__stl_alloc_rebind(std::allocator<type_record_shroud::type_shroud_change>* __a, const type_record_shroud::type_shroud_change* __formal)
{
    // @stub
}

// ..\stlport\stl_vector.h:199
DC_ONLY(0x8fb18, 0xC)
unsigned std::vector<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::capacity()
{
    // @stub
}

// ..\stlport\stl_alloc.h:1022
DC_ONLY(0x8fb24, 0x28)
type_record_shroud::type_shroud_change* std::_STL_alloc_proxy<type_record_shroud::type_shroud_change *,type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::allocate(unsigned __n)
{
    // @stub
}

// ..\stlport\stl_vector.h:199
DC_ONLY(0x8fb4c, 0xC)
unsigned std::vector<type_event_record *,std::allocator<type_event_record *> >::capacity()
{
    // @stub
}

// ..\stlport\stl_alloc.h:1022
DC_ONLY(0x8fb58, 0x28)
type_event_record** std::_STL_alloc_proxy<type_event_record * *,type_event_record *,std::allocator<type_event_record *> >::allocate(unsigned __n)
{
    // @stub
}

// ..\stlport\stl_alloc.h:1025
DC_ONLY(0x8fb80, 0x2C)
void std::_STL_alloc_proxy<type_event_record * *,type_event_record *,std::allocator<type_event_record *> >::deallocate(type_event_record** __p, unsigned __n)
{
    // @stub
}

// ..\stlport\stl_alloc.h:547
DC_ONLY(0x8fbac, 0x28)
type_record_shroud::type_shroud_change* std::allocator<type_record_shroud::type_shroud_change>::allocate(unsigned __n, const void* __formal)
{
    // @stub
}

// ..\stlport\stl_alloc.h:547
DC_ONLY(0x8fbd4, 0x24)
type_event_record** std::allocator<type_event_record *>::allocate(unsigned __n, const void* __formal)
{
    // @stub
}

// ..\stlport\stl_alloc.h:552
DC_ONLY(0x8fbf8, 0x1C)
void std::allocator<type_event_record *>::deallocate(type_event_record** __p, unsigned __n)
{
    // @stub
}

// ..\stlport\stl_uninitialized.h:97
DC_ONLY(0x8fc14, 0x38)
type_record_shroud::type_shroud_change* std::uninitialized_copy(type_record_shroud::type_shroud_change* __first, type_record_shroud::type_shroud_change* __last, type_record_shroud::type_shroud_change* __result)
{
    // @stub
}

// ..\stlport\stl_uninitialized.h:263
DC_ONLY(0x8fc4c, 0x38)
type_record_shroud::type_shroud_change* std::uninitialized_fill_n(type_record_shroud::type_shroud_change* __first, unsigned __n, const type_record_shroud::type_shroud_change* __x)
{
    // @stub
}

// ..\stlport\stl_vector.h:514
DC_ONLY(0x8fc84, 0x38)
std::vector<type_record_shroud::type_shroud_change,std::allocator<type_record_shroud::type_shroud_change> >::_M_allocate_and_copy(unsigned __n, type_record_shroud::type_shroud_change* __first, type_record_shroud::type_shroud_change* __last)
{
    // @stub
}

// ..\stlport\stl_uninitialized.h:97
DC_ONLY(0x8fcbc, 0x38)
type_event_record** std::uninitialized_copy(type_event_record** __first, type_event_record** __last, type_event_record** __result)
{
    // @stub
}

// ..\stlport\stl_uninitialized.h:263
DC_ONLY(0x8fcf4, 0x38)
type_event_record** std::uninitialized_fill_n(type_event_record** __first, unsigned __n, type_event_record** __x)
{
    // @stub
}

// ..\stlport\stl_vector.h:514
DC_ONLY(0x8fd2c, 0x38)
std::vector<type_event_record *,std::allocator<type_event_record *> >::_M_allocate_and_copy(unsigned __n, type_event_record** __first, type_event_record** __last)
{
    // @stub
}

// ..\stlport\stl_iterator_base.h:262
DC_ONLY(0x8fd64, 0x4)
type_record_shroud::type_shroud_change* std::value_type(const type_record_shroud::type_shroud_change* __formal)
{
    // @stub
}

// ..\stlport\stl_construct.h:121
DC_ONLY(0x8fd68, 0x1C)
void std::__destroy(type_record_shroud::type_shroud_change* __first, type_record_shroud::type_shroud_change* __last, type_record_shroud::type_shroud_change* __formal)
{
    // @stub
}

// ..\stlport\stl_iterator_base.h:243
DC_ONLY(0x8fd84, 0xC)
std::random_access_iterator_tag std::iterator_category(__$ReturnUdt, type_event_record** __formal)
{
    // @stub
}

// ..\stlport\stl_iterator_base.h:291
DC_ONLY(0x8fd90, 0x4)
int* std::distance_type(type_event_record** __formal)
{
    // @stub
}

// ..\stlport\stl_algobase.h:209
DC_ONLY(0x8fd94, 0x1E)
type_event_record** std::__copy(type_event_record** __first, type_event_record** __last, type_event_record** __result, std::random_access_iterator_tag __formal, int* __formal)
{
    // @stub
}

// ..\stlport\stl_iterator_base.h:262
DC_ONLY(0x8fdb4, 0x4)
type_event_record** std::value_type(type_event_record** __formal)
{
    // @stub
}

// ..\stlport\stl_construct.h:121
DC_ONLY(0x8fdb8, 0x1C)
void std::__destroy(type_event_record** __first, type_event_record** __last, type_event_record** __formal)
{
    // @stub
}

// ..\stlport\stl_iterator_base.h:243
DC_ONLY(0x8fdd4, 0xC)
std::random_access_iterator_tag std::iterator_category(__$ReturnUdt, const type_record_shroud::type_shroud_change* __formal)
{
    // @stub
}

// ..\stlport\stl_iterator_base.h:291
DC_ONLY(0x8fde0, 0x4)
int* std::distance_type(const type_record_shroud::type_shroud_change* __formal)
{
    // @stub
}

// ..\stlport\stl_algobase.h:209
DC_ONLY(0x8fde4, 0x42)
type_record_shroud::type_shroud_change* std::__copy(type_record_shroud::type_shroud_change* __first, type_record_shroud::type_shroud_change* __last, type_record_shroud::type_shroud_change* __result, std::random_access_iterator_tag __formal, int* __formal)
{
    // @stub
}

// ..\stlport\stl_alloc.h:968
DC_ONLY(0x8fe28, 0x4)
std::allocator<type_event_record* std::__stl_alloc_rebind(std::allocator<type_event_record* __a, type_event_record** __formal)
{
    // @stub
}

// ..\stlport\stl_uninitialized.h:88
DC_ONLY(0x8fe2c, 0x1C)
type_record_shroud::type_shroud_change* std::__uninitialized_copy(type_record_shroud::type_shroud_change* __first, type_record_shroud::type_shroud_change* __last, type_record_shroud::type_shroud_change* __result, type_record_shroud::type_shroud_change* __formal)
{
    // @stub
}

// ..\stlport\stl_uninitialized.h:255
DC_ONLY(0x8fe48, 0x1C)
type_record_shroud::type_shroud_change* std::__uninitialized_fill_n(type_record_shroud::type_shroud_change* __first, unsigned __n, const type_record_shroud::type_shroud_change* __x, type_record_shroud::type_shroud_change* __formal)
{
    // @stub
}

// ..\stlport\stl_uninitialized.h:88
DC_ONLY(0x8fe64, 0x1C)
type_event_record** std::__uninitialized_copy(type_event_record** __first, type_event_record** __last, type_event_record** __result, type_event_record** __formal)
{
    // @stub
}

// ..\stlport\stl_uninitialized.h:255
DC_ONLY(0x8fe80, 0x1C)
type_event_record** std::__uninitialized_fill_n(type_event_record** __first, unsigned __n, type_event_record** __x, type_event_record** __formal)
{
    // @stub
}

// ..\stlport\stl_construct.h:110
DC_ONLY(0x8fe9c, 0x30)
void std::__destroy_aux(type_record_shroud::type_shroud_change* __first, type_record_shroud::type_shroud_change* __last, __false_type __formal)
{
    // @stub
}

// ..\stlport\stl_construct.h:110
DC_ONLY(0x8fecc, 0x30)
void std::__destroy_aux(type_event_record** __first, type_event_record** __last, __false_type __formal)
{
    // @stub
}

// ..\stlport\stl_uninitialized.h:70
DC_ONLY(0x8fefc, 0x3C)
type_record_shroud::type_shroud_change* std::__uninitialized_copy_aux(type_record_shroud::type_shroud_change* __first, type_record_shroud::type_shroud_change* __last, type_record_shroud::type_shroud_change* __result, __false_type __formal)
{
    // @stub
}

// ..\stlport\stl_uninitialized.h:239
DC_ONLY(0x8ff38, 0x3C)
type_record_shroud::type_shroud_change* std::__uninitialized_fill_n_aux(type_record_shroud::type_shroud_change* __first, unsigned __n, const type_record_shroud::type_shroud_change* __x, __false_type __formal)
{
    // @stub
}

// ..\stlport\stl_uninitialized.h:70
DC_ONLY(0x8ff74, 0x3C)
type_event_record** std::__uninitialized_copy_aux(type_event_record** __first, type_event_record** __last, type_event_record** __result, __false_type __formal)
{
    // @stub
}

// ..\stlport\stl_uninitialized.h:239
DC_ONLY(0x8ffb0, 0x3C)
type_event_record** std::__uninitialized_fill_n_aux(type_event_record** __first, unsigned __n, type_event_record** __x, __false_type __formal)
{
    // @stub
}

// ..\stlport\stl_construct.h:59
DC_ONLY(0x8ffec, 0x1C)
void std::destroy(type_record_shroud::type_shroud_change* __pointer)
{
    // @stub
}

// ..\stlport\stl_construct.h:59
DC_ONLY(0x90008, 0x1C)
void std::destroy(type_event_record** __pointer)
{
    // @stub
}

// ..\stlport\stl_construct.h:53
DC_ONLY(0x90024, 0x4)
void std::__destroy_aux()
{
    // @stub
}

// ..\stlport\stl_construct.h:53
DC_ONLY(0x90028, 0x4)
void std::__destroy_aux()
{
    // @stub
}

#endif  // @carcass

// E:\gamedcs\event_record.cpp:1367
VA(0x0049da70, 0x41)  // DC roster order + adventure-options call edge
unsigned char game::replay_available() const
{
    for (unsigned i = 0; i < eventRecords.size(); ++i) {
        if (eventRecords[i]->player_id != gNetLocalGamePos)
            return 1;
    }
    return 0;
}

// E:\gamedcs\event_record.cpp:1426
VA(0x0049dc60, 0x8C)  // linkorder dc-label, dc 0x8ebc4
unsigned char game::save_recorded_events(TAbstractFile* outfile)
{
    int count = eventRecords.size();
    outfile->Write(&count, 4);
    for (int i = 0; i < count; ++i) {
        unsigned char type = eventRecords[i]->get_type();
        outfile->Write(&type, 1);
        if (!eventRecords[i]->save(outfile))
            return 0;
    }
    return 1;
}
