// levelupwindow.cpp - E:\gamedcs\levelupwindow.cpp (compiland levelupwindow.obj)
// HAND-OWNED after admission - INITIALLY GENERATED by `python3 -m homm3.carve carcass`; prototypes are Dreamcast CodeView evidence.
// 4 functions in link order; 20 compiler-generated $-thunks omitted.
#include <va.h>
#include <stdio.h>
#include "levelupwindow.h"
#include "border.h"
#include "button.h"
#include "exec.h"
#include "game.h"
#include "hero.h"
#include "iconwdgt.h"
#include "kb.h"
#include "kbwin.h"
#include "message.h"
#include "mousemgr.h"
#include "recruit.h"
#include "remote.h"
#include "soundmgr.h"
#include "textwdgt.h"
#include "widget.h"
#include "winmgr.h"

// Shared absolute deadline used by retail dialogs. Its timer role is proven
// by this handler and the other dialog handlers that compare GameTime::Get()
// against it before synthesizing WIDGET_END_DIALOG.
DATA(0x00697784) extern unsigned long g_dialogDeadline697784;

// Both are source-private in the DC levelupwindow compiland. Retail's ctor
// stores its object through the first, and this handler is the only consumer
// of the second.
// Before normalization: gpLevelUpWindow.
// Before normalization: lastIMHoverID.
DATA(0x00699634) static TLevelUpWindow* g_levelUpWindow;
DATA(0x0067fa34) static int g_lastImHoverId = -1;

// Retail's packed table is four pointers per secondary skill: the generic
// name followed by its basic/advanced/expert display strings. The encoded
// choice is 3*skill+level, with skill zero represented by values 3..5.
DATA(0x0067dcf0) extern const TLevelUpSkillTraits (&g_levelUpSkillTraits)[28];

// Text tables read directly by the retail constructor. The shared four-entry
// primary-skill table is declared with the other game-wide data in game.h.
DATA(0x006a7570) extern const char* g_skillMasteryNames[3];

// Before normalization (function): LevelUpSkillName.
static const char* levelUpSkillName(int encodedSkill)
{
    return g_levelUpSkillTraits[encodedSkill / 3 - 1]
        .m_levelNames[encodedSkill % 3];
}

// E:\gamedcs\levelupwindow.cpp:48
// Exact after removing the synthetic diagnostic padding and restoring the
// DC set_visible/set_hotkey/operator[] calls. DC lines 64/73/76/78 and
// 86..138 support construction followed by vector append; source-family
// controls vary their genuine result lifetimes. Fusing new into push_back
// and using one begin/end for-iterator reproduces retail's reserve size()
// boundary and widget EH homes. The bb local and named back() results stay.
//
// The 180-state lifetime search reproduced two 100% forms (named or direct
// text-format results), with all four scored TU functions exact. The last
// 99.99525% control retained a portrait local and stored its allocation in
// a dead parameter slot instead of retail's EH stack home. Earlier padding
// reached only 99.12995%; its nine unreachable printf calls, alternative
// doses and meaningless VERIFY expressions never established source facts.
// No diagnostic carrier or inline-depth pin remains.
// Before normalization (locals): gained_skill, first_choice, second_choice.
VA(0x004f8880, 0xE7E)  // linkorder+caller+vtable sequence, dc 0xe8344
TLevelUpWindow::TLevelUpWindow(hero* thisHero, int gainedSkill,
                               int firstChoice, int secondChoice)
    : CAdvPopup(205, 65, 385, 470, 0x12),
      m_leftSkill(firstChoice), m_rightSkill(secondChoice), m_selected(0)
{
    m_widgets.reserve(25);

    g_levelUpWindow = this;
    if (g_networkActive69954c && !g_currentPlayer->isLocalHuman())
        g_dialogDeadline697784 = GameTime::get() + 15000;
    g_mouseManager->setPointer(0, mouseManager::ADVENTURE_SET);

    // Before normalization: bb.
    bitmapBorder* background = new bitmapBorder(
        0, 0, 385, 470, BACKGROUND_ID, "lvlupbkg.pcx", 0x800);
    background->setPlayerPaletteColors(thisHero->m_owner);
    m_widgets.push_back(background);

    m_widgets.push_back(new bitmapBorder(
        171, 66, 58, 64, PORTRAIT_ID,
        g_heroTraits[thisHero->m_portrait].m_largePortraitName, 0x800));

    // DC lines 71/86/117 call the subscript wrapper, not its getText body.
    sprintf(g_text, (*g_generalText)[GENERAL_TEXT_LEVEL_UP_TITLE_FORMAT],
            thisHero->m_name);
    m_widgets.push_back(new textWidget(
        23, 22, 339, 23, g_text, "medfont.fnt", font::PRIMARY,
        TEXT1_ID, 5, 0, 8));

    sprintf(g_text, (*g_generalText)[GENERAL_TEXT_LEVEL_UP_HERO_FORMAT],
            thisHero->m_name, thisHero->m_level, thisHero->heroFn004D8F70());
    m_widgets.push_back(new textWidget(
        23, 151, 339, 23, g_text, "medfont.fnt", font::PRIMARY,
        TEXT2_ID, 5, 0, 8));

    sprintf(g_text, "%s +1", g_primarySkillNames[gainedSkill]);
    m_widgets.push_back(new textWidget(
        23, 242, 339, 23, g_text, "medfont.fnt", font::PRIMARY,
        TEXT3_ID, 5, 0, 8));
    m_widgets.push_back(new iconWidget(
        174, 190, 42, 42, PRISKILL_ID, "pskil42.def", gainedSkill,
        0, 0, 0, 0x10));

    if (secondChoice != -1) {
        sprintf(g_text, (*g_generalText)[GENERAL_TEXT_LEVEL_UP_CHOICE],
                g_skillMasteryNames[firstChoice % 3],
                g_levelUpSkillTraits[firstChoice / 3 - 1].m_name,
                g_skillMasteryNames[secondChoice % 3],
                g_levelUpSkillTraits[secondChoice / 3 - 1].m_name);
        m_widgets.push_back(new textWidget(
            23, 270, 339, 52, g_text, "medfont.fnt", font::PRIMARY,
            TEXT4_ID, 1, 0, 8));
        m_widgets.push_back(new textWidget(
            169, 325, 50, 46,
            (*g_generalText)[GENERAL_TEXT_LEVEL_UP_OR],
            "medfont.fnt", font::PRIMARY, TEXT5_ID, 5, 0, 8));

        m_widgets.push_back(new coloredBorderFrame(
            122, 325, 47, 46, SKILLBORDER_1_ID,
            g_unnamed6aacb0->m_data[45], 0x400));
        // DC lines 93/95 retain back() followed by set_visible(false).
        widget* addedLeft = m_widgets.back();
        addedLeft->setVisible(0);

        m_widgets.push_back(new coloredBorderFrame(
            220, 325, 47, 46, SKILLBORDER_2_ID,
            g_unnamed6aacb0->m_data[45], 0x400));
        widget* addedRight = m_widgets.back();
        addedRight->setVisible(0);

        m_widgets.push_back(new iconWidget(
            124, 326, 44, 44, SKILLICON_1_ID, "secskill.def",
            firstChoice, 0, 0, 0, 0x10));
        m_widgets.push_back(new iconWidget(
            222, 326, 44, 44, SKILLICON_2_ID, "secskill.def",
            secondChoice, 0, 0, 0, 0x10));

        sprintf(g_text, "%s\n%s", g_skillMasteryNames[firstChoice % 3],
                g_levelUpSkillTraits[firstChoice / 3 - 1].m_name);
        m_widgets.push_back(new textWidget(
            102, 375, 87, 40, g_text, "smalfont.fnt", font::PRIMARY,
            TEXT6_ID, 5, 0, 8));
        sprintf(g_text, "%s\n%s", g_skillMasteryNames[secondChoice % 3],
                g_levelUpSkillTraits[secondChoice / 3 - 1].m_name);
        m_widgets.push_back(new textWidget(
            200, 375, 87, 40, g_text, "smalfont.fnt", font::PRIMARY,
            TEXT7_ID, 5, 0, 8));
    } else if (firstChoice != -1) {
        sprintf(g_text, (*g_generalText)[GENERAL_TEXT_LEVEL_UP_SINGLE_CHOICE],
                g_skillMasteryNames[firstChoice % 3],
                g_levelUpSkillTraits[firstChoice / 3 - 1].m_name);
        m_widgets.push_back(new textWidget(
            23, 270, 339, 52, g_text, "medfont.fnt", font::PRIMARY,
            TEXT4_ID, 1, 0, 8));
        m_widgets.push_back(new coloredBorderFrame(
            169, 325, 47, 46, SKILLBORDER_1_ID,
            g_unnamed6aacb0->m_data[45], 0x400));
        m_widgets.push_back(new iconWidget(
            170, 326, 44, 44, SKILLICON_1_ID, "secskill.def",
            firstChoice, 0, 0, 0, 0x10));
        sprintf(g_text, "%s\n%s", g_skillMasteryNames[firstChoice % 3],
                g_levelUpSkillTraits[firstChoice / 3 - 1].m_name);
        m_widgets.push_back(new textWidget(
            149, 375, 87, 40, g_text, "smalfont.fnt", font::PRIMARY,
            TEXT6_ID, 5, 0, 8));
        m_selected = SKILLICON_1_ID;
    }

    button* accept = new button(
        296, 413, 64, 30, LEVELUP_ACCEPT_ID, "iokay.def",
        0, 1, 0, 0, 2);
    // DC lines 135/136 call the canonical button::set_hotkey wrapper.
    accept->setHotkey(1);
    accept->setHotkey(28);
    accept->enable(firstChoice == -1 || secondChoice == -1);
    m_widgets.push_back(accept);

    for (widget** it = m_widgets.begin(); it != m_widgets.end(); ++it) {
        if (*it)
            addWidget(*it, -1);
    }

    if (g_turnDuration69d630.isOn()
            && g_turnDuration69d630.isClose(15000))
        g_dialogDeadline697784 = GameTime::get() + 15000;
    if (g_unk691209)
        g_dialogDeadline697784 = GameTime::get() + 2000;
}

// Retail places the generated wrapper immediately after the constructor;
// Dreamcast appends it to the compiland.
VA_COMPGEN(0x004f9700, 0x21, SCALAR_DELETING_DTOR, TLevelUpWindow)

// E:\gamedcs\levelupwindow.cpp:159
VA(0x004f9730, 0x4E)  // body+vtable-proven, dc 0xe8c2c
TLevelUpWindow::~TLevelUpWindow()
{
    deleteWidgets();
}

// E:\gamedcs\levelupwindow.cpp:170
// Residual (77.73%): the retail object duplicates the identical
// enable/DrawWindow/return tail in all four selection arms (12 GetWidget calls),
// while this CL cross-jumps every arm to one shared tail (9 calls); it also
// merges the several `return 0` exits that retail keeps distinct (9 rets vs our
// 11). predict-inline's only unpaired row is exactly that GetWidget 9-vs-12
// count, so the tail merge IS the whole remaining residual.
// NEW 2026-08-14: the generation hypothesis in the old note is now DISPROVEN -
// `homm3 vc6 ab run` compiles this body with the RTM C2 12.00.8168 and gets
// output byte-identical to SP3 (104+36 both), verdict `neither`. The cross-jump
// is therefore a source-input difference we have not found, not a stale-CL
// artifact. Tried and rejected: repeated longhand tails, switch-vs-if dispatch,
// reordered selection arms, an inline helper.
// Re-audited 2026-09-01: retail has 43 blocks / 315 instructions / 9 returns,
// candidate 49 / 289 / 11; the first eight blocks are exact and why-branch
// reports distance 36. Its guided unsigned-hover-id, reverse-case, and
// swap-case controls are all byte-flat at 77.72727%, so none is retained.
// Macro/source-carrier audit (2026-08-21): conventional release VERIFY of
// each accept lookup (`(void)((accept = GetWidget(id)) != 0)`) is byte-flat,
// as are release-elided call-shaped diagnostic doses of 1/3/5/9 sites at
// entry. Carrying the accept object as its concrete `button*` type is also
// byte-flat. Enabling from the natural selection invariant
// `Selected != 0` regresses to 68.2665 and leaves the same branch-shape
// distance. VERIFY/TRACE/ASSERT source history therefore cannot select the
// retail tail topology through any conventional release expansion tested.
// DC-census verdict (2026-08-14): this handler's census is CLEAN. Its
// `heroWindow::GetWidget` x12 matches our twelve sites exactly and its
// `widget::set_visible` x4 matches our four send_message pairs. The one
// under-count row, `GameTime::IsPast` x1 (dc 0x1ef04 = `ElapsedSince(t) >= 0`,
// itself `(long)(Get() - t)`), is now preserved below and remains byte-
// EXACTLY flat at 77.7273 even though it nests three inline levels deep.
// What DID move it 73.18 -> 77.73: retail materialises each GetWidget() object
// BEFORE pushing the member function's arguments (`push id; call GetWidget;
// push 4; push 6; mov ecx,eax; call send_message`), where the fused
// `GetWidget(id)->send_message(a,b)` spelling pushes the arguments first. Each
// widget is bound to a pointer local below to reproduce retail's order.
// EXACT 2026-09-05 (77.73 -> 100.00): the "tail topology" above was the
// RETURN STRUCTURE. Retail shares one `return 0` epilogue (+0x10eb) among
// the KEY breaks, the mouse-move fallthrough, the non-widget id, the codeX
// default and the right-qualifier test, and keeps a second copy only at the
// codeY switch's fallthrough (+0x11dc): an if / else-if / else-if chain
// over msg->id with ONE trailing `return 0;`, the RIGHT_SELECT arm falling
// through into DESELECT (retail's chain fallthrough arm at +0x1109 runs into
// the qualifier test), `break` where the arms bail, and one `return 0;`
// after the codeY switch. Seven separate `return 0;` statements had cost
// seven duplicated epilogues AND made VC6 cross-jump the four
// enable/DrawWindow/`return 1` tails that retail keeps separate.
VA(0x004f9780, 0x440)  // vtable slot 9+linkorder, dc 0xe8c64
int TLevelUpWindow::windowHandler(message* msg)
{
    if (!g_dialogDeadline697784) {
        int result = CAdvPopup::windowHandler(msg);
        if (result) {
            if (g_turnDuration69d630.isExpired())
                g_windowManager->m_dialogReturn = 9999;
            return result;
        }
    }

    pollSound();

    unsigned long deadline = g_dialogDeadline697784;
    if (deadline && GameTime::isPast(deadline)) {
        msg->m_id = MESSAGE_WIDGET;
        g_windowManager->m_dialogReturn = 9999;
        msg->m_codeY = widget::WIDGET_END_DIALOG;
        msg->m_codeX = widget::WIDGET_END_DIALOG;
        g_dialogDeadline697784 = 0;
        return MESSAGE_DISPATCH_FORWARD;
    }

    if (msg->m_id == MESSAGE_KEY_DOWN) {
        switch (msg->m_codeX) {
        case LEVELUP_SELECT_RIGHT_KEY: {
            if (g_levelUpWindow->m_rightSkill == -1)
                break;
            widget* leftBorder = g_levelUpWindow->getWidget(SKILLBORDER_1_ID);
            leftBorder->sendMessage(
                widget::WIDGET_CLEAR_STATUS, widget::WIDGET_DRAWN);
            widget* rightBorder = g_levelUpWindow->getWidget(SKILLBORDER_2_ID);
            rightBorder->sendMessage(
                widget::WIDGET_SET_STATUS, widget::WIDGET_DRAWN);
            g_levelUpWindow->m_selected = SKILLICON_2_ID;
            widget* accept = g_levelUpWindow->getWidget(LEVELUP_ACCEPT_ID);
            accept->enable(1);
            g_levelUpWindow->drawWindow(1, 0xffff0001, 0xffff);
            return MESSAGE_DISPATCH_CONSUME;
        }

        case LEVELUP_SELECT_LEFT_KEY: {
            if (g_levelUpWindow->m_leftSkill == -1)
                break;
            widget* leftBorder = g_levelUpWindow->getWidget(SKILLBORDER_1_ID);
            leftBorder->sendMessage(
                widget::WIDGET_SET_STATUS, widget::WIDGET_DRAWN);
            if (g_levelUpWindow->m_rightSkill != -1) {
                widget* rightBorder =
                    g_levelUpWindow->getWidget(SKILLBORDER_2_ID);
                rightBorder->sendMessage(
                    widget::WIDGET_CLEAR_STATUS, widget::WIDGET_DRAWN);
            }
            g_levelUpWindow->m_selected = SKILLICON_1_ID;
            widget* accept = g_levelUpWindow->getWidget(LEVELUP_ACCEPT_ID);
            accept->enable(1);
            g_levelUpWindow->drawWindow(1, 0xffff0001, 0xffff);
            return MESSAGE_DISPATCH_CONSUME;
        }
        }
    } else if (msg->m_id == MESSAGE_MOUSE_MOVE) {
        int hoverID = g_levelUpWindow->findWidget(msg->m_mouseX, msg->m_mouseY);
        if (hoverID != g_lastImHoverId) {
            g_lastImHoverId = hoverID;
            if (hoverID != -1)
                g_mouseManager->setPointer(0, mouseManager::ADVENTURE_SET);
        }
    } else if (msg->m_id == MESSAGE_WIDGET) {
        switch (msg->m_codeX) {
        case widget::WIDGET_RIGHT_SELECT:
            switch (msg->m_codeY) {
            case SKILLICON_1_ID:
            case SKILLBORDER_1_ID:
                normalDialog(levelUpSkillName(g_levelUpWindow->m_leftSkill),
                    4, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
                break;
            case SKILLICON_2_ID:
            case SKILLBORDER_2_ID:
                normalDialog(levelUpSkillName(g_levelUpWindow->m_rightSkill),
                    4, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0);
                break;
            }
            // The right-click arm shares the selection tail below.
        case widget::WIDGET_DESELECT:
            if (msg->m_qualifier & MESSAGE_MODIFIER_RIGHT)
                break;

            switch (msg->m_codeY) {
            case SKILLICON_1_ID:
            case SKILLBORDER_1_ID: {
                widget* rightBorder =
                    g_levelUpWindow->getWidget(SKILLBORDER_2_ID);
                widget* leftBorder =
                    g_levelUpWindow->getWidget(SKILLBORDER_1_ID);
                leftBorder->sendMessage(
                    widget::WIDGET_SET_STATUS, widget::WIDGET_DRAWN);
                if (rightBorder)
                    rightBorder->sendMessage(
                        widget::WIDGET_CLEAR_STATUS, widget::WIDGET_DRAWN);
                g_levelUpWindow->m_selected = SKILLICON_1_ID;
                widget* accept =
                    g_levelUpWindow->getWidget(LEVELUP_ACCEPT_ID);
                accept->enable(1);
                g_levelUpWindow->drawWindow(1, 0xffff0001, 0xffff);
                return MESSAGE_DISPATCH_CONSUME;
            }

            case SKILLICON_2_ID:
            case SKILLBORDER_2_ID: {
                widget* leftBorder =
                    g_levelUpWindow->getWidget(SKILLBORDER_1_ID);
                leftBorder->sendMessage(
                    widget::WIDGET_CLEAR_STATUS, widget::WIDGET_DRAWN);
                widget* rightBorder =
                    g_levelUpWindow->getWidget(SKILLBORDER_2_ID);
                rightBorder->sendMessage(
                    widget::WIDGET_SET_STATUS, widget::WIDGET_DRAWN);
                g_levelUpWindow->m_selected = SKILLICON_2_ID;
                widget* accept =
                    g_levelUpWindow->getWidget(LEVELUP_ACCEPT_ID);
                accept->enable(1);
                g_levelUpWindow->drawWindow(1, 0xffff0001, 0xffff);
                return MESSAGE_DISPATCH_CONSUME;
            }

            case LEVELUP_ACCEPT_ID:
                msg->m_id = MESSAGE_WIDGET;
                g_windowManager->m_dialogReturn = g_levelUpWindow->m_selected;
                msg->m_codeY = widget::WIDGET_END_DIALOG;
                msg->m_codeX = widget::WIDGET_END_DIALOG;
                return MESSAGE_DISPATCH_FORWARD;
            }
            return 0;
        }
    }

    return 0;
}
