// overview.cpp - E:\gamedcs\overview.cpp (compiland overview.obj)
// HAND-OWNED after admission - INITIALLY GENERATED by `python3 -m homm3.carve carcass`; prototypes are Dreamcast CodeView evidence.
// 22 functions in link order; 20 compiler-generated $-thunks omitted.
#include <va.h>
#include <string.h>
#include "overview.h"
#include "game.h"
#include "kb.h"
#include "message.h"
#include "resourcemanager.h"
#include "slider.h"
#include "textwdgt.h"
#include "window.h"
#include "winmgr.h"

// The names are Dreamcast-attested; every retail address and extent below is
// independently fixed by SetupNewOverviewType's indexed accesses.
DATA(0x0069cbbc) static int giOverviewItems[2];
// Retail UpdateBackpack indexes one byte per local-player hero slot. The
// eight-byte extent is fixed by playerData::HERO_SLOT_COUNT and by the next
// overview datum in this packed run.
DATA(0x0069cbc4) static unsigned char gOverviewBackpackStart[8];
DATA(0x0069cbd4) static slider* overviewSlider;
// The hero-id half of the overview roster: UpdateBackpack indexes it with
// giOverviewTop[giOverviewType] + iSlot, and the retail GetHero expansion
// proves dword elements. The following four-dword gap is the town roster.
DATA(0x0069cbec) static int gOverviewHeroIds[8];
DATA(0x0069cc1c) static textWidget* textWidgetTitle[3];
DATA(0x0069cc34) static int iOverviewItems;
// The retail window is TOverviewWindow, whose derived layout is not needed by
// this base-interface consumer and is deliberately not fabricated here.
DATA(0x0069cc3c) static heroWindow* overWin;
DATA(0x0069cc54) static int giOverviewType;
DATA(0x0069cc58) static int giOverviewTop[2];
DATA(0x006a7ec0) static const char* cOverviewText[6];
DATA(0x006a7ecc) static const char* cTownOverviewText[3];

#if 0  // @carcass

// E:\gamedcs\overview.cpp:220
DC_ONLY(0x104458, 0x25A4)
void game::SetupDynamicStuff(int bUpdate, int bForceUpdate)
{
    // @stub
}

#endif  // @carcass

// E:\gamedcs\overview.cpp:1170. The DC name/locals and HoMM2 lineage give
// the source vocabulary; the Complete body proves the changed player fields,
// slider update, two-message protocol, per-mode title counts, and geometry.
// E:\gamedcs\overview.cpp:1170
VA(0x0051e330, 0x33A)
void game::SetupNewOverviewType(int iWhichType, unsigned char bUpdate)
{
    message msg;

    giOverviewType = iWhichType;
    iOverviewItems = giOverviewType == 0
        ? gpGame->GetLocalPlayer()->numHeroes
        : gpGame->GetLocalPlayer()->numTowns;

    if (giOverviewTop[giOverviewType] > iOverviewItems - 4)
        giOverviewTop[giOverviewType] = iOverviewItems - 4;
    if (giOverviewTop[giOverviewType] < 0)
        giOverviewTop[giOverviewType] = 0;

    if (giOverviewItems[giOverviewType] > 4) {
        overviewSlider->SetResolution(giOverviewItems[giOverviewType] - 3);
        overviewSlider->SetState(giOverviewTop[giOverviewType]);
    } else {
        overviewSlider->SetResolution(1);
    }

    msg.codeY = 195 + (giOverviewType != 1);
    msg.qualifier = 0;
    msg.mouseX = 0;
    msg.mouseY = 0;
    msg.window = 0;
    msg.id = MESSAGE_WIDGET;
    msg.codeX = widget::WIDGET_CLEAR_STATUS;
    msg.extra = 8;
    overWin->BroadcastMessage(&msg);

    msg.codeY = 195 + (giOverviewType != 0);
    msg.codeX = widget::WIDGET_SET_STATUS;
    overWin->BroadcastMessage(&msg);

    unsigned short titleXOffs[6] = {
        28, 435, 459, 28, 266, 499
    };
    unsigned short titleWidths[6] = {
        250, 287, 241, 230, 213, 213
    };

    for (int title = 0; title < 3; title++) {
        if (textWidgetTitle[title]) {
            overWin->RemoveWidget(textWidgetTitle[title]);
            delete textWidgetTitle[title];
            textWidgetTitle[title] = 0;
        }
    }

    if (giOverviewType == 0) {
        for (int title = 0; title < 2; title++) {
            strcpy(gText, cOverviewText[title]);
            textWidgetTitle[title] = new textWidget(
                titleXOffs[giOverviewType * 3 + title], 3,
                titleWidths[giOverviewType * 3 + title], 20, gText,
                "medfont.fnt",
                font::PRIMARY, title + 110,
                font::CENTER_JUSTIFIED, 0, 8);
            overWin->AddWidget(textWidgetTitle[title], -1);
        }
    } else {
        for (int title = 0; title < 3; title++) {
            strcpy(gText, cTownOverviewText[title]);
            textWidgetTitle[title] = new textWidget(
                titleXOffs[giOverviewType * 3 + title], 3,
                titleWidths[giOverviewType * 3 + title], 20, gText,
                DATA_COMPGEN(0x0065f2ec, overviewMedfontFnt, "medfont.fnt"),
                font::PRIMARY, title + 110,
                font::CENTER_JUSTIFIED, 0, 8);
            overWin->AddWidget(textWidgetTitle[title], -1);
        }
    }

    SetupDynamicStuff(0, 0);
    if (bUpdate)
        overWin->DrawWindow(bUpdate, 100, 999);
}

// Retail vtable 0x640320 slot 0. Dreamcast's canonical scalar-deleting
// wrapper agrees with the x86 destructor-then-conditional-delete sequence.
// E:\gamedcs\overview.cpp:2083
VA_COMPGEN(0x00520d60, 0x21, SCALAR_DELETING_DTOR, TOverviewWindow)

// Dreamcast proves the source-level Widgets deletion loop and CAdvPopup base
// destruction. Complete drops Dreamcast's resource-cache call (there is no
// corresponding x86 call) and independently proves the two derived vector
// teardowns at +0x74 and +0x64 between that loop and the base destructor.
// E:\gamedcs\overview.cpp:2086
VA(0x00520d90, 0x9C)  // vtable 0x640320 + two vector teardowns, dc 0x108f74
TOverviewWindow::~TOverviewWindow()
{
    for (widget** it = Widgets.begin(); it != Widgets.end(); ++it) {
        if (*it)
            delete *it;
    }

    // DC keeps this cache sweep out of line. Complete has no call at this
    // point; the PC declaration is therefore its retail-neutral inline form.
    ResourceManager::del_Spr_from_Cache();
}

#if 0  // @carcass

// E:\gamedcs\overview.cpp:1254
DC_ONLY(0x106d18, 0x7E)
void UpdateFlaggableIcon(int i)
{
    // @stub
}

// E:\gamedcs\overview.cpp:1279
DC_ONLY(0x106d98, 0x32)
void UpdateFlaggableIcons()
{
    // @stub
}

// E:\gamedcs\overview.cpp:1287
DC_ONLY(0x106dcc, 0xC2)
void DoFlaggableButtons(int which)
{
    // @stub
}

// E:\gamedcs\overview.cpp:1314
DC_ONLY(0x106e90, 0x7D6)
void game::Overview()
{
    // @stub
}

#endif  // @carcass

// E:\gamedcs\overview.cpp:1528. Dreamcast proves the four locals, their
// scopes, and the statement order: hero lookup, last-backpack bound, artifact
// and message construction, eight visible slots, status update, two window
// redraws, then the screen rectangle. Retail independently fixes the hero-id
// and backpack-start arrays, Complete's 200-id / 116-pixel slot strides, and
// the eight-slot widening.
//
// Residual (96.574%): ten of eleven retail CFG blocks align semantically. VC6
// keeps the slot-id base in ebx but reloads it at the loop test in this TU,
// while retail reloads it at the loop bottom; that adds one exit-only block.
// The remaining byte delta is the equivalent commutative LEA operand order.
// Negative controls: declaring `i` at the DC local-list position and assigning
// it in the for initializer drops to 91.930%; reversing `i + iSlotOff` is
// codegen-neutral and cannot change the LEA encoding. The current source keeps
// every DC-proven local, statement group and scope while banking the best VC6
// lowering found.
// E:\gamedcs\overview.cpp:1528
VA(0x00522470, 0x15E)  // body/arity identified, dc 0x107668
void UpdateBackpack(int iSlot)
{
    int heroNumber = giOverviewTop[giOverviewType] + iSlot;
    int iSlotOff = iSlot * 200 + 200;
    int i = 0;
    hero* currHero = gpGame->GetHero(gOverviewHeroIds[heroNumber]);
    int lastBackpackIndex = currHero->get_last_backpack_index() + 1;
    type_artifact artifact;
    message msg(0, 0, 0, 0, 0, 0, 0, 0);

    msg.id = MESSAGE_WIDGET;
    msg.codeX = widget::WIDGET_SET_ICON_FRAME;

    for (; i < 8 && i < lastBackpackIndex; ++i) {
        msg.codeY = i + iSlotOff + 130;
        artifact = *currHero->get_backpack(
            (gOverviewBackpackStart[heroNumber] + i) % lastBackpackIndex);
        msg.extra = artifact.artifactId;
        overWin->BroadcastMessage(&msg);

        if (artifact.artifactId == -1)
            overWin->WidgetClearStatus(i + iSlotOff + 130, 4);
        else
            overWin->WidgetSetStatus(i + iSlotOff + 130, 4);
    }

    overWin->DrawWindow(1, 0xffff0001, 0xffff);
    overWin->DrawWindow(0, iSlotOff + 130, iSlotOff + 137);
    gpWindowManager->UpdateScreen(293, iSlot * 116 + 91, 428, 46);
}

#if 0  // @carcass

// E:\gamedcs\overview.cpp:1562
DC_ONLY(0x1077e8, 0x100)
void UpdateArtifacts(int iSlot)
{
    // @stub
}

#endif  // @carcass

// E:\gamedcs\overview.cpp:1597. The DC five-line dossier predicts both
// GetLocalPlayer calls, the hero-slot bound, GetHero and the final backpack
// query. Retail has that exact call/access sequence and fastcall arity.
// E:\gamedcs\overview.cpp:1597
VA(0x005225d0, 0x55)  // body/arity identified, dc 0x1078e8
long get_last_backpack_index(long hero_number)
{
    if (hero_number >= gpGame->GetLocalPlayer()->numHeroes)
        return 0;
    hero* currHero = gpGame->GetHero(
        gpGame->GetLocalPlayer()->heroes[hero_number]);
    return currHero->get_last_backpack_index();
}

#if 0  // @carcass

// E:\gamedcs\overview.cpp:1612
DC_ONLY(0x107974, 0x42)
void increment_backpack_start(long slot)
{
    // @stub
}

// E:\gamedcs\overview.cpp:1629
DC_ONLY(0x1079b8, 0x42)
void decrement_backpack_start(long slot)
{
    // @stub
}

// E:\gamedcs\overview.cpp:1647
DC_ONLY(0x1079fc, 0x94)
void show_artifact(hero* currHero, const type_artifact* artifact, unsigned char right_mouse)
{
    // @stub
}

// E:\gamedcs\overview.cpp:1663
DC_ONLY(0x107a90, 0xA10)
int game::ProcessIconSelect(int codeY, unsigned char bRightMouse)
{
    // @stub
}

// E:\gamedcs\overview.cpp:2010
DC_ONLY(0x1084a0, 0x50)
void OverviewSliderCallback(int state, heroWindow* parent_window)
{
    // @stub
}

// E:\gamedcs\overview.cpp:2017
DC_ONLY(0x1084f0, 0xA84)
void TOverviewWindow::TOverviewWindow()
{
    // @stub
}

// E:\gamedcs\overview.cpp:2086
DC_ONLY(0x108f74, 0x68)
void TOverviewWindow::~TOverviewWindow()
{
    // @stub
}

// E:\gamedcs\overview.cpp:2096
DC_ONLY(0x108fdc, 0x50)
void TOverviewWindow::ClearButtons(int slot)
{
    // @stub
}

// E:\gamedcs\overview.cpp:2103
DC_ONLY(0x10902c, 0x40)
void TOverviewWindow::UpdateRollover(char* cText)
{
    // @stub
}

// E:\gamedcs\overview.cpp:2115
DC_ONLY(0x10906c, 0x90E)
void TOverviewWindow::DoRollover(int codeY)
{
    // @stub
}

// E:\gamedcs\overview.cpp:2546
DC_ONLY(0x10997c, 0x87C)
int TOverviewWindow::WindowHandler(message* msg)
{
    // @stub
}

// E:\gamedcs\Hero.h:664
DC_ONLY(0x10a1f8, 0x18)
town* hero::GetOccupiedTown()
{
    // @stub
}

// E:\gamedcs\overview.cpp:2083
DC_ONLY(0x10a210, 0x34)
void* TOverviewWindow::`scalar deleting destructor'(unsigned __flags)
{
    // @stub
}

#endif  // @carcass
