// singleselectionpopups.cpp - E:\gamedcs\singleselectionpopups.cpp (compiland singleselectionpopups.obj)
// HAND-OWNED after admission - INITIALLY GENERATED by `python3 -m homm3.carve carcass`; prototypes are Dreamcast CodeView evidence.
//
// Popup-dialog family. Three widget subclasses of widget (CHotspotWidget,
// CSpriteWidget, CBitmapWidget) and four TDialogBox-derived single-selection
// dialogs (CBonusDlg, CHeroDlg, CTownDlg, CTeamAlignmentDlg) whose common
// base CSingleSelPopup is fully inlined into each derived ctor. The whole
// order-map is vtable-proven: every class ctor stores its own vtable and each
// vtable's overridden slots name the retail address directly (address-take
// proof). Vtables read straight from the hash-verified image:
//   CHotspotWidget  0x6419a4   (widget subclass, 13 slots)
//   CSpriteWidget   0x641a00   (widget subclass, 13 slots)
//   CBitmapWidget   0x641a34   (widget subclass, 13 slots)
//   CBonusDlg       0x6419d8   (TDialogBox subclass, 10 slots)
//   CHeroDlg        0x641a68   (TDialogBox subclass, 10 slots)
//   CTownDlg        0x641a90   (TDialogBox subclass, 10 slots)
//   CTeamAlignmentDlg 0x641ab8 (TDialogBox subclass, 10 slots)
// ICF folds several bodies: CBitmapWidget::Main and its scalar deleting
// destructor onto CSpriteWidget's (0x575a10 / 0x5757b0), and the CTownDlg /
// CTeamAlignmentDlg scalar deleting destructors onto CHeroDlg's (0x575e30);
// the folded twins keep DC_ONLY rows below (one retail address = one claim).
// Widget/CSingleSelPopup ctors and the trivial zBufferDraw/Draw stubs are
// inlined or ICF-folded out of this TU (0x404140 / 0x404df0 shared empties).
// All three widget non-deleting dtors fold to 0x575a60 (jmp ~widget) and all
// four dialog non-deleting dtors fold to 0x576530 (jmp ~TDialogBox); they are
// emitted here as empty out-of-line bodies with no claim of their own.
//
// CreateWin family status: the two CBonusDlg::CreateWin overloads are
// reconstructed (98.00 / 95.51) and cap on the register-homing family - the
// schedule is aligned (why-reg flow-distance 0) but retail binds `this` to edi
// and the per-widget temp to esi where our CL binds them the other way, a swap
// the vc6 catalog reports as not source-addressable. CHeroDlg and CTownDlg
// remain @stub; CTeamAlignmentDlg is reconstructed below.
#include <va.h>
#include "singleselectionpopups.h"
#include "bitmap816.h"
#include "bitmap16.h"
#include "csprite.h"
#include "winmgr.h"
#include "remote.h"
#include "kbwin.h"
#include "game.h"
#include "iconwdgt.h"
#include "textresource.h"
#include "textwdgt.h"

// ============================================================================
// CHotspotWidget - a bare rectangular click target.
// ============================================================================

// E:\gamedcs\singleselectionpopups.cpp:114
// The ctor calls ??0widget@@QAE@XZ (default base ctor) and stores five dwords
// straight into the widget base; DC's trailing `focus` byte is not a retail
// parameter (`ret 0x14`).
VA(0x00575220, 0x40)  // anchor-vtable CHotspotWidget ctor stores vtbl 0x6419a4, calls ??0widget, ret 0x14 (5 args; DC lists 6), dc 0x12de28
CHotspotWidget::CHotspotWidget(int xPos, int yPos, int w, int h, int widgetId)
{
    x = xPos;
    y = yPos;
    width = w;
    height = h;
    id = widgetId;
}

CHotspotWidget::~CHotspotWidget()
{
}

// E:\gamedcs\singleselectionpopups.cpp:121
VA_COMPGEN(0x00575260, 0x21, SCALAR_DELETING_DTOR, CHotspotWidget)  // vtbl 0x6419a4 slot0, dc 0x12f2b8

// E:\gamedcs\singleselectionpopups.cpp:124 - slot 2 of vtable 0x6419a4, the
// same hotspot mouse handler border::Main runs one file over: a field_2C
// asleep guard, a not-active bail to widget::Main, and a jump-table switch on
// msg->id with the disabled DOWN/UP arms falling through to their right-button
// twins. mouseX/mouseY are int (heroWindow::x/y are int, +8.9 over short).
//
// Residual (94.28%): the SAME merged-return generation class border::Main
// carries (its residual note quotes the identical DUP-EXIT). Retail merges
// the RIGHT_BUTTON_UP not-selected exit into the shared return-0 block the
// field_2C guard opens (backward `je`); this C2 duplicates it as a fifth
// `ret`. Plain `return 0;` at every exit is the closest (94.28); a
// `goto returnZero` from any later exit re-sinks the guard to `jg` and drops
// it to 90.06 - the `--branches` DUP-EXIT with the guard block moved. Not
// source-reachable, same as border::Main.
VA(0x00575290, 0x179)  // anchor-vtable CHotspotWidget vtbl 0x6419a4 slot2 (Main override), ret 4, dc 0x12dea8
int CHotspotWidget::Main(message* msg)
{
    if (field_2C > 0)
        return 0;

    if (!(status & WIDGET_ACTIVE))
        return widget::Main(msg);

    unsigned char isDisabled = 0;
    if (status & WIDGET_DISABLED)
        isDisabled = 1;

    switch (msg->id) {
    case MESSAGE_LEFT_BUTTON_DOWN:
        if (isDisabled)
            break;
        // fall through
    case MESSAGE_RIGHT_BUTTON_DOWN: {
        int mouseX = msg->codeX - parentWindow->x;
        int mouseY = msg->codeY - parentWindow->y;
        if (mouseX < x || mouseY < y || mouseX >= x + width
            || mouseY >= y + height)
            return 0;
        if (msg->id == MESSAGE_RIGHT_BUTTON_DOWN) {
            msg->qualifier = MESSAGE_MODIFIER_RIGHT;
            msg->codeX = WIDGET_RIGHT_SELECT;
        } else {
            status |= WIDGET_SELECTED;
            msg->codeX = WIDGET_SELECT;
        }
        msg->id = MESSAGE_WIDGET;
        msg->codeY = id;
        return 2;
    }

    case MESSAGE_LEFT_BUTTON_UP:
        if (isDisabled)
            break;
        // fall through
    case MESSAGE_RIGHT_BUTTON_UP:
        if (!(status & WIDGET_SELECTED))
            return 0;
        status &= ~WIDGET_SELECTED;
        msg->id = MESSAGE_WIDGET;
        msg->codeX = WIDGET_DESELECT;
        msg->codeY = id;
        return 2;
    }
    return widget::Main(msg);
}

// ============================================================================
// CBonusDlg - the two-CreateWin bonus dialog.
// ============================================================================

// E:\gamedcs\singleselectionpopups.cpp:214 - the inlined CSingleSelPopup ctor:
// push 0x12 through TDialogBox, store the CBonusDlg vtable, store gameMode.
VA(0x00575410, 0x20)  // anchor-vtable CBonusDlg ctor stores vtbl 0x6419d8, calls ??0TDialogBox(0x12), ret 4, dc 0x12dfa8
CBonusDlg::CBonusDlg(unsigned char newGameMode)
    : CSingleSelPopup(0x12, newGameMode)
{
}

CBonusDlg::~CBonusDlg()
{
}

CHeroDlg::~CHeroDlg()
{
}

CTownDlg::~CTownDlg()
{
}

CTeamAlignmentDlg::~CTeamAlignmentDlg()
{
}

// E:\gamedcs\singleselectionpopups.h:45 - slot 3 of every dialog vtable. A
// right-click (RIGHT_BUTTON_UP) or a network abort-popup ends the dialog with
// WIDGET_END_DIALOG in both codeX/codeY; everything else falls through to the
// base heroWindow::handle_message (folded onto inputManager::Main 0x4ec560).
// The two end-dialog paths keep their own dialogReturn/id stores and share
// only the codeX/codeY/return tail, exactly as retail cross-jumps them; the
// `id = MESSAGE_WIDGET` store must precede `dialogReturn = codeY` (id store
// stays per-block, +12.8) and the netmsg chain nests inside the id!=0x40 arm
// so the default `return` sinks between the two arms (+45 over the flat form).
//
// Residual (99.96%): every instruction byte matches; the only deltas are
// three reloc-NAME cosmetics the model does not resolve here - bVideoPaused
// (data_29954c) and pDPlay (data_29d808) are unnamed tree-wide (their owning
// objs delink them to working labels too), and the tail call names the folded
// heroWindow::handle_message where the model carries only its ICF twin
// inputManager::Main (0x4ec560). Reloc-name-only, not source-reachable from
// this TU (the names live in shared headers / other objs).
VA(0x00575430, 0x8f)  // anchor-vtable CSingleSelPopup::handle_message = shared slot3 of all four dialog vtables, ret 4, dc 0x12ef28
int CSingleSelPopup::handle_message(message& msg)
{
    if (msg.id != MESSAGE_RIGHT_BUTTON_UP) {
        if (bVideoPaused && pDPlay) {
            CNetMsgHandler* handler = pDPlay->GetNetMsgHandler();
            if (handler) {
                handler->CheckHandleNet(1, 0);
                if (handler->GetAbortPopupMsg()) {
                    msg.id = MESSAGE_WIDGET;
                    gpWindowManager->dialogReturn = msg.codeY;
                    msg.codeX = widget::WIDGET_END_DIALOG;
                    msg.codeY = widget::WIDGET_END_DIALOG;
                    return 2;
                }
            }
        }
        return heroWindow::handle_message(msg);
    }
    msg.id = MESSAGE_WIDGET;
    gpWindowManager->dialogReturn = msg.codeY;
    msg.codeX = widget::WIDGET_END_DIALOG;
    msg.codeY = widget::WIDGET_END_DIALOG;
    return 2;
}

// E:\gamedcs\singleselectionpopups.cpp:215
VA_COMPGEN(0x005754c0, 0x21, SCALAR_DELETING_DTOR, CBonusDlg)  // vtbl 0x6419d8 slot0, dc 0x12f304

// E:\gamedcs\singleselectionpopups.cpp:218 - the sprite-bonus dialog: a
// medfont title, the centred CSpriteWidget icon (its ctor inlined here,
// storing vtbl 0x641a00 and normalising the frame via GetNumFrames(0)), and
// two smalfont captions. Setup fixes the 300x225 frame; each widget is heap-
// allocated and registered through Add.
VA(0x005754f0, 0x254)  // anchor-vtable CBonusDlg::CreateWin(sprite) inlines CSpriteWidget ctor (stores vtbl 0x641a00), ret 0x14 (5 args), dc 0x12dff0
unsigned char CBonusDlg::CreateWin(const char* title, CSprite* sprite, int frame, const char* botTitle, const char* description)
{
    if (!Setup(300, 225, 200, 150))
        return 0;
    Add(new textWidget(10, 26, width - 20, 36, title, "medfont.fnt",
        font::PRIMARY, -1, 1, 0, 8));
    Add(new CSpriteWidget((width - sprite->Width) / 2, 60, sprite, frame));
    Add(new textWidget(10, 95, width - 20, 18, botTitle, "smalfont.fnt",
        font::PRIMARY, -1, 1, 0, 8));
    Add(new textWidget(15, 120, width - 30, height - 120, description,
        "smalfont.fnt", font::PRIMARY, -1, 1, 0, 8));
    return 1;
}

// ============================================================================
// CSpriteWidget - a widget wrapping a CSprite.
// ============================================================================

// E:\gamedcs\singleselectionpopups.cpp:71 - slot 4 of vtable 0x641a00. Draws
// the sprite through the screen bitmap: the DC Bitmap16Bit overload of
// CSprite::Draw, whose header wrapper expands the dst->map/Width/Height/Pitch
// reads inline.
VA(0x00575750, 0x54)  // anchor-vtable CSpriteWidget vtbl 0x641a00 slot4 (Draw override), size = DC exact, dc 0x12f0c8
void CSpriteWidget::Draw()
{
    sprite->Draw(0, frame, 0, 0, width, height,
        gpWindowManager->screenBitmap, x + parentWindow->x,
        y + parentWindow->y, 0, 1);
}

// E:\gamedcs\singleselectionpopups.cpp:47 - inlined into every CreateWin that
// builds a sprite icon (dc 0x12f018, no standalone retail body). Stores the
// sprite/frame past the widget base and normalises frame against sequence 0's
// count; GetNumFrames(0)'s else arm folds to the literal-0 divisor.
CSpriteWidget::CSpriteWidget(int xPos, int yPos, CSprite* pSprite, int frameArg)
{
    sprite = pSprite;
    frame = frameArg;
    x = xPos;
    y = yPos;
    width = pSprite->Width;
    height = pSprite->Height;
    frame %= pSprite->GetNumFrames(0);
}

CSpriteWidget::~CSpriteWidget()
{
}

// E:\gamedcs\singleselectionpopups.cpp:73
VA_COMPGEN(0x005757b0, 0x21, SCALAR_DELETING_DTOR, CSpriteWidget)  // vtbl 0x641a00 slot0; ICF folds CBitmapWidget dtor (dc 0x12f26c), dc 0x12f11c

// E:\gamedcs\singleselectionpopups.cpp:234 - the bitmap-bonus twin of the
// sprite CreateWin above: same medfont title / smalfont captions, with a
// centred CBitmapWidget (ctor inlined, storing vtbl 0x641a34) in place of the
// sprite icon.
VA(0x005757e0, 0x226)  // anchor-vtable CBonusDlg::CreateWin(bitmap) inlines CBitmapWidget ctor (stores vtbl 0x641a34), ret 0x10 (4 args), dc 0x12e1cc
unsigned char CBonusDlg::CreateWin(const char* title, Bitmap816* pImage, const char* botTitle, const char* description)
{
    if (!Setup(300, 225, 200, 150))
        return 0;
    Add(new textWidget(10, 26, width - 20, 36, title, "medfont.fnt",
        font::PRIMARY, -1, 1, 0, 8));
    Add(new CBitmapWidget((width - pImage->Width) / 2, 60, pImage));
    Add(new textWidget(10, 95, width - 20, 18, botTitle, "smalfont.fnt",
        font::PRIMARY, -1, 1, 0, 8));
    Add(new textWidget(15, 120, width - 30, height - 120, description,
        "smalfont.fnt", font::PRIMARY, -1, 1, 0, 8));
    return 1;
}

// E:\gamedcs\singleselectionpopups.cpp:61
VA(0x00575a10, 0x10)  // anchor-vtable CSpriteWidget vtbl 0x641a00 slot2 (Main override; ICF folds CBitmapWidget::Main), dc 0x12f0ac
int CSpriteWidget::Main(message* msg)
{
    return widget::Main(msg);
}

// ============================================================================
// CBitmapWidget - a widget wrapping a Bitmap816.
// ============================================================================

// E:\gamedcs\singleselectionpopups.cpp:103 - slot 4 of vtable 0x641a34. Blits
// the image at full size through the screen bitmap; no null guard on image.
VA(0x00575a20, 0x3e)  // anchor-vtable CBitmapWidget vtbl 0x641a34 slot4 (Draw override), calls Bitmap816::Draw, dc 0x12f1fc
void CBitmapWidget::Draw()
{
    image->Draw(0, 0, image->Width, image->Height,
        gpWindowManager->screenBitmap, x + parentWindow->x,
        y + parentWindow->y, 1);
}

// E:\gamedcs\singleselectionpopups.cpp:82 - inlined into the bitmap CreateWin
// callers (dc 0x12f168, no standalone retail body). Stores the image past the
// widget base with the bitmap's own extent.
CBitmapWidget::CBitmapWidget(int xPos, int yPos, Bitmap816* pImage)
{
    image = pImage;
    x = xPos;
    y = yPos;
    width = pImage->Width;
    height = pImage->Height;
}

CBitmapWidget::~CBitmapWidget()
{
}

// ============================================================================
// CHeroDlg
// ============================================================================

// E:\gamedcs\singleselectionpopups.cpp:255
VA(0x00575a70, 0x20)  // anchor-vtable CHeroDlg ctor stores vtbl 0x641a68, calls ??0TDialogBox(0x12), ret 4, dc 0x12e3a0
CHeroDlg::CHeroDlg(unsigned char newGameMode)
    : CSingleSelPopup(0x12, newGameMode)
{
}

// E:\gamedcs\singleselectionpopups.cpp:260
// Residual (93.93%): all 24 blocks, 9 branches / 2 returns, and the ordered
// call multiset agree. why-reg reports a 174-slot register-visible distance:
// the Widgets vector base and per-widget allocation result trade EBX/EDI even
// though their definition slots agree, the C1 front-end-handle-state class.
VA(0x00575a90, 0x380)  // anchor-vtable CHeroDlg::CreateWin inlines CBitmapWidget (vtbl 0x641a34) + CSpriteWidget (vtbl 0x641a00) ctors, ret 0x18 (6 args), dc 0x12e3f0
unsigned char CHeroDlg::CreateWin(Bitmap816* heroPick, const char* heroName, CSprite* specialtyIcon, int frame, const char* specialtyName, const char* desc)
{
    char sTemp[256];

    if (!Setup(250, 172, 300, 256))
        return 0;

    Add(new textWidget(30, 26, width - 60, 36,
        gpGeneralText->GetText(78), "medfont.fnt", font::PRIMARY,
        -1, 1, 0, 8));
    Add(new CBitmapWidget((width - heroPick->Width) / 2, 56, heroPick));

    sprintf(sTemp, DATA_COMPGEN(
        0x0066033c, rolloverOwnedObjectFormat, "%s - %s"), heroName, desc);
    Add(new textWidget(30, 91, width - 60, 18, sTemp,
        "smalfont.fnt", font::PRIMARY, -1, 1, 0, 8));

    Add(new textWidget(30, 122, width - 60, 36,
        gpGeneralText->GetText(79), "medfont.fnt", font::PRIMARY,
        -1, 1, 0, 8));
    Add(new CSpriteWidget((width - specialtyIcon->Width) / 2, 149,
        specialtyIcon, frame));
    Add(new textWidget(30, specialtyIcon->Height + 151, width - 60, 36,
        specialtyName, "smalfont.fnt", font::PRIMARY, -1, 1, 0, 8));
    return 1;
}

// ============================================================================
// CTownDlg
// ============================================================================

// E:\gamedcs\singleselectionpopups.cpp:298
VA(0x00575e10, 0x20)  // anchor-vtable CTownDlg ctor stores vtbl 0x641a90, calls ??0TDialogBox(0x12), ret 4, dc 0x12e690
CTownDlg::CTownDlg(unsigned char newGameMode)
    : CSingleSelPopup(0x12, newGameMode)
{
}

// E:\gamedcs\singleselectionpopups.cpp:299
VA_COMPGEN(0x00575e30, 0x21, SCALAR_DELETING_DTOR, CHeroDlg)  // vtbl 0x641a68/0x641a90/0x641ab8 slot0; ICF folds CTownDlg (dc 0x12f36c) + CTeamAlignmentDlg (dc 0x12f3a0) dtors, dc 0x12f338

// E:\gamedcs\singleselectionpopups.cpp:302
// Residual (87.28%): the 24-branch / 2-return sequence and ordered call
// multiset agree. The remaining frame/register class is one slot (our 0x14
// frame vs retail 0x18) plus a 273-slot visible distance. A bounded 1,785-form
// depth-1..3 AST tree over 25 clean mutations found no improvement.
VA(0x00575e60, 0x670)  // anchor-vtable CTownDlg::CreateWin inlines CSpriteWidget ctor (stores vtbl 0x641a00), ret 0xc (3 args), dc 0x12e708
unsigned char CTownDlg::CreateWin(CSprite* town, int frame, TTownType townType)
{
    if (!Setup(272, 140, 256, 320))
        return 0;

    Add(new textWidget(10, 26, width - 20, 36,
        gpGeneralText->GetText(81), "medfont.fnt", font::PRIMARY,
        -1, 1, 0, 8));
    Add(new CSpriteWidget((width - town->Width) / 2, 60, town, frame));
    Add(new textWidget(10, 95, width - 20, 18,
        gUnnamed6a74f4[townType], "smalfont.fnt", font::PRIMARY,
        -1, 1, 0, 8));
    Add(new textWidget(10, 127, width - 20, 36,
        gpGeneralText->GetText(80), "medfont.fnt", font::PRIMARY,
        -1, 1, 0, 8));

    int iconX = width / 2 - 68;
    int textX = iconX - 10;
    int creatureBase = townType * (2 * TOWN_DWELLING_COUNT);
    int slot;
    for (slot = 0; slot < 3; ++slot) {
        int creature = gTownDwellingCreatures[creatureBase + slot];
        iconWidget* portrait = new iconWidget(
            iconX, 159, 32, 32, slot, "cprsmall.def",
            0, 0, 0, 0, iconWidget::ICON_STYLE_PLAIN);
        Add(portrait);
        portrait->SetIconFrame(creature + 2);
        Add(new textWidget(textX, 193, 52, 32,
            akCreatureTypeTraits[creature].m_name, "tiny.fnt",
            font::PRIMARY, -1, 1, 0, 8));
        iconX += 52;
        textX += 52;
    }

    iconX = width / 2 - 88;
    textX = iconX - 10;
    for (slot = 3; slot < TOWN_DWELLING_COUNT; ++slot) {
        int creature = gTownDwellingCreatures[creatureBase + slot];
        iconWidget* portrait = new iconWidget(
            iconX, 235, 32, 32, slot, "cprsmall.def",
            0, 0, 0, 0, iconWidget::ICON_STYLE_PLAIN);
        Add(portrait);
        portrait->SetIconFrame(creature + 2);
        Add(new textWidget(textX, 267, 52, 32,
            akCreatureTypeTraits[creature].m_name, "tiny.fnt",
            font::PRIMARY, -1, 1, 0, 8));
        iconX += 52;
        textX += 52;
    }
    return 1;
}

// ============================================================================
// CTeamAlignmentDlg
// ============================================================================

// E:\gamedcs\singleselectionpopups.cpp:359 - the only dialog ctor with an
// fs:[0] EH frame: it calls GetTeams in the body, so the TDialogBox base must
// be unwound if GetTeams throws.
VA(0x005764d0, 0x53)  // anchor-vtable CTeamAlignmentDlg ctor stores vtbl 0x641ab8, calls ??0TDialogBox(0x12) + GetTeams (0x576930), fs:[0] EH frame, ret 4, dc 0x12eac8
CTeamAlignmentDlg::CTeamAlignmentDlg(unsigned char newGameMode)
    : CSingleSelPopup(0x12, newGameMode)
{
    GetTeams();
}

// E:\gamedcs\singleselectionpopups.cpp:365
// Residual (99.11%): register-visible distance 15 after identical first
// definitions. The bounded AST tree measured 1,965 compatible depth-1..3
// shapes; follow-up trees measured 32 local lifetimes, 32 xStart computations,
// and 20 CountNumPlayers inline-body forms. All clean variants were flat or
// worse. `volatile xStart` cuts the distance to 8 but is not source evidence,
// so it and synthetic TU-state noise remain deliberately excluded. Restoring
// the two preceding real CreateWin bodies (CHeroDlg and CTownDlg), both with
// retail-exact branch and call structure, leaves this score unchanged.
VA(0x00576540, 0x3e8)  // anchor-vtable, dc 0x12eb24
unsigned char CTeamAlignmentDlg::CreateWin()
{
    int xStart;
    char sTemp[256];
    int dialogHeight = ((numTeams * 50 + 56) / 64 + 1) * 64;
    if (!Setup(272, (600 - dialogHeight) / 2, 256, dialogHeight))
        return 0;

    Add(new textWidget(10, 20, width - 20, 36,
        gpGeneralText->GetText(658), "medfont.fnt", font::PRIMARY,
        -1, 1, 0, 8));

    for (int team = 0; team < numTeams; ++team) {
        int y = team * 50 + 56;
        sprintf(sTemp, gpGeneralText->GetText(657), team + 1);
        Add(new textWidget(10, y, width - 20, 18, sTemp,
            "smalfont.fnt", font::PRIMARY, -1, 1, 0, 8));

        int rowWidth = CountNumPlayers(team) * 18 - 3;
        xStart = (width - rowWidth) / 2;
        for (int player = 0; player < 8; ++player) {
            if (teamMasks[team] & (1 << player)) {
                iconWidget* flag = new iconWidget(
                    xStart, y + 20, 15, 20, -1, "ITGFLAGS.DEF",
                    0, 0, 0, 0, iconWidget::ICON_STYLE_PLAIN);
                flag->send_message(widget::WIDGET_SET_ICON_FRAME, player);
                Add(flag);
                xStart += 18;
            }
        }
    }
    return 1;
}

int CTeamAlignmentDlg::CountNumPlayers(int teamNbr)
{
    int count = 0;
    for (int player = 0; player < 8; ++player) {
        if (teamMasks[teamNbr] & (1 << player))
            ++count;
    }
    return count;
}

// E:\gamedcs\singleselectionpopups.cpp:424 - build the team-mask table off
// gpGame: for each present player (setup.playerPos >= 0) not yet grouped,
// open a new team seeded with that player's bit, then fold in every later
// present player sharing its mapHeader.teamInfo entry.
VA(0x00576930, 0xd1)  // anchor-callee called by CTeamAlignmentDlg ctor (0x5764d0), void/ret, touches team bss 0x2994e8, dc 0x12edd4
void CTeamAlignmentDlg::GetTeams()
{
    unsigned char assigned[8] = { 0 };
    int player;

    memset(teamMasks, 0, sizeof(teamMasks));
    numTeams = 0;
    for (player = 0; player < 8; ++player) {
        if (gpGame->setup.playerPos[player] < 0)
            continue;
        if (assigned[player])
            continue;
        assigned[player] = 1;
        teamMasks[numTeams] = 1 << player;
        for (int other = player + 1; other < 8; ++other) {
            if (gpGame->setup.playerPos[other] < 0)
                continue;
            if (gpGame->OnSameTeam(player, other)) {
                assigned[other] = 1;
                teamMasks[numTeams] |= 1 << other;
            }
        }
        ++numTeams;
    }
}

#if 0  // @carcass -- located, not reconstructed

// ============================================================================
// Unclaimed DC roster rows: inlined away, ICF-folded onto a claimed twin, or
// folded onto a shared empty outside this TU. No standalone retail body.
// ============================================================================

// --- CSingleSelPopup base: ctor/Add/ExitDialog inlined into the four derived
//     dialog ctors; the base is never directly instantiated (no own vtable). ---
// E:\gamedcs\singleselectionpopups.h:34
DC_ONLY(0x12eeac, 0x48)   // inlined (push 0x12 / ??0TDialogBox / set vtbl / [+0x54]=mode) into each dialog ctor
void CSingleSelPopup::CSingleSelPopup(int type, unsigned char newGameMode)
{
    // @stub
}
// E:\gamedcs\singleselectionpopups.h:39
DC_ONLY(0x12eef4, 0x34)   // inlined
void CSingleSelPopup::Add(widget* w)
{
    // @stub
}
// E:\gamedcs\singleselectionpopups.h:75
DC_ONLY(0x12efc0, 0x1C)   // inlined / thunk
int CSingleSelPopup::ExitDialog(message* msg)
{
    // @stub
}
// E:\gamedcs\singleselectionpopups.h:79
DC_ONLY(0x12efdc, 0x34)   // base never directly instantiated
void* CSingleSelPopup::scalar_deleting_destructor(unsigned __flags)
{
    // @stub
}

// --- CTeamAlignmentDlg::CountNumPlayers: inlined into GetTeams/CreateWin. ---
// E:\gamedcs\singleselectionpopups.cpp:411
DC_ONLY(0x12ed7c, 0x58)
int CTeamAlignmentDlg::CountNumPlayers(int teamNbr)
{
    // @stub
}

// --- Widget-subclass ctors: inlined into the CreateWin callers that build
//     them (each stores the class vtable inline; see the CreateWin claims). ---
// E:\gamedcs\singleselectionpopups.cpp:47
DC_ONLY(0x12f018, 0x94)   // inlined into CBonusDlg/CHeroDlg/CTownDlg CreateWin
void CSpriteWidget::CSpriteWidget(int xPos, int yPos, CSprite* pSprite, int frame)
{
    // @stub
}
// E:\gamedcs\singleselectionpopups.cpp:82
DC_ONLY(0x12f168, 0x78)   // inlined into CBonusDlg/CHeroDlg CreateWin
void CBitmapWidget::CBitmapWidget(int xPos, int yPos, Bitmap816* pImage)
{
    // @stub
}

// --- CBitmapWidget::Main: ICF-folded onto CSpriteWidget::Main (0x575a10). ---
// E:\gamedcs\singleselectionpopups.cpp:93
DC_ONLY(0x12f1e0, 0x18)   // folds -> 0x575a10 (return widget::Main)
int CBitmapWidget::Main(message* msg)
{
    // @stub
}

// --- Trivial zBufferDraw / Draw stubs: ICF-folded onto shared empties
//     0x404140 / 0x404df0 outside this TU (excluded class). ---
// E:\gamedcs\singleselectionpopups.h:120
DC_ONLY(0x12f010, 0x4)    // folds -> 0x404140
void CHotspotWidget::zBufferDraw()
{
    // @stub
}
// E:\gamedcs\singleselectionpopups.h:121
DC_ONLY(0x12f014, 0x4)    // folds -> 0x404df0
void CHotspotWidget::Draw()
{
    // @stub
}
// E:\gamedcs\singleselectionpopups.cpp:67
DC_ONLY(0x12f0c4, 0x4)    // folds -> 0x404140
void CSpriteWidget::zBufferDraw()
{
    // @stub
}
// E:\gamedcs\singleselectionpopups.cpp:99
DC_ONLY(0x12f1f8, 0x4)    // folds -> 0x404140
void CBitmapWidget::zBufferDraw()
{
    // @stub
}

#endif  // @carcass
