// soundmgr.cpp - E:\gamedcs\soundmgr.cpp (compiland soundmgr.obj)
// HAND-OWNED after admission - INITIALLY GENERATED by `python3 -m homm3.carve carcass`; prototypes are Dreamcast CodeView evidence.
// 25 functions in link order; 20 compiler-generated $-thunks omitted.
#include "terrain.h"
#include <va.h>
#include <windows.h>
#include <stdio.h>
#include <string.h>
#include "../vendor/miles-5.0e/include/Mss.h"
#include "soundmgr.h"
#include "sample.h"
#include "smackmgr.h"
#include "kbwin.h"
// SetMusicVolume's three cross-TU views: the combat manager's status
// (which selects combat music), the adventure manager's terrain field,
// and Random.
#include "advmgr.h"
#include "cmbtmgr.h"
#include "kb.h"
#include "misc.h"

// Number of live asynchronous sample waiters. WaitEndSampleThread increments
// and decrements this counter; Close gives them up to one second to drain.
// The role and storage are retail-byte-proven; no surviving name covers it.
// Before normalization: gSampleWorkerCount.
DATA(0x006a3254) int g_sampleWorkerCount;
DATA(0x0069fec0) MP3ResumePosition g_mp3ResumePositions[50];
DATA(0x006a3498) int g_mp3ResumePositionCount;
DATA(0x00684aa8) int g_soundSampleRate = 44100;
DATA(0x00684aac) int g_soundBitsPerSample = SOUND_BITS_PER_SAMPLE_16;
DATA(0x00684ab0) int g_soundOutputChannels = 2;
DATA(0x00684ae0) int g_soundMaxSamples = 14;
DATA(0x0069fe80) AILWaveFormat g_soundWaveFormat;
DATA(0x00698a28) int g_unk698a28;

// Provisional file-static, /Ob2-inlined at both of its call sites (no
// out-of-line body sits anywhere in the soundmgr span). The manager
// travels as a parameter because the two callers disagree about which
// one they mean: PauseSamples passes `this`, WaitSample passes the
// global. Name unattested.
// Before normalization (function): SamplePlaying.
static int samplePlaying(soundManager* mgr, ds_memsample* inSample)
{
    if (g_noSound)
        return 0;
    if (!mgr->m_ds)
        return 0;
    if (!inSample)
        return 0;
    EnterCriticalSection(&mgr->m_sectionSoundCall);
    int playing = AIL_sample_status(inSample) == AIL_SAMPLE_PLAYING;
    LeaveCriticalSection(&mgr->m_sectionSoundCall);
    return playing;
}

// E:\gamedcs\soundmgr.cpp:69
// LOCATED 2026-08-07, RECONSTRUCTED 2026-08-08. Location evidence:
//   * order-map: the DC roster runs SetMusicVolume < ConvertVolume <
//     soundManager::soundManager, and 0x5994b0 < 0x5996c0 < 0x599760
//     with 0x599760 already claimed as the ctor - the two carve rows
//     immediately below it are the only slots that fit.
//   * anchor-callee: AdjustMusicVolumes (0x59a1b0) ends in a tail
//     `jmp 0x5994b0` with `this` still in ecx and nothing pushed -
//     exactly a `void SetMusicVolume()` thiscall.
//   * body: it opens with `push 0x65; push 0x7f; call 0x5996c0`, i.e.
//     ConvertVolume(127, 101), and spends the result on
//     AIL_set_stream_volume - which is what SetMusicVolume does.
//   * size plausibility: 528/244 = 2.16x, inside the 0.3-2.5x band.
// The five "missing views" the 2026-08-07 note parked on are resolved:
// 0x6993d0 is gpCombatManager and 0x699268 is gpAdvManager (both were
// already modelled in their own headers), 0x66fedc is the literal
// "combat%02d", 0x678330 is the nine-byte terrain->music-id table, and
// the thread entry the vol==0 arm hands to _beginthread is 0x59a830 -
// the SAME ProcessMP3Stop entry StopMP3 uses - so that arm is StopMP3()
// /Ob2-inlined, not a distinct body. Both Enters go through
// gpSoundManager and both
// Leaves through `this`; that asymmetry is retail's and is transcribed
// verbatim. The two inner arms are ResumeStream() and StopMP3()
// inlined by /Ob2, written as CALLS per the ClearMemSample precedent.
// E:\gamedcs\soundmgr.cpp:69
VA(0x005994b0, 0x210)  // anchor-callee + order-map, dc 0x14b07c
void soundManager::setMusicVolume()
{
    if (g_noSound)
        return;

    int vol = convertVolume(127, VOLUME_TYPE_101);

    EnterCriticalSection(&g_soundManager->m_sectionMp3Change);
    EnterCriticalSection(&g_soundManager->m_sectionSoundCall);
    if (vol != 0) {
        if (g_mp3Stream) {
            if (m_mp3Playing)
                AIL_set_stream_volume(g_mp3Stream, vol);
            else
                resumeStream();
        } else if (g_combatManager->m_status) {
            // Before normalization (locals): cName.
            char name[100];

            sprintf(name, DATA_COMPGEN(0x0066fedc, combatMusicFormat,
                                        "combat%02d"),
                    random(1, 4));
            g_soundManager->startMP3(name, 0, 1);
        } else {
            int musicFileId = g_terrainMusicIds[g_advManager->m_lastTerrain];
            if (musicFileId >= 2 && musicFileId <= 10)
                startMP3(g_terrainMusic[musicFileId - 2], 0, 0);
        }
    } else {
        stopMP3();
    }
    LeaveCriticalSection(&m_sectionSoundCall);
    LeaveCriticalSection(&m_sectionMp3Change);
}

// E:\gamedcs\soundmgr.cpp:121
// LOCATED 2026-08-07 by the same order-map, and pinned independently
// twice over: MemorySample calls it `push 0x64; push [sample+0x2c]`
// with ecx = this and feeds the result to AIL_set_sample_volume, and
// SetMusicVolume calls it `push 0x65; push 0x7f` and feeds the result
// to AIL_set_stream_volume. `this` is never read - the body only
// selects between the two volume-setting globals.
// EXACT 2026-08-09. Retail duplicates the range check, scale and
// minimum-one clamp in the two arms, then joins before the negative and
// 127 clamps. That shared tail lengthens `result`'s lifetime, selects EDX
// as its carrier and enables the retail cross-jumps. The scoped
// auto_inline pin is separately load-bearing: the exact smaller body falls
// under this compile's /Ob2 budget, but retail calls it from SetMusicVolume,
// ModifySample and MemorySample rather than expanding it.
#pragma auto_inline(off)
// E:\gamedcs\soundmgr.cpp:121
// Before normalization (locals): iVolumeValue, iVolumeType.
VA(0x005996c0, 0x97)  // anchor-callee, dc 0x14b170
int soundManager::convertVolume(int volumeValue, int volumeType)
{
    int result = 0;
    if (volumeType == VOLUME_TYPE_101) {
        int setting = g_unk698760;
        if (setting >= 1 && setting <= 10) {
            result = (setting + 1) * volumeValue / 10;
            if (result < 1)
                result = 1;
        }
    } else {
        int setting = g_unk698764;
        if (setting >= 1 && setting <= 10) {
            result = (setting + 1) * volumeValue / 10;
            if (result < 1)
                result = 1;
        }
    }
    if (result < 0)
        result = 0;
    if (result > 127)
        result = 127;
    return result;
}
#pragma auto_inline(on)

// E:\gamedcs\soundmgr.cpp:165
// EXACT 2026-08-09: MP3Playing belongs in the member-initializer list.
// That construction-phase distinction makes VC6 emit its byte clear before
// the derived vptr store, exactly as retail does; writing the same assignment
// in the body schedules it after the vptr and plateaus at 99.0312%.
// E:\gamedcs\soundmgr.cpp:165
VA(0x00599760, 0x67)  // anchor-global, dc 0x14b1ec
soundManager::soundManager()
    : m_mp3Playing(0)
{
    m_status = 0;
    memset(g_ailDriverState, 0, sizeof(g_ailDriverState));
    memset(&m_samples, 0, sizeof(m_samples) + sizeof(m_sampleHandles) + sizeof(m_sampleNum));
    m_playSounds = 0;
    m_ds = 0;
    m_changeSounds = 0;
    InitializeCriticalSection(&m_sectionSoundCall);
    InitializeCriticalSection(&m_sectionMp3Change);
    InitializeCriticalSection(&m_sectionMp3NameChange);
}

// E:\gamedcs\soundmgr.cpp:322
// Vtable slot 0 and the unique Device:/Miles setup body independently pin
// this retail expansion of soundManager::Open. The DC body is much smaller
// because it uses ds_engine; Complete performs the PC waveOut preference
// fallback, Smacker/Bink binding and twelve-handle allocation here.
//
// Residual (84.53%): the best source has retail's 17 branches, one return,
// complete middleware call/data flow and 703-byte target extent. Two retry
// branches still target blocks in the opposite physical order, and C2 keeps
// `this` in EBX while retail keeps it in ESI (homed while ESI carries the
// channel count) and holds AIL_set_preference in EBX. Four grounded shapes
// were exhausted: structured retry plus a post-loop driver test (83.56%, one
// extra branch), explicit-goto retry (67.80%, wrong block order), the direct
// result-carrier loop below (84.53%), and an explicit long-lived
// set-preference pointer (same bytes). The remaining layout/RA choice is not
// source-addressable without distorting the proven retry semantics.
VA(0x005997d0, 0x2BF)  // vtable slot + Device: string, dc 0x14b240
int soundManager::open(int newPriority)
{
    m_currentTerrainMusic = 0xff;
    memset(&m_samples, 0,
           sizeof(m_samples) + sizeof(m_sampleHandles) + sizeof(m_sampleNum));

    if (!g_noSound) {
        AIL_startup();
        if (!g_unk698a28 && !m_ds) {
            typedef int (__stdcall* SetPreferenceProc)(int, int);
            SetPreferenceProc setPreference = AIL_set_preference;
            setPreference(15, 0);
            setPreference(33, 1);
            setPreference(34, 100);

            AILDigitalDriver* driver;
            AILDigitalDriver* result;
            for (;;) {
                if (g_soundSampleRate < 11025) {
                    result = 0;
                    break;
                }

                g_soundWaveFormat.m_formatTag = 1;
                g_soundWaveFormat.m_channels =
                    static_cast<unsigned short>(g_soundOutputChannels);
                g_soundWaveFormat.m_samplesPerSec = g_soundSampleRate;
                g_soundWaveFormat.m_avgBytesPerSec =
                    (g_soundBitsPerSample / 8) * g_soundOutputChannels
                    * g_soundSampleRate;
                g_soundWaveFormat.m_blockAlign = static_cast<unsigned short>(
                    (g_soundBitsPerSample / 8) * g_soundOutputChannels);
                g_soundWaveFormat.m_bitsPerSample =
                    static_cast<unsigned short>(g_soundBitsPerSample);

                AIL_HWND();
                int openResult = AIL_waveOutOpen(
                    &driver, 0, -1, &g_soundWaveFormat);
                if (!openResult) {
                    char description[128];
                    strcpy(description, DATA_COMPGEN(
                        0x00684b28, soundDevicePrefix, "Device: "));
                    AIL_digital_configuration(
                        driver, 0, 0, description + strlen(description));
                    if (AIL_get_preference(15)) {
                        result = driver;
                        break;
                    }
                    if (!strstr(description, DATA_COMPGEN(
                            0x00684b1c, emulatedDeviceMarker,
                            "Emulated"))) {
                        result = driver;
                        break;
                    }
                    AIL_waveOutClose(driver);
                    setPreference(15, 1);
                } else if (AIL_get_preference(15)) {
                    g_soundSampleRate /= 2;
                    if (g_soundSampleRate >= 11025)
                        continue;
                    if (g_soundBitsPerSample == SOUND_BITS_PER_SAMPLE_8) {
                        g_soundBitsPerSample = SOUND_BITS_PER_SAMPLE_8;
                        g_soundSampleRate = 22050;
                        continue;
                    }
                    result = 0;
                    break;
                }
                setPreference(15, 1);
            }
            m_ds = result;
        }

        if (!m_ds) {
            g_unk698764 = 0;
        } else {
            if (g_soundManager->m_ds->lppdsb) {
                AILPrimaryBuffer* buffer =
                    static_cast<AILPrimaryBuffer*>(g_soundManager->m_ds->lppdsb);
                buffer->m_vtable->m_setVolume(buffer, 0);
            }
            SmackSoundUseMSS(g_soundManager->m_ds);
            BinkSetSoundSystem(BinkOpenMiles, g_soundManager->m_ds);
        }
        m_playSounds = 1;

        if (!g_noSound && m_ds) {
            int count;
            for (count = 0; count < 12; ++count) {
                m_sampleHandles[count] = AIL_allocate_sample_handle(m_ds);
                if (!m_sampleHandles[count])
                    break;
            }
            m_sampleNum = count;
            g_soundMaxSamples = count;
        }
        m_samples = 1;
    }

    m_id = 16;
    m_priority = -1;
    m_status = STATUS_ACTIVE;
    strcpy(m_mgrName, DATA_COMPGEN(
        0x00684b0c, soundManagerName, "soundManager"));
    return 0;
}

// E:\gamedcs\soundmgr.cpp:410
VA(0x00599a90, 0xF1)  // vtable slot + compiland order, dc 0x14b270
void soundManager::close()
{
    if (m_status == STATUS_ACTIVE) {
        g_soundManager->m_playSounds = 1;
        g_unk691209 = 0;
        videoShutDown();

        if (!g_noSound) {
            for (int waits = 0; waits < 20; ++waits) {
                if (g_sampleWorkerCount <= 0)
                    break;
                Sleep(50);
            }

            EnterCriticalSection(&m_sectionMp3Change);
            EnterCriticalSection(&m_sectionSoundCall);
            if (g_mp3Stream) {
                AIL_pause_stream(g_mp3Stream, 1);
                AIL_close_stream(g_mp3Stream);
                g_mp3Stream = 0;
            }
            for (int i = 0; i < m_sampleNum; ++i)
                AIL_end_sample(m_sampleHandles[i]);
            m_samples = 0;
            AIL_serve();
            Sleep(1);
            AIL_shutdown();
            LeaveCriticalSection(&m_sectionSoundCall);
            LeaveCriticalSection(&m_sectionMp3Change);
        }

        m_status = 0;
        g_noSound = 1;
    }
}

// Retail-only pair (no DC lines; the WinCE build has no app-switch
// handling): AppWndProc's WM_ACTIVATEAPP calls PauseSamples on
// deactivate and ResumeSamples on activate around ResumeStream. Both
// early-out on gbNoSound and walk sampleHandles under
// section_sound_call. Names provisional pending the real source
// names; layout slots them between Main and StopAllSamples.

VA(0x00599b90, 0xAB)  // anchor-callee, retail-only
void soundManager::resumeSamples()
{
    if (g_noSound)
        return;
    if (!m_ds)
        return;
    if (m_playSounds == 0 && !g_unk691209)
        return;
    EnterCriticalSection(&m_sectionSoundCall);
    for (int i = 0; i < m_sampleNum; i++)
        if (g_sampleWasPlaying[i] && AIL_sample_status(m_sampleHandles[i]) == AIL_SAMPLE_RESUMABLE)
            AIL_resume_sample(m_sampleHandles[i]);
    LeaveCriticalSection(&m_sectionSoundCall);
    memset(g_sampleWasPlaying, 0, sizeof(g_sampleWasPlaying));
}

VA(0x00599c40, 0x14B)  // anchor-callee, retail-only
void soundManager::pauseSamples()
{
    if (g_noSound)
        return;
    if (!m_ds)
        return;
    if (m_playSounds == 0 && !g_unk691209)
        return;
    EnterCriticalSection(&m_sectionSoundCall);
    for (int i = 0; i < m_sampleNum; i++) {
        g_sampleWasPlaying[i] = samplePlaying(this, m_sampleHandles[i]);
        AIL_stop_sample(m_sampleHandles[i]);
    }
    LeaveCriticalSection(&m_sectionSoundCall);
    stopMP3();
}

// E:\gamedcs\soundmgr.cpp:526
// Before normalization (locals): bStopMusicToo.
VA(0x00599d90, 0xEA)  // anchor-global, dc 0x14b2a8
void soundManager::stopAllSamples(int stopMusicToo)
{
    if (g_noSound)
        return;
    if (!m_ds)
        return;
    if (m_playSounds == 0 && !g_unk691209)
        return;
    memset(g_sampleWasPlaying, 0, sizeof(g_sampleWasPlaying));
    EnterCriticalSection(&m_sectionSoundCall);
    for (int i = 0; i < m_sampleNum; i++)
        AIL_end_sample(m_sampleHandles[i]);
    LeaveCriticalSection(&m_sectionSoundCall);
    if (stopMusicToo)
        stopMP3();
}

// E:\gamedcs\soundmgr.cpp:556
// EXACT since the 2026-08-07 layout correction: the old 97.4%/99.96%
// residual was the `ds` member sitting at 0x40 instead of 0x3c, not a
// register choice.
// E:\gamedcs\soundmgr.cpp:556
VA(0x00599e80, 0x3D)  // anchor-global, dc 0x14b2c0
void soundManager::stopSample(ds_memsample* inSample)
{
    if (g_noSound)
        return;
    if (!m_ds)
        return;
    if (!inSample)
        return;
    EnterCriticalSection(&m_sectionSoundCall);
    AIL_end_sample(inSample);
    LeaveCriticalSection(&m_sectionSoundCall);
}

// E:\gamedcs\soundmgr.cpp:572
VA(0x00599ec0, 0x7F)  // dc-bracket forced, dc 0x14b2d8
void soundManager::waitSample(ds_memsample* sample, int time)
{
    if (time < 0)
        time = 4000;
    unsigned long deadline = GameTime::get() + time;
    while (samplePlaying(g_soundManager, sample)) {
        if (static_cast<long>(GameTime::get() - deadline) >= 0)
            return;
        process1WindowsMessage();
        pollSound();
    }
}

// E:\gamedcs\soundmgr.cpp:597
// Before normalization (locals): sFunction.
VA(0x00599f40, 0xE1)  // anchor-global, dc 0x14b37c
void soundManager::modifySample(ds_memsample* inSample, short functionId, long value)
{
    if (g_noSound)
        return;
    if (!m_ds)
        return;
    if (m_playSounds == 0 && !g_unk691209)
        return;
    if (!m_samples)
        return;
    int found = -1;
    EnterCriticalSection(&m_sectionSoundCall);
    for (int i = 0; i < m_sampleNum; i++) {
        if (inSample == m_sampleHandles[i])
            found = i;
        switch (functionId) {
        case SAMPLE_MODIFY_1:
        case SAMPLE_MODIFY_100:
            AIL_set_sample_volume(inSample, convertVolume(value, 100));
            if (found >= 0)
                g_ailDriverState[found] = static_cast<short>(value);
            break;
        case SAMPLE_MODIFY_5:
            AIL_start_sample(inSample);
            break;
        }
    }
    LeaveCriticalSection(&m_sectionSoundCall);
}

// PC-only query used by the remote chat sample path.  Operation 1 returns
// the Miles volume and operation 4 reduces the status to the playing bit;
// every other operation retains the initialized zero result.
VA(0x0059a030, 0x87)  // remote call sites + Miles imports, retail-only
int soundManager::getSampleInfo(ds_memsample* inSample, short operation)
{
    if (g_noSound)
        return 0;
    if (!m_ds)
        return 0;
    if (!inSample)
        return 0;

    int result = 0;
    EnterCriticalSection(&m_sectionSoundCall);
    switch (operation) {
    case SAMPLE_INFO_VOLUME:
        result = AIL_sample_volume(inSample);
        break;
    case SAMPLE_INFO_PLAYING:
        result = AIL_sample_status(inSample) == AIL_SAMPLE_PLAYING;
        break;
    }
    LeaveCriticalSection(&m_sectionSoundCall);
    return result;
}

// E:\gamedcs\soundmgr.cpp:691
VA(0x0059a0c0, 0xEB)  // anchor-global, dc 0x14b42c
void soundManager::adjustSoundVolumes()
{
    if (g_noSound)
        return;
    if (!m_ds)
        return;
    if (m_playSounds == 0 && !g_unk691209)
        return;
    // Slot 0 is skipped: retail starts the walk at &sampleHandles[1]
    // and &gAilDriverState[1] (`lea eax,[esi+0x48]`, bss_29fea2).
    for (int i = 1; i < m_sampleNum; i++) {
        // Named once ahead of the branch: retail hoists the slot load
        // above the gUnk698764 test into a callee-saved register.
        ds_memsample* handle = m_sampleHandles[i];
        // Positive arm first: retail falls through into the
        // SamplePlaying test and sinks the `push 0; push 1` arm below
        // it, which is the layout the if/else-if spelling inverts.
        if (g_unk698764) {
            if (samplePlaying(this, handle))
                modifySample(handle, SAMPLE_MODIFY_100, g_ailDriverState[i]);
        } else {
            modifySample(handle, SAMPLE_MODIFY_1, 0);
        }
    }
}

// E:\gamedcs\soundmgr.cpp:733
VA(0x0059a1b0, 0x22)  // anchor-global, dc 0x14b4d4
void soundManager::adjustMusicVolumes()
{
    if (g_noSound)
        return;
    if (m_playSounds == 0 && !g_unk691209)
        return;
    setMusicVolume();
}

// E:\gamedcs\soundmgr.cpp:751
VA(0x0059a1e0, 0x25)  // anchor-global, dc 0x14b500
void soundManager::switchAmbientMusic(int newMusicFileId)
{
    if (newMusicFileId >= 2 && newMusicFileId <= 10)
        startMP3(g_terrainMusic[newMusicFileId - 2], 0, 0);
}

// E:\gamedcs\soundmgr.cpp:759
// DREAMCAST SOURCE SHAPE (dc 0x14b528): raw NB11 records the recovered `sPtr`
// parameter and no S_REGREL32 locals after S_ENDARG, plus 24 breakpoint rows,
// 27 lexical scopes and 25 SH4 blocks. Line 817 emits both channel-wrap stores
// as one statement (`slot = range->next = range->first`), and line 821 groups
// Channel with the named StopSample helper. Both byte-flat restorations are
// literal below as retained Dreamcast evidence, together
// with the shared StopSample / ConvertVolume / volume / start / handle-return
// order. The declaration now uses the recovered `sPtr` name too.
//
// Two DC shapes do not transfer to Complete. Its four separate early-return
// scopes become seven PC admission tests; spelling those as separate returns
// scores 66.07407%, and separate guards targeting one shared label score
// 93.88889%. Retail's one shared failure tail therefore keeps the combined
// condition. DC's single SetVolume statement follows its byte parameter;
// Complete's int-taking Miles adapter requires two source call arms to emit
// retail's per-arm push before the cross-jumped call. A shared int result and
// a ternary each score 98.51234% and are rejected platform spellings.
//
// EXACT 2026-08-30: the PC-only tail is not a provisional file-static wrapper.
// Dreamcast proves the `soundManager::service_sounds` member name in
// SoundMgr.h, and Complete retail keeps its non-empty 81-byte body at 0x59a7d0.
// Calling that member on gpSoundManager expands to the same five-block tail
// here but also restores the member-call C1 state: retail's EAX/EDX/ECX
// scratch choices replace the wrapper's EDX/ECX/EDX rotation. MemorySample
// rises 99.78395% -> exact while the exact launch_sample sibling and the
// out-of-line member remain exact. The asymmetric gate rejects flattening the
// recovered helper boundary back into a duplicate wrapper.
// E:\gamedcs\soundmgr.cpp:759
// Before normalization (locals): sPtr.
VA(0x0059a210, 0x1DB)  // anchor-global, dc 0x14b528
ds_memsample* soundManager::memorySample(sample* samplePointer)
{
    // Retail sinks all seven admission guards into ONE shared
    // `xor eax,eax` exit, so they have to be one condition here: the
    // split-if spelling duplicates the epilogue seven times (the
    // adjacent-early-out lever, running the other way round for once).
    if (!g_noSound && m_ds && (m_playSounds || g_unk691209) && g_unk698764 && samplePointer
        && m_samples && samplePointer->m_memSample.m_memVolume) {
        SoundChannelRange* range = &g_soundChannels[samplePointer->m_memSample.m_memCindex];
        EnterCriticalSection(&m_sectionSoundCall);
        int slot = range->m_first;
        while (slot < range->m_last) {
            if (AIL_sample_status(m_sampleHandles[slot]) == AIL_SAMPLE_SLOT_FREE)
                break;
            slot++;
        }
        if (slot == range->m_last) {
            if (samplePointer->m_memSample.m_memCindex == SOUND_CHANNEL_COUNT) {
                LeaveCriticalSection(&m_sectionSoundCall);
                return 0;
            }
            slot = range->m_next++;
            if (range->m_next >= range->m_last) {
                slot = range->m_next = range->m_first;
            }
            // Direct, not expanded: retail loads this slot once into a
            // callee-saved register and the DC line group retains the
            // StopSample helper boundary around that selected channel.
            stopSample(m_sampleHandles[slot]);
        }

        ds_memsample* handle = m_sampleHandles[slot];
        g_ailDriverState[slot] = static_cast<short>(samplePointer->m_memSample.m_memVolume);
        AIL_init_sample(handle);
        AIL_set_sample_file(handle, samplePointer->m_memSample.m_data, 0);
        AIL_set_sample_loop_count(handle, samplePointer->m_memSample.m_memLooping);
        if (g_unk698764)
            AIL_set_sample_volume(handle, convertVolume(samplePointer->m_memSample.m_memVolume, 100));
        else
            AIL_set_sample_volume(handle, 0);
        AIL_start_sample(handle);
        samplePointer->m_memSample.m_memSampleHandle = handle;
        LeaveCriticalSection(&m_sectionSoundCall);

        g_soundManager->serviceSounds();
        return handle;
    }
    return 0;
}

// E:\gamedcs\soundmgr.cpp:869
VA(0x0059a3f0, 0x15)  // anchor-global, dc 0x14b644
int soundManager::musicPlaying()
{
    if (g_noSound)
        return 0;
    return m_mp3Playing;
}

// E:\gamedcs\soundmgr.cpp:877
VA(0x0059a410, 0x5C)  // anchor-global, dc 0x14b65c
void clearMemSample(SAMPLE2 sample2)
{
    if (!sample2.m_resSample)
        return;
    if (g_shutDownDone)
        return;
    // This is soundManager::StopSample on the global, inlined by /Ob2 -
    // guard trio, section, AIL_end_sample, section, store for store.
    g_soundManager->stopSample(sample2.m_playSample);
    sample2.m_resSample->dispose();
}

// E:\gamedcs\soundmgr.cpp:894
// Before normalization (locals): cSampleName.
VA(0x0059a470, 0x43)  // anchor-global, dc 0x14b698
SAMPLE2 loadPlaySample(const char* sampleName)
{
    if (!sampleName)
        return g_nullSample2;
    sample* loaded = ResourceManager::getSample(sampleName);
    if (!loaded)
        return g_nullSample2;
    loaded->m_memSample.m_memCindex = 2;
    SAMPLE2 played;
    played.m_resSample = loaded;
    played.m_playSample = g_soundManager->memorySample(loaded);
    return played;
}

// E:\gamedcs\soundmgr.cpp:911
// Before normalization (locals): iMilliWait.
VA(0x0059a4c0, 0xCE)  // anchor-global, dc 0x14b6ec
void waitEndSample(SAMPLE2 sample2, int milliWait)
{
    if (milliWait < 0)
        milliWait = 4000;
    unsigned long deadline = GameTime::get() + milliWait;
    // The handle test is loop-invariant and retail hoists it: one test
    // ahead of the loop, none inside.
    while (sample2.m_playSample && samplePlaying(g_soundManager, sample2.m_playSample)) {
        if (static_cast<long>(GameTime::get() - deadline) >= 0)
            break;
        process1WindowsMessage();
        pollSound();
    }
    clearMemSample(sample2);
}


// E:\gamedcs\soundmgr.cpp:976
// Before normalization (locals): sample_name, max_time.
VA(0x0059a590, 0x112)  // anchor-global, dc 0x14b780
void launchSample(const char* sampleName, int maxTime, int channel)
{
    if (g_noSound)
        return;
    if (!g_soundManager->m_ds)
        return;
    if (g_soundManager->m_playSounds == 0 && !g_unk691209)
        return;
    if (!g_unk698764)
        return;
    if (!sampleName)
        return;
    if (maxTime < 0)
        maxTime = 10000;
    LaunchedSample* launched = new LaunchedSample;
    launched->m_sample2.m_resSample = ResourceManager::getSample(sampleName);
    launched->m_maxTime = maxTime;
    if (!launched->m_sample2.m_resSample) {
        delete launched;
        return;
    }
    launched->m_sample2.m_resSample->m_memSample.m_memCindex = channel;
    launched->m_sample2.m_playSample =
        g_soundManager->memorySample(launched->m_sample2.m_resSample);
    g_soundManager->serviceSounds();
    if (!g_shutDownDone)
        _beginthread(waitEndSampleThread, 0, launched);
}

// The address taken by launch_sample is a cdecl thread entry.  Its packet
// fields, 100-ms elapsed-time loop, live-waiter accounting, and final
// ClearMemSample expansion are all independently visible in retail.
// E:\gamedcs\soundmgr.cpp:911/976 vicinity; PC worker has no DC row.
VA(0x0059a6b0, 0x113)  // address-taken + packet layout, retail-only
void __cdecl waitEndSampleThread(void* arglist)
{
    ++g_sampleWorkerCount;
    LaunchedSample* launched = static_cast<LaunchedSample*>(arglist);
    int elapsed = 0;
    if (launched->m_sample2.m_playSample && !g_shutDownDone) {
        while (samplePlaying(g_soundManager, launched->m_sample2.m_playSample)
               && elapsed < launched->m_maxTime) {
            Sleep(100);
            elapsed += 100;
            if (g_shutDownDone)
                break;
        }
    }
    clearMemSample(launched->m_sample2);
    delete launched;
    --g_sampleWorkerCount;
    _endthread();
}

// Dreamcast records this named SoundMgr.h member as an empty WinCE service in
// kb.obj. Complete gives it the non-empty PC Miles body below: retail keeps an
// exact out-of-line copy and exact /Ob2 expansions in MemorySample and
// launch_sample. Those three copies jointly prove the shared member boundary.
VA(0x0059a7d0, 0x51)  // hd-crossbuild; DC SoundMgr.h:140, dc 0xe6ef4
void soundManager::serviceSounds()
{
    EnterCriticalSection(&m_sectionSoundCall);
    AIL_serve();
    if (g_mp3Stream && g_soundManager->m_mp3Playing && !g_shutDownDone)
        AIL_service_stream(g_mp3Stream, 1);
    Sleep(1);
    LeaveCriticalSection(&m_sectionSoundCall);
}

// E:\gamedcs\soundmgr.cpp:1068
// Retail has five address-taken references to this 16-byte-aligned entry.
// Its load/call/tail-jump body and the DC callgraph independently settle the
// cdecl thread signature and ThreadStopMP3 callee.
VA(0x0059a830, 0x10)  // address-taken + dc 0x14b7e0 xref edge
void __cdecl processMP3Stop(void* nothing)
{
    g_soundManager->threadStopMP3();
    _endthread();
}

// E:\gamedcs\soundmgr.cpp:1162
// ResumeStream and StartMP3 both hand this entry to _beginthread; the body
// reciprocally calls ConvertVolume and ThreadStopMP3 and uses the same
// position cache as ThreadStopMP3. Those independent edges settle the PC
// worker despite its much larger Miles implementation than Dreamcast's.
VA(0x0059a840, 0x3BB)  // three address-taken xrefs + dc 0x14b7f4 role
void __cdecl processStopAndPlayMP3(void* arglist)
{
    EnterCriticalSection(&g_soundManager->m_sectionMp3Change);
    int volume = g_soundManager->convertVolume(127, VOLUME_TYPE_101);
    EnterCriticalSection(&g_soundManager->m_sectionMp3NameChange);
    if (!g_mp3NamePlaying[0]) {
        LeaveCriticalSection(&g_soundManager->m_sectionMp3NameChange);
        LeaveCriticalSection(&g_soundManager->m_sectionMp3Change);
        _endthread();
        return;
    }
    LeaveCriticalSection(&g_soundManager->m_sectionMp3NameChange);

    g_soundManager->threadStopMP3();
    EnterCriticalSection(&g_soundManager->m_sectionSoundCall);
    if (!g_shutDownDone && g_mp3Stream)
        AIL_close_stream(g_mp3Stream);
    g_mp3Stream = 0;
    LeaveCriticalSection(&g_soundManager->m_sectionSoundCall);

    EnterCriticalSection(&g_soundManager->m_sectionMp3NameChange);
    if (!g_mp3NamePlaying[0]) {
        LeaveCriticalSection(&g_soundManager->m_sectionMp3NameChange);
        LeaveCriticalSection(&g_soundManager->m_sectionMp3Change);
        _endthread();
        return;
    }

    strcpy(g_mp3Name, g_mp3NamePlaying);
    g_unk69fe90 = g_unk69fe9c;
    char filename[100];
    sprintf(filename, DATA_COMPGEN(
        0x00684b34, mp3PathFormat, "mp3\\%s.mp3"), g_mp3NamePlaying);
    g_mp3NamePlaying[0] = 0;
    LeaveCriticalSection(&g_soundManager->m_sectionMp3NameChange);

    if (volume && !g_shutDownDone) {
        g_soundManager->m_mp3Playing = 1;
        EnterCriticalSection(&g_soundManager->m_sectionSoundCall);
        g_mp3Stream = AIL_open_stream(g_soundManager->m_ds, filename, 0);
        if (g_mp3Stream && !g_shutDownDone && g_foregroundApp) {
            AIL_set_stream_volume(
                g_mp3Stream, g_unk69fe90 ? volume : 0);
            AIL_set_stream_loop_count(g_mp3Stream, g_unk69fe90);
            AIL_service_stream(g_mp3Stream, 1);

            if (!g_unk69fe90) {
                EnterCriticalSection(&g_soundManager->m_sectionMp3Change);
                EnterCriticalSection(&g_soundManager->m_sectionSoundCall);
                for (int slot = 0; slot < g_mp3ResumePositionCount; ++slot) {
                    if (strcmp(g_mp3ResumePositions[slot].m_name, g_mp3Name) == 0) {
                        AIL_set_stream_position(
                            g_mp3Stream, g_mp3ResumePositions[slot].m_position);
                        break;
                    }
                }
                LeaveCriticalSection(&g_soundManager->m_sectionSoundCall);
                LeaveCriticalSection(&g_soundManager->m_sectionMp3Change);
            }

            if (!g_shutDownDone)
                AIL_start_stream(g_mp3Stream);

            if (!g_unk69fe90) {
                float currentVolume = 0.0f;
                for (int step = 1; step < 10; ++step) {
                    if (g_shutDownDone)
                        break;
                    currentVolume += static_cast<float>(volume) / 10.0f;
                    AIL_set_stream_volume(
                        g_mp3Stream, static_cast<int>(currentVolume));
                    LeaveCriticalSection(&g_soundManager->m_sectionSoundCall);
                    Sleep(100);
                    EnterCriticalSection(&g_soundManager->m_sectionSoundCall);
                }
                if (!g_shutDownDone)
                    AIL_set_stream_volume(g_mp3Stream, volume);
            }
        }
        LeaveCriticalSection(&g_soundManager->m_sectionSoundCall);
    }
    LeaveCriticalSection(&g_soundManager->m_sectionMp3Change);
    _endthread();
}

// E:\gamedcs\soundmgr.cpp:1288
VA(0x0059ac00, 0xA9)  // anchor-global, dc 0x14b8e8
void soundManager::resumeStream()
{
    EnterCriticalSection(&m_sectionMp3NameChange);
    if (g_mp3Name[0] == 0 || g_shutDownDone) {
        LeaveCriticalSection(&m_sectionMp3NameChange);
        return;
    }
    strcpy(g_mp3NamePlaying, g_mp3Name);
    g_unk69fe9c = g_unk69fe90;
    LeaveCriticalSection(&m_sectionMp3NameChange);
    EnterCriticalSection(&m_sectionSoundCall);
    AIL_serve();
    LeaveCriticalSection(&m_sectionSoundCall);
    if (g_shutDownDone)
        return;
    _beginthread(processStopAndPlayMP3, 0, 0);
}

// E:\gamedcs\soundmgr.cpp:1343
// DECODE STARTED 2026-08-07 (head to +0x178), FINISHED 2026-08-08.
// Both name compares are VC6's INLINE strcmp intrinsic (the
// two-bytes-per-iteration loop closing with `sbb eax,eax; sbb eax,-1`),
// so they are written as plain strcmp calls. The gate at +0x81 is
// gUnk698760 - a DIFFERENT global from MemorySample's gUnk698764, they
// must not be merged. Three /Ob2 inlines carry the body and are written
// as CALLS (the ClearMemSample precedent): StopAllSamples(1) in the
// name-unchanged arm, StopAllSamples(0) in the +0x26f arm, and
// ResumeStream() as the whole 0x1d5..0x25a tail. VC6 tail-merges the
// two arms' closing `if (!bShutDownDone) _beginthread(...)` blocks -
// the +0x26f arm's `jmp` back into the ResumeStream inline's tail is
// that merge, not a shared source statement.
// The name-match early-out is spelled as the NEGATED outer `if` with the
// Leave textually last, NOT as `if (== 0) { Leave; return; }` and not as
// a `goto`: those two both make our CL duplicate the epilogue in place
// (90.9%), while retail sinks the Leave to one block that falls into the
// single shared epilogue the four head guards already jump to. Writing
// it this way closed the epilogue duplication AND flipped the tail-merge
// to retail's direction in one step - both deltas were the same
// placement decision.
// E:\gamedcs\soundmgr.cpp:1343
// Before normalization (locals): bStopSamples.
VA(0x0059acb0, 0x355)  // anchor-global, dc 0x14b924
void soundManager::startMP3(const char* filename, int loopCount, unsigned char stopSamples)
{
    if (g_noSound)
        return;
    if (!m_ds)
        return;
    if (m_playSounds == 0 && !g_unk691209)
        return;
    if (!g_unk698760)
        return;

    EnterCriticalSection(&m_sectionMp3NameChange);
    if (strcmp(filename, g_mp3NamePlaying) != 0) {
        if (strcmp(filename, g_mp3Name) == 0) {
            LeaveCriticalSection(&m_sectionMp3NameChange);
            EnterCriticalSection(&m_sectionSoundCall);
            int streamStatus = AIL_stream_status(g_mp3Stream);
            LeaveCriticalSection(&m_sectionSoundCall);
            if (streamStatus == AIL_STREAM_PLAYING)
                return;
            if (stopSamples)
                stopAllSamples(1);
            resumeStream();
        } else {
            strcpy(g_mp3NamePlaying, filename);
            g_unk69fe9c = loopCount;
            LeaveCriticalSection(&m_sectionMp3NameChange);
            if (stopSamples)
                stopAllSamples(0);
            EnterCriticalSection(&m_sectionSoundCall);
            AIL_serve();
            Sleep(1);
            LeaveCriticalSection(&m_sectionSoundCall);
            if (g_shutDownDone)
                return;
            _beginthread(processStopAndPlayMP3, 0, 0);
        }
        return;
    }
    LeaveCriticalSection(&m_sectionMp3NameChange);
}

// E:\gamedcs\soundmgr.cpp:1413
VA(0x0059b010, 0x6A)  // anchor-global, dc 0x14b974
void soundManager::stopMP3()
{
    EnterCriticalSection(&m_sectionMp3Change);
    EnterCriticalSection(&m_sectionSoundCall);
    if (g_mp3Stream && AIL_stream_status(g_mp3Stream) == AIL_STREAM_PLAYING) {
        AIL_serve();
        Sleep(5);
        if (!g_shutDownDone)
            _beginthread(processMP3Stop, 0, 0);
    }
    LeaveCriticalSection(&m_sectionSoundCall);
    LeaveCriticalSection(&m_sectionMp3Change);
}

// E:\gamedcs\soundmgr.cpp:1434
// ProcessMP3Stop's exact call edge pins this member to the 533-byte body at
// 0x59b080. Retail saves the current stream position under its pending name,
// fades the active volume in nine fixed steps while releasing the Miles lock
// for each sleep, pauses the stream, and clears MP3Playing.
VA(0x0059b080, 0x215)  // ProcessMP3Stop sole direct caller, dc 0x14b984
void soundManager::threadStopMP3()
{
    EnterCriticalSection(&m_sectionMp3Change);
    EnterCriticalSection(&m_sectionSoundCall);
    if (g_mp3Stream && m_mp3Playing && !g_shutDownDone) {
        EnterCriticalSection(&g_soundManager->m_sectionMp3NameChange);
        EnterCriticalSection(&g_soundManager->m_sectionSoundCall);

        int slot;
        for (slot = 0; slot < g_mp3ResumePositionCount; ++slot) {
            if (strcmp(g_mp3ResumePositions[slot].m_name, g_mp3Name) == 0) {
                g_mp3ResumePositions[slot].m_position =
                    AIL_stream_position(g_mp3Stream);
                break;
            }
        }
        if (slot == g_mp3ResumePositionCount) {
            strcpy(g_mp3ResumePositions[slot].m_name, g_mp3Name);
            g_mp3ResumePositions[slot].m_position =
                AIL_stream_position(g_mp3Stream);
            ++g_mp3ResumePositionCount;
        }

        LeaveCriticalSection(&g_soundManager->m_sectionSoundCall);
        LeaveCriticalSection(&g_soundManager->m_sectionMp3NameChange);

        float originalVolume =
            static_cast<float>(AIL_stream_volume(g_mp3Stream));
        if (originalVolume != 0.0f) {
            float currentVolume = originalVolume;
            for (int step = 1; step < 10; ++step) {
                if (g_shutDownDone)
                    break;
                currentVolume -= originalVolume / 10.0f;
                AIL_set_stream_volume(
                    g_mp3Stream, static_cast<int>(currentVolume));
                LeaveCriticalSection(&m_sectionSoundCall);
                Sleep(100);
                EnterCriticalSection(&m_sectionSoundCall);
            }
        }
        if (!g_shutDownDone)
            AIL_pause_stream(g_mp3Stream, 1);
    }
    m_mp3Playing = 0;
    LeaveCriticalSection(&m_sectionSoundCall);
    LeaveCriticalSection(&m_sectionMp3Change);
}
