// strip.cpp - E:\gamedcs\strip.cpp (compiland strip.obj)
// HAND-OWNED after admission - INITIALLY GENERATED by `python3 -m homm3.carve carcass`; prototypes are Dreamcast CodeView evidence.
// 8 functions in link order; 20 compiler-generated $-thunks omitted.
#include <va.h>
// #include "strip.h"

// E:\gamedcs\strip.cpp:53
DC_ONLY(0x158880, 0x62)
void strip::strip(int inX, int inY, int inPos, int newIcons, int newIconFrame, long new_owner, hero* new_hero, armyGroup* groupToDraw, int firstId, unsigned char update, heroWindow* inWin)
{
    // @stub
}

// E:\gamedcs\strip.cpp:70
DC_ONLY(0x1588e4, 0x4)
void strip::~strip()
{
    // @stub
}

// E:\gamedcs\strip.cpp:75
DC_ONLY(0x1588e8, 0x28)
void strip::Draw(TCreatureType divide_creature)
{
    // @stub
}

// E:\gamedcs\strip.cpp:81
DC_ONLY(0x158910, 0xF0)
void strip::DrawIcons(unsigned char update, TCreatureType divide_creature)
{
    // @stub
}

// E:\gamedcs\strip.cpp:124
DC_ONLY(0x158a00, 0x80)
void strip::DrawNumber(int i)
{
    // @stub
}

// E:\gamedcs\strip.cpp:139
DC_ONLY(0x158a80, 0x180)
void strip::DrawOwner(int frame)
{
    // @stub
}

// E:\gamedcs\strip.cpp:221
DC_ONLY(0x158c00, 0xBA)
void strip::DrawMonster(int i, int frame)
{
    // @stub
}

// E:\gamedcs\strip.cpp:253
DC_ONLY(0x158cbc, 0x78)
void strip::DrawSelector(int i)
{
    // @stub
}

