// wingraph.cpp - E:\gamedcs\wingraph.cpp (compiland wingraph.obj)
// HAND-OWNED after admission - INITIALLY GENERATED by `python3 -m homm3.carve carcass`; prototypes are Dreamcast CodeView evidence.
// 27 functions in link order; 28 compiler-generated $-thunks omitted.
#include <va.h>
#include <ddraw.h>
#include <string.h>
#include "wingraph.h"
#include "kb.h"
#include "kbwin.h"
#include "misc.h"
#include "palette.h"
#include "bitmap16.h"
#include "mousemgr.h"
#include "resourcemanager.h"
#include "smackmgr.h"
// DDSetFullScreenStatus brackets the mode change with a pause of the
// music stream.
#include "soundmgr.h"
#include "winmgr.h"

// Private desktop metrics, written as one consecutive triple by
// GetDesktopInfo's three GetDeviceCaps calls (BITSPIXEL, HORZRES, VERTRES)
// and read back by the two six-byte accessors below. No retail or Dreamcast
// symbol attests storage names, so these remain house-ordinal placeholders
// in their owning TU.
// Before normalization: gUnnamed68c870.
DATA(0x0068c870)
static int g_unnamed68c870;
// Before normalization: gUnnamed68c874.
DATA(0x0068c874)
static int g_unnamed68c874;
// Before normalization: gUnnamed68c878.
DATA(0x0068c878)
static int g_unnamed68c878;

// DirectDraw's lifecycle cells. The primary/back surfaces are public because
// the blitters consume them; the DirectDraw and clipper interfaces remain
// private to this compiland.
// Before normalization: gpDirectDraw.
DATA(0x006aacb8) static IDirectDraw* g_directDraw;
DATA(0x006aacbc) IDirectDrawSurface* g_ddsPrimary;
// Before normalization: gpDDClipper.
DATA(0x006aacc0) IDirectDrawSurface* g_ddsBack;
// Before normalization: gWinGraphBusy.
DATA(0x006aacd0) static IDirectDrawClipper* g_ddClipper;
// Before normalization: gInDirectDrawError.
DATA(0x006aacb4) static int g_winGraphBusy;
DATA(0x006aacd4) static unsigned char g_inDirectDrawError;

// wingraph's own Bitmap16Bit VIEW of the locked back surface, referenced
// (never owned) at every DDCreateSurface and re-referenced after each
// successful Blt retry. File-static: 0x6aac70 is touched from exactly four
// places and all four are rows in this compiland (0x1ffdf5 - the dynamic
// initializer that constructs it 0x0-by-0x0 - 0x1ffe11, 0x2001a9, 0x2006c2).
// NAME provisional: no roster attests it.
// Before normalization: gDDSurfaceBitmap.
DATA(0x006aac70) static Bitmap16Bit g_ddSurfaceBitmap(0, 0);

// DC's PixelFormat, one complete SDK object. GetPixelFormat writes all
// 32 bytes; its masks are members, not separate mousemgr-owned globals.
DATA(0x0068c850) DDPIXELFORMAT g_pixelFormat = {
    sizeof(DDPIXELFORMAT), DDPF_RGB
};

#if 0  // @carcass

// E:\gamedcs\wingraph.cpp:72
DC_ONLY(0x198af4, 0x26)
void setPlayerPaletteColors(unsigned short* pPalette, int whichPlayer)
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:83
DC_ONLY(0x198b1c, 0x2A)
void setPlayerPaletteColors(TPalette24* pal, int whichPlayer)
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:109
DC_ONLY(0x198b48, 0x1E)
void DDCreatePrimary()
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:130
DC_ONLY(0x198b68, 0x64)
void DDSetupClipper()
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:156
DC_ONLY(0x198bcc, 0x190)
void ddInitGraphics(int Mode, unsigned char reinit)
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:260
DC_ONLY(0x198d5c, 0x2D0)
void robAppBlit(tagRECT* comb_rect)
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:370
DC_ONLY(0x19902c, 0x26)
void ddAppBlit(const tagRECT* mregion)
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:529
DC_ONLY(0x199054, 0x90)
void DDAppBlitX(const tagRECT* region, int dx, int dy)
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:719
DC_ONLY(0x1990e4, 0x86)
void DDRestoreFrontBuffer(tagRECT* dst_rect)
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:861
DC_ONLY(0x19916c, 0x4)
void DDBlitFromFront()
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:931
DC_ONLY(0x199170, 0x140)
void ddBlit(IDirectDrawSurface4* dst_surface, const tagRECT* udst_rect, IDirectDrawSurface4* src_surface, const tagRECT* usrc_rect, unsigned long flags)
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:1013
DC_ONLY(0x1992b0, 0x1E0)
IDirectDrawSurface4* ddCreateSurface(unsigned long width, unsigned long height, int bPrimary, IDirectDrawSurface4** oldsurface)
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:1110
DC_ONLY(0x199490, 0x108)
IDirectDrawSurface4* BMCreateSurface(unsigned long width, unsigned long height)
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:1238
DC_ONLY(0x199598, 0x134)
void DDCreateMouseSurfaces()
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:1289
DC_ONLY(0x1996cc, 0x58)
void DDReleaseMouseSurfaces()
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:1476
DC_ONLY(0x19a09c, 0x76)
void ddCleanUpWinGraphics()
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:1691
DC_ONLY(0x19a20c, 0x28)
void ResizeWindow()
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:1712
DC_ONLY(0x19a234, 0x1AC)
unsigned char ddSetFullScreenStatus(int iNewStatus)
{
    // @stub
}

// E:\gamedcs\wingraph.cpp:1857
#endif  // @carcass

// The two player-colour painters, the first rows of wingraph.obj. Both copy
// the LAST 32 palette entries - the player-colour range - out of the
// Players.pal resource oldmain loaded, indexed by player: 32 RGB555 words
// for the 16-bit target, 32 RGB triples for the 24-bit one. The +0x1c source
// bias is the resource head both TPalette16 and TPalette24 carry, and the
// destination offsets (0x1c0 and 0x2bc) are what fix entry 224 as the range's
// first colour in each layout.
// E:\gamedcs\wingraph.cpp:72
VA(0x005ffe20, 0x1E)  // anchor-caller(bitmapBorder/button::SetPlayerPaletteColors) + dc-order-map, dc 0x198af4
void setPlayerPaletteColors(palette* pal, int whichPlayer)
{
    memcpy(&pal->m_data[224], &g_playerPalette->m_data[whichPlayer * 32],
           32 * sizeof(unsigned short));
}

// E:\gamedcs\wingraph.cpp:83
VA(0x005ffe40, 0x22)  // anchor-caller(bitmapBorder::SetPlayerPaletteColors) + dc-order-map, dc 0x198b1c
void setPlayerPaletteColors(TPalette24* pal, int whichPlayer)
{
    memcpy(pal->m_colors.m_data[224], g_playerPalette24->m_colors.m_data[whichPlayer * 32],
           32 * 3);
}

// The screen blit: unlock the back buffer, put the damaged rectangle up on
// the primary, and lock the back buffer again with both Bitmap16Bit views
// re-referenced to wherever it landed. When the damaged rectangle overlaps
// the saved mouse rectangle the pointer has to be composited into the back
// buffer first and lifted out again afterwards, which is the whole middle of
// the body; the empty spin on the mouse manager's busy word is retail's, and
// VC6 hoists its load out so the wait is one self-jump.
// E:\gamedcs\wingraph.cpp:260
// Before normalization (locals): comb_rect.
VA(0x005ffe70, 0x35C)  // anchor-caller(AppPaint, winmgr's five UpdateScreen/fade sites) + wingraph statics, dc 0x198d5c
void robAppBlit(tagRECT* combRect)
{
    if (IsIconic(g_hwndApp))
        return;
    if (!g_directDraw)
        return;
    if (combRect->right <= combRect->left)
        return;
    if (combRect->bottom <= combRect->top)
        return;

    HRESULT result = g_ddsBack->Unlock(0);
    if (result != DD_OK)
        ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                     "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0xdf);

    POINT origin;
    origin.x = 0;
    origin.y = 0;
    RECT screenRect = *combRect;
    ClientToScreen(g_hwndApp, &origin);
    OffsetRect(&screenRect, origin.x, origin.y);

    if (g_mouseManager->m_savedRect.right > combRect->left
        && combRect->right > g_mouseManager->m_savedRect.left
        && g_mouseManager->m_savedRect.bottom > combRect->top
        && combRect->bottom > g_mouseManager->m_savedRect.top) {
        RECT pointerRect;
        RECT sourceRect;
        if (g_mouseManager) {
            while (g_mouseManager->m_busy)
                ;
            IntersectRect(&pointerRect, combRect,
                          &g_mouseManager->m_savedRect);
            sourceRect = pointerRect;
            OffsetRect(&sourceRect, -g_mouseManager->m_savedRect.left,
                       -g_mouseManager->m_savedRect.top);
            ddBlit(g_ddsMouseSaveSurface, &sourceRect, static_cast<IDirectDrawSurface4*>(static_cast<void*>(g_ddsBack)),
                   &pointerRect, DDBLT_WAIT);
            if (g_mouseManager->m_hideCount == 0 && g_mouseManager->m_sprite
                && g_mouseManager->m_frame >= 0) {
                DDSURFACEDESC surfaceDesc;
                memset(&surfaceDesc, 0, sizeof(surfaceDesc));
                surfaceDesc.dwSize = sizeof(surfaceDesc);
                result = g_ddsBack->Lock(0, &surfaceDesc, DDLOCK_WAIT, 0);
                if (result != DD_OK)
                    ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                     "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x119);
                g_mouseManager->m_sprite->draw(0, g_mouseManager->m_frame,
                    pointerRect.left - g_mouseManager->m_imageX,
                    pointerRect.top - g_mouseManager->m_imageY,
                    pointerRect.right - pointerRect.left,
                    pointerRect.bottom - pointerRect.top,
                    static_cast<unsigned short*>(surfaceDesc.lpSurface),
                    pointerRect.left, pointerRect.top,
                    surfaceDesc.dwWidth, surfaceDesc.dwHeight,
                    surfaceDesc.lPitch, 0, 1);
                result = g_ddsBack->Unlock(0);
                if (result != DD_OK)
                    ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                     "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x124);
            }
        }

        ddBlit(static_cast<IDirectDrawSurface4*>(static_cast<void*>(g_ddsPrimary)), &screenRect, static_cast<IDirectDrawSurface4*>(static_cast<void*>(g_ddsBack)), combRect, DDBLT_WAIT);

        if (g_mouseManager && g_mouseManager->m_hideCount == 0
            && g_mouseManager->m_sprite && g_mouseManager->m_frame >= 0) {
            ddBlit(static_cast<IDirectDrawSurface4*>(static_cast<void*>(g_ddsBack)), &pointerRect, g_ddsMouseSaveSurface,
                   &sourceRect, DDBLT_WAIT);
        }
    } else {
        ddBlit(static_cast<IDirectDrawSurface4*>(static_cast<void*>(g_ddsPrimary)), &screenRect, static_cast<IDirectDrawSurface4*>(static_cast<void*>(g_ddsBack)), combRect, DDBLT_WAIT);
    }

    DDSURFACEDESC surfaceDesc;
    memset(&surfaceDesc, 0, sizeof(surfaceDesc));
    surfaceDesc.dwSize = sizeof(surfaceDesc);
    result = g_ddsBack->Lock(0, &surfaceDesc, DDLOCK_WAIT, 0);
    if (result != DD_OK)
        ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                     "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x13e);

    if (g_windowManager->m_screenBitmap) {
        g_windowManager->m_screenBitmap->reference(
            surfaceDesc.dwWidth, surfaceDesc.dwHeight, surfaceDesc.lPitch,
            static_cast<unsigned short*>(surfaceDesc.lpSurface));
    }
    g_ddSurfaceBitmap.reference(
        surfaceDesc.dwWidth, surfaceDesc.dwHeight, surfaceDesc.lPitch,
        static_cast<unsigned short*>(surfaceDesc.lpSurface));

    if (result != DD_OK)
        ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                     "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x14a);
}

// Every surface-to-surface copy in the game goes through here, and the
// whole body is three copies of one retry loop: blit, and while DirectDraw
// answers DDERR_SURFACELOST, restore whatever was lost and blit again. The
// three arms differ only in which surface is the primary - retail RELOADS
// gpDDSPrimary at each of its six uses rather than naming it - and the two
// arms that touch the primary take a LOCAL COPY of the rectangle that
// belongs to it, because DDResetDisplayMode re-origins that copy in place
// when the mode changed underneath. The discarded GameTime::Get() before
// each loop is retail's, not an artifact.
//
// The two surface interface generations meet here: the roster types this
// function's parameters IDirectDrawSurface4 (mousemgr's three globals agree)
// while the primary is the v1 interface DirectDrawCreate returns, so the
// primary is bridged through void* at each use exactly as mousemgr already
// bridges DDSURFACEDESC. The vtable prefix through Restore is identical in
// both generations, so no byte depends on the choice.
//
// EXACT (100.0000%, 2026-09-05). The three retry arms are
// `while (1) { if (Blt(...) != LOST) goto done; <recovery> }` - an infinite
// loop whose ONLY exit is the forward `goto` out of the function. The
// previous note recorded this as the merged-return / tail-merge class after
// four measurements ("VC6 INVERTS all three retry loops... every shape is
// BYTE-IDENTICAL"), and the conclusion was wrong: all four of those shapes
// keep a LABEL that both falls in and is jumped back to, and VC6 PEELS such
// a label - it emits the Blt once as a guard and a second time at the
// bottom, giving three surplus calls and two surplus rets. Wrapping the same
// statements in `while (1)` removes the fall-in predecessor, so VC6 emits
// one Blt per arm with retail's unconditional `jmp` back edge and
// cross-jumps all three epilogues onto the single `ret 0xc`. 63.77 -> 100.
// Same lever, same day: kb::oldmain's two campaign-continue arms, 73.35 ->
// 75.97.
// Direct returns from all three Blt loops also share the retail epilogue
// and remain exact; no forward done label is needed.
// E:\gamedcs\wingraph.cpp:931
VA(0x006001d0, 0x1E1)  // anchor-caller(mousemgr, six sites) + header identification, dc 0x199170
void ddBlit(IDirectDrawSurface4* dstSurface, const tagRECT* dstRect,
            IDirectDrawSurface4* srcSurface, const tagRECT* srcRect,
            unsigned long flags)
{
    if (IsRectEmpty(srcRect))
        return;

    if (dstSurface
        == static_cast<IDirectDrawSurface4*>(
               static_cast<void*>(g_ddsPrimary))) {
        RECT region = *dstRect;
        GameTime::get();
        while (1) {
            if (g_ddsPrimary->Blt(&region,
                    static_cast<IDirectDrawSurface*>(
                        static_cast<void*>(srcSurface)),
                    const_cast<RECT*>(srcRect), flags, 0)
                != DDERR_SURFACELOST) {
                return;
            }
            if (g_ddsPrimary->IsLost() == DDERR_SURFACELOST) {
                HRESULT result = g_ddsPrimary->Restore();
                if (result == DDERR_WRONGMODE)
                    ddResetDisplayMode(&region);
                else if (result != DD_OK)
                    ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                                  "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x1b4);
            }
            if (srcSurface->IsLost() == DDERR_SURFACELOST) {
                HRESULT result = ddRestoreSurfaces();
                if (result != DD_OK)
                    ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                                  "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x1bb);
            }
        }
    }

    if (srcSurface
        == static_cast<IDirectDrawSurface4*>(
               static_cast<void*>(g_ddsPrimary))) {
        RECT region = *srcRect;
        GameTime::get();
        while (1) {
            if (dstSurface->Blt(const_cast<RECT*>(dstRect),
                    static_cast<IDirectDrawSurface4*>(
                        static_cast<void*>(g_ddsPrimary)),
                    &region, flags, 0)
                != DDERR_SURFACELOST) {
                return;
            }
            if (g_ddsPrimary->IsLost() == DDERR_SURFACELOST) {
                HRESULT result = g_ddsPrimary->Restore();
                if (result == DDERR_WRONGMODE)
                    ddResetDisplayMode(&region);
                else if (result != DD_OK)
                    ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                                  "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x1ef);
            }
            if (dstSurface->IsLost() == DDERR_SURFACELOST) {
                HRESULT result = ddRestoreSurfaces();
                if (result != DD_OK)
                    ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                                  "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x1f6);
            }
        }
    }

    GameTime::get();
    while (1) {
        if (dstSurface->Blt(const_cast<RECT*>(dstRect), srcSurface,
                const_cast<RECT*>(srcRect), flags, 0)
            != DDERR_SURFACELOST) {
            return;
        }
        {
            HRESULT result = ddRestoreSurfaces();
            if (result != DD_OK)
                ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                                  "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x233);
        }
    }
}

// The DDERR_WRONGMODE recovery DDBlit's two primary-surface loops call when
// Restore reports the display mode changed underneath the game. If we were
// already fullscreen the mode is simply re-asserted and the primary
// restored; otherwise the primary and its clipper are dropped, the desktop
// caps re-read, and - unless the desktop is itself 16-bit - the window is
// pushed into fullscreen (popup style, topmost, no menu) with the blit's own
// rectangle re-origined against the moved client area, which is why the
// caller hands its working copy in. Either way the primary is rebuilt and,
// if we ended up fullscreen, the preference is written back.
//
// The desktop-caps block is GetDesktopInfo expanded: it is a small extern
// with an out-of-line body further down this TU, so /Ob2 takes it here and
// leaves the emitted copy for the other callers.
// E:\gamedcs\wingraph.cpp
VA(0x006003c0, 0x22D)  // anchor-caller(DDBlit, both primary retry loops), retail-only
void ddResetDisplayMode(tagRECT* region)
{
    if (g_windowedMode) {
        HRESULT result = g_directDraw->SetCooperativeLevel(
            g_hwndApp, DDSCL_EXCLUSIVE | DDSCL_FULLSCREEN | DDSCL_ALLOWREBOOT);
        if (result != DD_OK)
            ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x157);
        result = g_directDraw->SetDisplayMode(800, 600, 16);
        if (result != DD_OK)
            ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x15b);
        result = g_ddsPrimary->Restore();
        if (result != DD_OK)
            ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x15f);
        return;
    }

    unsigned char desktopIsHighColor = getDesktopInfo();

    HRESULT result = g_ddsPrimary->SetClipper(0);
    if (result != DD_OK)
        ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x168);
    g_ddsPrimary->Release();
    g_ddsPrimary = 0;

    if (!desktopIsHighColor) {
        POINT origin;
        origin.x = 0;
        origin.y = 0;
        ScreenToClient(g_hwndApp, &origin);
        OffsetRect(region, origin.x, origin.y);
        g_ddClipper->Release();
        g_ddClipper = 0;
        g_windowedMode = 1;
        SetWindowLongA(g_hwndApp, GWL_STYLE, WS_POPUP | WS_VISIBLE);
        SetWindowLongA(g_hwndApp, GWL_EXSTYLE, WS_EX_TOPMOST);
        kbChangeMenu(0);
        result = g_directDraw->SetCooperativeLevel(
            g_hwndApp, DDSCL_EXCLUSIVE | DDSCL_FULLSCREEN | DDSCL_ALLOWREBOOT);
        if (result != DD_OK)
            ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x17e);
        result = g_directDraw->SetDisplayMode(800, 600, 16);
        if (result != DD_OK)
            ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x182);
    }

    g_ddsPrimary = ddCreateSurface(800, 600, 1);

    if (!g_windowedMode) {
        result = g_ddsPrimary->SetClipper(g_ddClipper);
        if (result != DD_OK)
            ddsd(result, DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"), 0x18c);
    } else {
        writePrefs();
    }
}

// The one surface factory: DDInitGraphics builds the 800x600 primary
// through it with bPrimary set, and the back buffer with it clear. Only the
// offscreen arm is locked and published - the lock's own DDSURFACEDESC is
// what feeds both Bitmap16Bit references, so the surface pointer, pitch and
// extent all come back through the same descriptor the create filled in.
// Retail reuses the bPrimary parameter home for the created surface, which
// is why the flag is cached in a register before the call.
// E:\gamedcs\wingraph.cpp:1013
VA(0x006005f0, 0xE4)  // anchor-caller(DDInitGraphics, both surfaces) + header identification, dc 0x1992b0
IDirectDrawSurface* ddCreateSurface(unsigned long width, unsigned long height,
                                    // Before normalization (locals): bPrimary.
                                    int primary)
{
    DDSURFACEDESC surfaceDesc;
    IDirectDrawSurface* surface;

    memset(&surfaceDesc, 0, sizeof(surfaceDesc));
    surfaceDesc.dwSize = sizeof(surfaceDesc);
    if (primary) {
        surfaceDesc.dwFlags = DDSD_CAPS;
        surfaceDesc.ddsCaps.dwCaps = DDSCAPS_PRIMARYSURFACE;
    } else {
        surfaceDesc.dwFlags = DDSD_CAPS | DDSD_HEIGHT | DDSD_WIDTH;
        surfaceDesc.ddsCaps.dwCaps =
            DDSCAPS_OFFSCREENPLAIN | DDSCAPS_SYSTEMMEMORY;
        surfaceDesc.dwHeight = height;
        surfaceDesc.dwWidth = width;
    }

    HRESULT result = g_directDraw->CreateSurface(&surfaceDesc, &surface, 0);
    if (result != DD_OK)
        ddsd(result,
             DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                          "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"),
             0x263);

    if (!primary) {
        result = surface->Lock(0, &surfaceDesc, DDLOCK_WAIT, 0);
        if (result != DD_OK)
            ddsd(result,
                 DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"),
                 0x26a);

        if (g_windowManager->m_screenBitmap) {
            g_windowManager->m_screenBitmap->reference(
                surfaceDesc.dwWidth, surfaceDesc.dwHeight, surfaceDesc.lPitch,
                static_cast<unsigned short*>(surfaceDesc.lpSurface));
        }
        g_ddSurfaceBitmap.reference(
            surfaceDesc.dwWidth, surfaceDesc.dwHeight, surfaceDesc.lPitch,
            static_cast<unsigned short*>(surfaceDesc.lpSurface));
    }

    return surface;
}

// The Dreamcast line table groups the re-entry test, RestoreDisplayMode,
// error-name switch, formatter and shutdown into the same source statements
// retained here.  Complete's x86 body independently proves the 200-byte
// cTemp extent, every HRESULT case, one MessageBeep, the low-word error code
// passed to wsprintfA, and the final guard reset.  The shared HoMM2 DDSD body
// supplies the source lineage; its smaller error roster is not copied blindly.
// Before normalization (locals): iDDErr, cFile, iLine, cTemp.
VA(0x006006E0, 0xCBF)  // DC DDSD identity + retail literals/CFG + HoMM2 lineage
void ddsd(int ddErr, char* file, int line)
{
    char temp[200];

    if (g_inDirectDrawError)
        return;

    g_inDirectDrawError = 1;
    if (g_directDraw)
        g_directDraw->RestoreDisplayMode();

    switch (ddErr) {
    case DD_OK:
        return;
    case DDERR_OUTOFMEMORY:
        strcpy(temp, DATA_COMPGEN(0x0068D248, ddsd_DDERR_OUTOFMEMORY,
                                   "DDERR_OUTOFMEMORY"));
        break;
    case DDERR_GENERIC:
        strcpy(temp, DATA_COMPGEN(0x0068D238, ddsd_DDERR_GENERIC,
                                   "DDERR_GENERIC"));
        break;
    case DDERR_UNSUPPORTED:
        strcpy(temp, DATA_COMPGEN(0x0068D224, ddsd_DDERR_UNSUPPORTED,
                                   "DDERR_UNSUPPORTED"));
        break;
    case DDERR_INVALIDPARAMS:
        strcpy(temp, DATA_COMPGEN(0x0068D210, ddsd_DDERR_INVALIDPARAMS,
                                   "DDERR_INVALIDPARAMS"));
        break;
    case DDERR_CANNOTATTACHSURFACE:
        strcpy(temp, DATA_COMPGEN(0x0068D1F4,
                                   ddsd_DDERR_CANNOTATTACHSURFACE,
                                   "DDERR_CANNOTATTACHSURFACE"));
        break;
    case DDERR_ALREADYINITIALIZED:
        strcpy(temp, DATA_COMPGEN(0x0068D1D8,
                                   ddsd_DDERR_ALREADYINITIALIZED,
                                   "DDERR_ALREADYINITIALIZED"));
        break;
    case DDERR_CANNOTDETACHSURFACE:
        strcpy(temp, DATA_COMPGEN(0x0068D1BC,
                                   ddsd_DDERR_CANNOTDETACHSURFACE,
                                   "DDERR_CANNOTDETACHSURFACE"));
        break;
    case DDERR_CURRENTLYNOTAVAIL:
        strcpy(temp, DATA_COMPGEN(0x0068D1A4,
                                   ddsd_DDERR_CURRENTLYNOTAVAIL,
                                   "DDERR_CURRENTLYNOTAVAIL"));
        break;
    case DDERR_EXCEPTION:
        strcpy(temp, DATA_COMPGEN(0x0068D194, ddsd_DDERR_EXCEPTION,
                                   "DDERR_EXCEPTION"));
        break;
    case DDERR_HEIGHTALIGN:
        strcpy(temp, DATA_COMPGEN(0x0068D180, ddsd_DDERR_HEIGHTALIGN,
                                   "DDERR_HEIGHTALIGN"));
        break;
    case DDERR_INCOMPATIBLEPRIMARY:
        strcpy(temp, DATA_COMPGEN(0x0068D164,
                                   ddsd_DDERR_INCOMPATIBLEPRIMARY,
                                   "DDERR_INCOMPATIBLEPRIMARY"));
        break;
    case DDERR_INVALIDCAPS:
        strcpy(temp, DATA_COMPGEN(0x0068D150, ddsd_DDERR_INVALIDCAPS,
                                   "DDERR_INVALIDCAPS"));
        break;
    case DDERR_INVALIDCLIPLIST:
        strcpy(temp, DATA_COMPGEN(0x0068D138,
                                   ddsd_DDERR_INVALIDCLIPLIST,
                                   "DDERR_INVALIDCLIPLIST"));
        break;
    case DDERR_INVALIDMODE:
        strcpy(temp, DATA_COMPGEN(0x0068D124, ddsd_DDERR_INVALIDMODE,
                                   "DDERR_INVALIDMODE"));
        break;
    case DDERR_INVALIDOBJECT:
        strcpy(temp, DATA_COMPGEN(0x0068D110,
                                   ddsd_DDERR_INVALIDOBJECT,
                                   "DDERR_INVALIDOBJECT"));
        break;
    case DDERR_INVALIDPIXELFORMAT:
        strcpy(temp, DATA_COMPGEN(0x0068D0F4,
                                   ddsd_DDERR_INVALIDPIXELFORMAT,
                                   "DDERR_INVALIDPIXELFORMAT"));
        break;
    case DDERR_INVALIDRECT:
        strcpy(temp, DATA_COMPGEN(0x0068D0E0, ddsd_DDERR_INVALIDRECT,
                                   "DDERR_INVALIDRECT"));
        break;
    case DDERR_LOCKEDSURFACES:
        strcpy(temp, DATA_COMPGEN(0x0068D0C8,
                                   ddsd_DDERR_LOCKEDSURFACES,
                                   "DDERR_LOCKEDSURFACES"));
        break;
    case DDERR_NO3D:
        strcpy(temp, DATA_COMPGEN(0x0068D0BC, ddsd_DDERR_NO3D,
                                   "DDERR_NO3D"));
        break;
    case DDERR_NOALPHAHW:
        strcpy(temp, DATA_COMPGEN(0x0068D0AC, ddsd_DDERR_NOALPHAHW,
                                   "DDERR_NOALPHAHW"));
        break;
    case DDERR_NOCLIPLIST:
        strcpy(temp, DATA_COMPGEN(0x0068D098, ddsd_DDERR_NOCLIPLIST,
                                   "DDERR_NOCLIPLIST"));
        break;
    case DDERR_NOCOLORCONVHW:
        strcpy(temp, DATA_COMPGEN(0x0068D084,
                                   ddsd_DDERR_NOCOLORCONVHW,
                                   "DDERR_NOCOLORCONVHW"));
        break;
    case DDERR_NOCOOPERATIVELEVELSET:
        strcpy(temp, DATA_COMPGEN(0x0068D068,
                                   ddsd_DDERR_NOCOOPERATIVELEVELSET,
                                   "DDERR_NOCOOPERATIVELEVELSET"));
        break;
    case DDERR_NOCOLORKEY:
        strcpy(temp, DATA_COMPGEN(0x0068D054, ddsd_DDERR_NOCOLORKEY,
                                   "DDERR_NOCOLORKEY"));
        break;
    case DDERR_NOCOLORKEYHW:
        strcpy(temp, DATA_COMPGEN(0x0068D040,
                                   ddsd_DDERR_NOCOLORKEYHW,
                                   "DDERR_NOCOLORKEYHW"));
        break;
    case DDERR_NODIRECTDRAWSUPPORT:
        strcpy(temp, DATA_COMPGEN(0x0068D024,
                                   ddsd_DDERR_NODIRECTDRAWSUPPORT,
                                   "DDERR_NODIRECTDRAWSUPPORT"));
        break;
    case DDERR_NOEXCLUSIVEMODE:
        strcpy(temp, DATA_COMPGEN(0x0068D00C,
                                   ddsd_DDERR_NOEXCLUSIVEMODE,
                                   "DDERR_NOEXCLUSIVEMODE"));
        break;
    case DDERR_NOFLIPHW:
        strcpy(temp, DATA_COMPGEN(0x0068CFFC, ddsd_DDERR_NOFLIPHW,
                                   "DDERR_NOFLIPHW"));
        break;
    case DDERR_NOGDI:
        strcpy(temp, DATA_COMPGEN(0x0068CFF0, ddsd_DDERR_NOGDI,
                                   "DDERR_NOGDI"));
        break;
    case DDERR_NOMIRRORHW:
        strcpy(temp, DATA_COMPGEN(0x0068CFDC, ddsd_DDERR_NOMIRRORHW,
                                   "DDERR_NOMIRRORHW"));
        break;
    case DDERR_NOTFOUND:
        strcpy(temp, DATA_COMPGEN(0x0068CFCC, ddsd_DDERR_NOTFOUND,
                                   "DDERR_NOTFOUND"));
        break;
    case DDERR_NOOVERLAYHW:
        strcpy(temp, DATA_COMPGEN(0x0068CFB8, ddsd_DDERR_NOOVERLAYHW,
                                   "DDERR_NOOVERLAYHW"));
        break;
    case DDERR_OVERLAPPINGRECTS:
        strcpy(temp, DATA_COMPGEN(0x0068CFA0,
                                   ddsd_DDERR_OVERLAPPINGRECTS,
                                   "DDERR_OVERLAPPINGRECTS"));
        break;
    case DDERR_NORASTEROPHW:
        strcpy(temp, DATA_COMPGEN(0x0068CF8C,
                                   ddsd_DDERR_NORASTEROPHW,
                                   "DDERR_NORASTEROPHW"));
        break;
    case DDERR_NOROTATIONHW:
        strcpy(temp, DATA_COMPGEN(0x0068CF78,
                                   ddsd_DDERR_NOROTATIONHW,
                                   "DDERR_NOROTATIONHW"));
        break;
    case DDERR_NOSTRETCHHW:
        strcpy(temp, DATA_COMPGEN(0x0068CF64,
                                   ddsd_DDERR_NOSTRETCHHW,
                                   "DDERR_NOSTRETCHHW"));
        break;
    case DDERR_NOT4BITCOLOR:
        strcpy(temp, DATA_COMPGEN(0x0068CF50,
                                   ddsd_DDERR_NOT4BITCOLOR,
                                   "DDERR_NOT4BITCOLOR"));
        break;
    case DDERR_NOT4BITCOLORINDEX:
        strcpy(temp, DATA_COMPGEN(0x0068CF38,
                                   ddsd_DDERR_NOT4BITCOLORINDEX,
                                   "DDERR_NOT4BITCOLORINDEX"));
        break;
    case DDERR_NOT8BITCOLOR:
        strcpy(temp, DATA_COMPGEN(0x0068CF24,
                                   ddsd_DDERR_NOT8BITCOLOR,
                                   "DDERR_NOT8BITCOLOR"));
        break;
    case DDERR_NOTEXTUREHW:
        strcpy(temp, DATA_COMPGEN(0x0068CF10,
                                   ddsd_DDERR_NOTEXTUREHW,
                                   "DDERR_NOTEXTUREHW"));
        break;
    case DDERR_NOVSYNCHW:
        strcpy(temp, DATA_COMPGEN(0x0068CF00, ddsd_DDERR_NOVSYNCHW,
                                   "DDERR_NOVSYNCHW"));
        break;
    case DDERR_NOZBUFFERHW:
        strcpy(temp, DATA_COMPGEN(0x0068CEEC,
                                   ddsd_DDERR_NOZBUFFERHW,
                                   "DDERR_NOZBUFFERHW"));
        break;
    case DDERR_NOZOVERLAYHW:
        strcpy(temp, DATA_COMPGEN(0x0068CED8,
                                   ddsd_DDERR_NOZOVERLAYHW,
                                   "DDERR_NOZOVERLAYHW"));
        break;
    case DDERR_OUTOFCAPS:
        strcpy(temp, DATA_COMPGEN(0x0068CEC8, ddsd_DDERR_OUTOFCAPS,
                                   "DDERR_OUTOFCAPS"));
        break;
    case DDERR_OUTOFVIDEOMEMORY:
        strcpy(temp, DATA_COMPGEN(0x0068CEB0,
                                   ddsd_DDERR_OUTOFVIDEOMEMORY,
                                   "DDERR_OUTOFVIDEOMEMORY"));
        break;
    case DDERR_OVERLAYCANTCLIP:
        strcpy(temp, DATA_COMPGEN(0x0068CE98,
                                   ddsd_DDERR_OVERLAYCANTCLIP,
                                   "DDERR_OVERLAYCANTCLIP"));
        break;
    case DDERR_OVERLAYCOLORKEYONLYONEACTIVE:
        strcpy(temp, DATA_COMPGEN(0x0068CE74,
                                   ddsd_DDERR_OVERLAYCOLORKEYONLYONEACTIVE,
                                   "DDERR_OVERLAYCOLORKEYONLYONEACTIVE"));
        break;
    case DDERR_PALETTEBUSY:
        strcpy(temp, DATA_COMPGEN(0x0068CE60, ddsd_DDERR_PALETTEBUSY,
                                   "DDERR_PALETTEBUSY"));
        break;
    case DDERR_COLORKEYNOTSET:
        strcpy(temp, DATA_COMPGEN(0x0068CE48,
                                   ddsd_DDERR_COLORKEYNOTSET,
                                   "DDERR_COLORKEYNOTSET"));
        break;
    case DDERR_SURFACEALREADYATTACHED:
        strcpy(temp, DATA_COMPGEN(0x0068CE28,
                                   ddsd_DDERR_SURFACEALREADYATTACHED,
                                   "DDERR_SURFACEALREADYATTACHED"));
        break;
    case DDERR_SURFACEALREADYDEPENDENT:
        strcpy(temp, DATA_COMPGEN(0x0068CE08,
                                   ddsd_DDERR_SURFACEALREADYDEPENDENT,
                                   "DDERR_SURFACEALREADYDEPENDENT"));
        break;
    case DDERR_SURFACEBUSY:
        strcpy(temp, DATA_COMPGEN(0x0068CDF4, ddsd_DDERR_SURFACEBUSY,
                                   "DDERR_SURFACEBUSY"));
        break;
    case DDERR_CANTLOCKSURFACE:
        strcpy(temp, DATA_COMPGEN(0x0068CDDC,
                                   ddsd_DDERR_CANTLOCKSURFACE,
                                   "DDERR_CANTLOCKSURFACE"));
        break;
    case DDERR_SURFACEISOBSCURED:
        strcpy(temp, DATA_COMPGEN(0x0068CDC4,
                                   ddsd_DDERR_SURFACEISOBSCURED,
                                   "DDERR_SURFACEISOBSCURED"));
        break;
    case DDERR_SURFACELOST:
        strcpy(temp, DATA_COMPGEN(0x0068CDB0, ddsd_DDERR_SURFACELOST,
                                   "DDERR_SURFACELOST"));
        break;
    case DDERR_SURFACENOTATTACHED:
        strcpy(temp, DATA_COMPGEN(0x0068CD94,
                                   ddsd_DDERR_SURFACENOTATTACHED,
                                   "DDERR_SURFACENOTATTACHED"));
        break;
    case DDERR_TOOBIGHEIGHT:
        strcpy(temp, DATA_COMPGEN(0x0068CD80,
                                   ddsd_DDERR_TOOBIGHEIGHT,
                                   "DDERR_TOOBIGHEIGHT"));
        break;
    case DDERR_TOOBIGSIZE:
        strcpy(temp, DATA_COMPGEN(0x0068CD6C, ddsd_DDERR_TOOBIGSIZE,
                                   "DDERR_TOOBIGSIZE"));
        break;
    case DDERR_TOOBIGWIDTH:
        strcpy(temp, DATA_COMPGEN(0x0068CD58,
                                   ddsd_DDERR_TOOBIGWIDTH,
                                   "DDERR_TOOBIGWIDTH"));
        break;
    case DDERR_UNSUPPORTEDFORMAT:
        strcpy(temp, DATA_COMPGEN(0x0068CD40,
                                   ddsd_DDERR_UNSUPPORTEDFORMAT,
                                   "DDERR_UNSUPPORTEDFORMAT"));
        break;
    case DDERR_UNSUPPORTEDMASK:
        strcpy(temp, DATA_COMPGEN(0x0068CD28,
                                   ddsd_DDERR_UNSUPPORTEDMASK,
                                   "DDERR_UNSUPPORTEDMASK"));
        break;
    case DDERR_INVALIDSTREAM:
        strcpy(temp, DATA_COMPGEN(0x0068CD14,
                                   ddsd_DDERR_INVALIDSTREAM,
                                   "DDERR_INVALIDSTREAM"));
        break;
    case DDERR_VERTICALBLANKINPROGRESS:
        strcpy(temp, DATA_COMPGEN(0x0068CCF4,
                                   ddsd_DDERR_VERTICALBLANKINPROGRESS,
                                   "DDERR_VERTICALBLANKINPROGRESS"));
        break;
    case DDERR_WASSTILLDRAWING:
        strcpy(temp, DATA_COMPGEN(0x0068CCDC,
                                   ddsd_DDERR_WASSTILLDRAWING,
                                   "DDERR_WASSTILLDRAWING"));
        break;
    case DDERR_XALIGN:
        strcpy(temp, DATA_COMPGEN(0x0068CCCC, ddsd_DDERR_XALIGN,
                                   "DDERR_XALIGN"));
        break;
    case DDERR_INVALIDDIRECTDRAWGUID:
        strcpy(temp, DATA_COMPGEN(0x0068CCB0,
                                   ddsd_DDERR_INVALIDDIRECTDRAWGUID,
                                   "DDERR_INVALIDDIRECTDRAWGUID"));
        break;
    case DDERR_DIRECTDRAWALREADYCREATED:
        strcpy(temp, DATA_COMPGEN(0x0068CC90,
                                   ddsd_DDERR_DIRECTDRAWALREADYCREATED,
                                   "DDERR_DIRECTDRAWALREADYCREATED"));
        break;
    case DDERR_NODIRECTDRAWHW:
        strcpy(temp, DATA_COMPGEN(0x0068CC78,
                                   ddsd_DDERR_NODIRECTDRAWHW,
                                   "DDERR_NODIRECTDRAWHW"));
        break;
    case DDERR_PRIMARYSURFACEALREADYEXISTS:
        strcpy(temp, DATA_COMPGEN(0x0068CC54,
                                   ddsd_DDERR_PRIMARYSURFACEALREADYEXISTS,
                                   "DDERR_PRIMARYSURFACEALREADYEXISTS"));
        break;
    case DDERR_NOEMULATION:
        strcpy(temp, DATA_COMPGEN(0x0068CC40, ddsd_DDERR_NOEMULATION,
                                   "DDERR_NOEMULATION"));
        break;
    case DDERR_REGIONTOOSMALL:
        strcpy(temp, DATA_COMPGEN(0x0068CC28,
                                   ddsd_DDERR_REGIONTOOSMALL,
                                   "DDERR_REGIONTOOSMALL"));
        break;
    case DDERR_CLIPPERISUSINGHWND:
        strcpy(temp, DATA_COMPGEN(0x0068CC0C,
                                   ddsd_DDERR_CLIPPERISUSINGHWND,
                                   "DDERR_CLIPPERISUSINGHWND"));
        break;
    case DDERR_NOCLIPPERATTACHED:
        strcpy(temp, DATA_COMPGEN(0x0068CBF4,
                                   ddsd_DDERR_NOCLIPPERATTACHED,
                                   "DDERR_NOCLIPPERATTACHED"));
        break;
    case DDERR_NOHWND:
        strcpy(temp, DATA_COMPGEN(0x0068CBE4, ddsd_DDERR_NOHWND,
                                   "DDERR_NOHWND"));
        break;
    case DDERR_HWNDSUBCLASSED:
        strcpy(temp, DATA_COMPGEN(0x0068CBCC,
                                   ddsd_DDERR_HWNDSUBCLASSED,
                                   "DDERR_HWNDSUBCLASSED"));
        break;
    case DDERR_HWNDALREADYSET:
        strcpy(temp, DATA_COMPGEN(0x0068CBB4,
                                   ddsd_DDERR_HWNDALREADYSET,
                                   "DDERR_HWNDALREADYSET"));
        break;
    case DDERR_NOPALETTEATTACHED:
        strcpy(temp, DATA_COMPGEN(0x0068CB9C,
                                   ddsd_DDERR_NOPALETTEATTACHED,
                                   "DDERR_NOPALETTEATTACHED"));
        break;
    case DDERR_NOPALETTEHW:
        strcpy(temp, DATA_COMPGEN(0x0068CB88,
                                   ddsd_DDERR_NOPALETTEHW,
                                   "DDERR_NOPALETTEHW"));
        break;
    case DDERR_BLTFASTCANTCLIP:
        strcpy(temp, DATA_COMPGEN(0x0068CB70,
                                   ddsd_DDERR_BLTFASTCANTCLIP,
                                   "DDERR_BLTFASTCANTCLIP"));
        break;
    case DDERR_NOBLTHW:
        strcpy(temp, DATA_COMPGEN(0x0068CB60, ddsd_DDERR_NOBLTHW,
                                   "DDERR_NOBLTHW"));
        break;
    case DDERR_NODDROPSHW:
        strcpy(temp, DATA_COMPGEN(0x0068CB4C,
                                   ddsd_DDERR_NODDROPSHW,
                                   "DDERR_NODDROPSHW"));
        break;
    case DDERR_OVERLAYNOTVISIBLE:
        strcpy(temp, DATA_COMPGEN(0x0068CB34,
                                   ddsd_DDERR_OVERLAYNOTVISIBLE,
                                   "DDERR_OVERLAYNOTVISIBLE"));
        break;
    case DDERR_NOOVERLAYDEST:
        strcpy(temp, DATA_COMPGEN(0x0068CB20,
                                   ddsd_DDERR_NOOVERLAYDEST,
                                   "DDERR_NOOVERLAYDEST"));
        break;
    case DDERR_INVALIDPOSITION:
        strcpy(temp, DATA_COMPGEN(0x0068CB08,
                                   ddsd_DDERR_INVALIDPOSITION,
                                   "DDERR_INVALIDPOSITION"));
        break;
    case DDERR_NOTAOVERLAYSURFACE:
        strcpy(temp, DATA_COMPGEN(0x0068CAEC,
                                   ddsd_DDERR_NOTAOVERLAYSURFACE,
                                   "DDERR_NOTAOVERLAYSURFACE"));
        break;
    case DDERR_EXCLUSIVEMODEALREADYSET:
        strcpy(temp, DATA_COMPGEN(0x0068CACC,
                                   ddsd_DDERR_EXCLUSIVEMODEALREADYSET,
                                   "DDERR_EXCLUSIVEMODEALREADYSET"));
        break;
    case DDERR_NOTFLIPPABLE:
        strcpy(temp, DATA_COMPGEN(0x0068CAB8,
                                   ddsd_DDERR_NOTFLIPPABLE,
                                   "DDERR_NOTFLIPPABLE"));
        break;
    case DDERR_CANTDUPLICATE:
        strcpy(temp, DATA_COMPGEN(0x0068CAA4,
                                   ddsd_DDERR_CANTDUPLICATE,
                                   "DDERR_CANTDUPLICATE"));
        break;
    case DDERR_NOTLOCKED:
        strcpy(temp, DATA_COMPGEN(0x0068CA94, ddsd_DDERR_NOTLOCKED,
                                   "DDERR_NOTLOCKED"));
        break;
    case DDERR_CANTCREATEDC:
        strcpy(temp, DATA_COMPGEN(0x0068CA80,
                                   ddsd_DDERR_CANTCREATEDC,
                                   "DDERR_CANTCREATEDC"));
        break;
    case DDERR_NODC:
        strcpy(temp, DATA_COMPGEN(0x0068CA74, ddsd_DDERR_NODC,
                                   "DDERR_NODC"));
        break;
    case DDERR_WRONGMODE:
        strcpy(temp, DATA_COMPGEN(0x0068CA64, ddsd_DDERR_WRONGMODE,
                                   "DDERR_WRONGMODE"));
        break;
    case DDERR_IMPLICITLYCREATED:
        strcpy(temp, DATA_COMPGEN(0x0068CA4C,
                                   ddsd_DDERR_IMPLICITLYCREATED,
                                   "DDERR_IMPLICITLYCREATED"));
        break;
    case DDERR_NOTPALETTIZED:
        strcpy(temp, DATA_COMPGEN(0x0068CA38,
                                   ddsd_DDERR_NOTPALETTIZED,
                                   "DDERR_NOTPALETTIZED"));
        break;
    case DDERR_UNSUPPORTEDMODE:
        strcpy(temp, DATA_COMPGEN(0x0068CA20,
                                   ddsd_DDERR_UNSUPPORTEDMODE,
                                   "DDERR_UNSUPPORTEDMODE"));
        break;
    case DDERR_NOMIPMAPHW:
        strcpy(temp, DATA_COMPGEN(0x0068CA0C,
                                   ddsd_DDERR_NOMIPMAPHW,
                                   "DDERR_NOMIPMAPHW"));
        break;
    case DDERR_INVALIDSURFACETYPE:
        strcpy(temp, DATA_COMPGEN(0x0068C9F0,
                                   ddsd_DDERR_INVALIDSURFACETYPE,
                                   "DDERR_INVALIDSURFACETYPE"));
        break;
    case DDERR_NOOPTIMIZEHW:
        strcpy(temp, DATA_COMPGEN(0x0068C9DC,
                                   ddsd_DDERR_NOOPTIMIZEHW,
                                   "DDERR_NOOPTIMIZEHW"));
        break;
    case DDERR_NOTLOADED:
        strcpy(temp, DATA_COMPGEN(0x0068C9CC, ddsd_DDERR_NOTLOADED,
                                   "DDERR_NOTLOADED"));
        break;
    case DDERR_NOFOCUSWINDOW:
        strcpy(temp, DATA_COMPGEN(0x0068C9B8,
                                   ddsd_DDERR_NOFOCUSWINDOW,
                                   "DDERR_NOFOCUSWINDOW"));
        break;
    case DDERR_DCALREADYCREATED:
        strcpy(temp, DATA_COMPGEN(0x0068C9A0,
                                   ddsd_DDERR_DCALREADYCREATED,
                                   "DDERR_DCALREADYCREATED"));
        break;
    case DDERR_NONONLOCALVIDMEM:
        strcpy(temp, DATA_COMPGEN(0x0068C988,
                                   ddsd_DDERR_NONONLOCALVIDMEM,
                                   "DDERR_NONONLOCALVIDMEM"));
        break;
    case DDERR_CANTPAGELOCK:
        strcpy(temp, DATA_COMPGEN(0x0068C974,
                                   ddsd_DDERR_CANTPAGELOCK,
                                   "DDERR_CANTPAGELOCK"));
        break;
    case DDERR_CANTPAGEUNLOCK:
        strcpy(temp, DATA_COMPGEN(0x0068C95C,
                                   ddsd_DDERR_CANTPAGEUNLOCK,
                                   "DDERR_CANTPAGEUNLOCK"));
        break;
    case DDERR_NOTPAGELOCKED:
        strcpy(temp, DATA_COMPGEN(0x0068C948,
                                   ddsd_DDERR_NOTPAGELOCKED,
                                   "DDERR_NOTPAGELOCKED"));
        break;
    case DDERR_MOREDATA:
        strcpy(temp, DATA_COMPGEN(0x0068C938, ddsd_DDERR_MOREDATA,
                                   "DDERR_MOREDATA"));
        break;
    case DDERR_EXPIRED:
        strcpy(temp, DATA_COMPGEN(0x0068C928, ddsd_DDERR_EXPIRED,
                                   "DDERR_EXPIRED"));
        break;
    case DDERR_DEVICEDOESNTOWNSURFACE:
        strcpy(temp, DATA_COMPGEN(0x0068C8F4,
                                   ddsd_DDERR_DEVICEDOESNTOWNSURFACE,
                                   "DDERR_DEVICEDOESNTOWNSURFACE"));
        break;
    case DDERR_VIDEONOTACTIVE:
        strcpy(temp, DATA_COMPGEN(0x0068C8DC,
                                   ddsd_DDERR_VIDEONOTACTIVE,
                                   "DDERR_VIDEONOTACTIVE"));
        break;
    default:
        strcpy(temp, DATA_COMPGEN(0x0068C914, ddsdUnknownError,
                                   "Error type unknown"));
        break;
    }

    MessageBeep(0);
    wsprintfA(g_text,
              DATA_COMPGEN(
                  0x0068C8A4,
                  ddsdErrorFormat,
                  "DirectDraw Error (%d):\n\n  '%s'\n\n  File: '%s'\n  Line: %d"),
              ddErr & 0xffff,
              temp,
              file,
              line);
    shutDown(g_text);
    g_inDirectDrawError = 0;
}

// E:\gamedcs\wingraph.cpp:1627
// The row immediately before GetDesktopInfo, which is exactly where the
// Dreamcast roster puts DDRestoreSurfaces once the two source-static
// neighbours (ResizeWindow, DDSetFullScreenStatus) are accounted for, and
// the body says the same thing: five surface slots, each asked IsLost
// (vtable +0x60) and, on DDERR_SURFACELOST, Restore (+0x6c), with the
// first failing HRESULT returned. The three mouse surfaces are
// mousemgr.cpp's, in its declaration order.
//
// Retail RE-READS each global for the Restore call rather than keeping the
// IsLost receiver live, which is what the separate-statement spelling gives.
VA(0x006013a0, 0xC0)  // dc-order-map (the row before GetDesktopInfo) + IsLost/Restore pairs, dc 0x19a114
long ddRestoreSurfaces()
{
    long result;

    if (g_ddsPrimary && g_ddsPrimary->IsLost() == DDERR_SURFACELOST) {
        result = g_ddsPrimary->Restore();
        if (result)
            return result;
    }
    if (g_ddsBack && g_ddsBack->IsLost() == DDERR_SURFACELOST) {
        result = g_ddsBack->Restore();
        if (result)
            return result;
    }
    if (g_ddsMouseSurface
        && g_ddsMouseSurface->IsLost() == DDERR_SURFACELOST) {
        result = g_ddsMouseSurface->Restore();
        if (result)
            return result;
    }
    if (g_ddsMouseSaveSurface
        && g_ddsMouseSaveSurface->IsLost() == DDERR_SURFACELOST) {
        result = g_ddsMouseSaveSurface->Restore();
        if (result)
            return result;
    }
    if (g_ddsMouseScratchSurface
        && g_ddsMouseScratchSurface->IsLost() == DDERR_SURFACELOST) {
        result = g_ddsMouseScratchSurface->Restore();
        if (result)
            return result;
    }
    return 0;
}

// E:\gamedcs\wingraph.cpp:1833
// Retail's row is the real query the Dreamcast port stubbed out to four
// bytes: it fills the desktop-metric triple the two accessors below read,
// which pins the identity independently of the roster order.
VA(0x00601460, 0x52)  // anchor-global (the 0x68c870 triple), dc 0x19a418
unsigned char getDesktopInfo()
{
    // Before normalization (locals): hDesktopDC.
    HDC desktopDC = GetDC(0);
    if (desktopDC) {
        g_unnamed68c870 = GetDeviceCaps(desktopDC, BITSPIXEL);
        g_unnamed68c874 = GetDeviceCaps(desktopDC, HORZRES);
        g_unnamed68c878 = GetDeviceCaps(desktopDC, VERTRES);
        ReleaseDC(0, desktopDC);
        return g_unnamed68c870 == DESKTOP_REQUIRED_BITS_PER_PIXEL;
    }
    return 0;
}

VA(0x006014c0, 0x6)  // exact load of giDesktopWidth, dc 0x19a41c
int getDesktopWidth()
{
    return g_unnamed68c874;
}

// E:\gamedcs\wingraph.cpp:1870
VA(0x006014d0, 0x6)  // exact load of giDesktopHeight, dc 0x19a424
int getDesktopHeight()
{
    return g_unnamed68c878;
}

#if 0  // @carcass

// E:\gamedcs\wingraph.cpp:1876
// Located as WinMain's post-CreateWindow callee; the retail body is a
// 5-byte tail jmp into the DirectDraw-creating 0x6014f0.
#endif  // @carcass

VA(0x006014e0, 0x5)  // anchor-callee, dc 0x19a42c
void initGraphics()
{
    ddInitGraphics();
}

// Retail's DirectDraw setup is the Win32 expansion of DC's DDInitGraphics:
// create the v1 interface, select fullscreen/windowed cooperative mode,
// create the primary/back surfaces, publish the 16-bit channel masks, then
// allocate the three system-memory mouse surfaces. The called vtable slots,
// dimensions, caps and diagnostic line numbers are all direct retail bytes.
// E:\gamedcs\wingraph.cpp:156
VA(0x006014f0, 0x32F)  // wrapper tail-jump + DirectDrawCreate lifecycle
void ddInitGraphics()
{
    if (g_winGraphBusy)
        return;

    HRESULT result = DirectDrawCreate(0, &g_directDraw, 0);
    if (result != DD_OK)
        ddsd(result,
             DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                          "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"),
             0x9a);

    if (g_windowedMode) {
        result = g_directDraw->SetCooperativeLevel(
            g_hwndApp, DDSCL_EXCLUSIVE | DDSCL_FULLSCREEN | DDSCL_ALLOWREBOOT);
        if (result != DD_OK)
            ddsd(result,
                 DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"),
                 0xa0);
        result = g_directDraw->SetDisplayMode(800, 600, 16);
        if (result != DD_OK)
            ddsd(result,
                 DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"),
                 0xa4);
    } else {
        result = g_directDraw->SetCooperativeLevel(g_hwndApp, DDSCL_NORMAL);
        if (result != DD_OK)
            ddsd(result,
                 DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"),
                 0xaa);
    }

    g_ddsPrimary = ddCreateSurface(800, 600, 1);
    if (g_ddClipper) {
        result = g_ddsPrimary->SetClipper(0);
        if (result != DD_OK && result != DDERR_NOCLIPPERATTACHED)
            ddsd(result,
                 DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"),
                 0x6e);
        g_ddClipper->Release();
        g_ddClipper = 0;
    }
    g_ddsPrimary->GetPixelFormat(&g_pixelFormat);

    ResourceManager::setPixelFormat(
        g_pixelFormat.dwRBitMask, g_pixelFormat.dwGBitMask, g_pixelFormat.dwBBitMask);
    SmackManager::setPixelFormat(
        g_pixelFormat.dwRBitMask, g_pixelFormat.dwGBitMask, g_pixelFormat.dwBBitMask);

    if (!g_windowedMode) {
        result = g_directDraw->CreateClipper(0, &g_ddClipper, 0);
        if (result != DD_OK)
            ddsd(result,
                 DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"),
                 0x81);
        result = g_ddClipper->SetHWnd(0, g_hwndApp);
        if (result != DD_OK)
            ddsd(result,
                 DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"),
                 0x86);
        result = g_ddsPrimary->SetClipper(g_ddClipper);
        if (result != DD_OK)
            ddsd(result,
                 DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"),
                 0x8b);
    }

    g_ddsBack = ddCreateSurface(800, 600, 0);

    DDSURFACEDESC surfaceDesc;
    memset(&surfaceDesc, 0, sizeof(surfaceDesc));
    surfaceDesc.dwSize = sizeof(surfaceDesc);
    surfaceDesc.dwFlags = DDSD_CAPS | DDSD_HEIGHT | DDSD_WIDTH;
    surfaceDesc.ddsCaps.dwCaps =
        DDSCAPS_OFFSCREENPLAIN | DDSCAPS_SYSTEMMEMORY;
    surfaceDesc.dwHeight = 64;
    surfaceDesc.dwWidth = 64;
    result = g_directDraw->CreateSurface(
        &surfaceDesc,
        static_cast<IDirectDrawSurface**>(
            static_cast<void*>(&g_ddsMouseSurface)),
        0);
    if (result != DD_OK)
        ddsd(result,
             DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                          "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"),
             0x28b);

    DDCOLORKEY colorKey;
    unsigned long color = rgBto16(0, 255, 255);
    colorKey.dwColorSpaceLowValue = color;
    colorKey.dwColorSpaceHighValue = color;
    g_ddsMouseSurface->SetColorKey(DDCKEY_SRCBLT, &colorKey);

    memset(&surfaceDesc, 0, sizeof(surfaceDesc));
    surfaceDesc.dwSize = sizeof(surfaceDesc);
    surfaceDesc.dwFlags = DDSD_CAPS | DDSD_HEIGHT | DDSD_WIDTH;
    surfaceDesc.ddsCaps.dwCaps =
        DDSCAPS_OFFSCREENPLAIN | DDSCAPS_SYSTEMMEMORY;
    surfaceDesc.dwHeight = 64;
    surfaceDesc.dwWidth = 64;
    result = g_directDraw->CreateSurface(
        &surfaceDesc,
        static_cast<IDirectDrawSurface**>(
            static_cast<void*>(&g_ddsMouseSaveSurface)),
        0);
    if (result != DD_OK)
        ddsd(result,
             DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                          "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"),
             0x29c);

    memset(&surfaceDesc, 0, sizeof(surfaceDesc));
    surfaceDesc.dwSize = sizeof(surfaceDesc);
    surfaceDesc.dwFlags = DDSD_CAPS | DDSD_HEIGHT | DDSD_WIDTH;
    surfaceDesc.ddsCaps.dwCaps =
        DDSCAPS_OFFSCREENPLAIN | DDSCAPS_SYSTEMMEMORY;
    surfaceDesc.dwHeight = 128;
    surfaceDesc.dwWidth = 128;
    result = g_directDraw->CreateSurface(
        &surfaceDesc,
        static_cast<IDirectDrawSurface**>(
            static_cast<void*>(&g_ddsMouseScratchSurface)),
        0);
    if (result != DD_OK)
        ddsd(result,
             DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                          "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"),
             0x2aa);
}

// E:\gamedcs\wingraph.cpp:1882
// AppWndProc's WM_PAINT callee, called (hwnd, NULL) - the homm2 shape; a
// four-byte WinCE stub on Dreamcast, a real 112-byte paint here. An empty
// update rectangle from BeginPaint is widened to the whole client area
// before the blit, and the blit is skipped on a degenerate rectangle.
VA(0x00601820, 0x70)  // anchor-callee (AppWndProc WM_PAINT), dc 0x19a440
int appPaint(void* hwnd, void* hdc)
{
    PAINTSTRUCT ps;
    RECT clientRect;
    HWND window = static_cast<HWND>(hwnd);

    BeginPaint(window, &ps);
    if (!ps.rcPaint.right || !ps.rcPaint.bottom) {
        GetClientRect(window, &clientRect);
        ps.rcPaint = clientRect;
    }
    if (ps.rcPaint.right - ps.rcPaint.left > 0
        && ps.rcPaint.bottom - ps.rcPaint.top > 0)
        robAppBlit(&ps.rcPaint);
    EndPaint(window, &ps);
    return 1;
}

// E:\gamedcs\wingraph.cpp:1916
// AppExit's first callee (kbwin 0x4f7fa0; homm2 AppExit order). Retail
// body is a 5-byte tail jmp into 0x6018a0 - the WING arm of homm2's
// wrapper is gone, only the DD path survives.
VA(0x00601890, 0x5)  // anchor-callee, dc 0x19a444
void cleanUpWinGraphics()
{
    ddCleanUpWinGraphics();
}

// The cleanup worker follows the same DirectDraw lifecycle as the mature
// HoMM2 sibling, extended by Heroes III's three mouse surfaces. Retail's
// vtable slots independently fix every interface generation: IDirectDraw
// RestoreDisplayMode/SetCooperativeLevel and IDirectDrawSurface::SetClipper.
// E:\gamedcs\wingraph.cpp:1476
VA(0x006018a0, 0x100)  // wrapper tail-jump + DirectDraw release chain
void ddCleanUpWinGraphics()
{
    if (g_directDraw) {
        g_directDraw->RestoreDisplayMode();

        if (g_ddClipper) {
            if (g_ddsPrimary) {
                HRESULT result = g_ddsPrimary->SetClipper(0);
                if (result != DD_OK && result != DDERR_NOCLIPPERATTACHED)
                    ddsd(result,
                         DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                                      "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"),
                         0x378);
            }
            g_ddClipper->Release();
            g_ddClipper = 0;
        }

        if (g_ddsPrimary) {
            g_ddsPrimary->Release();
            g_ddsPrimary = 0;
        }
        if (g_ddsBack) {
            g_ddsBack->Release();
            g_ddsBack = 0;
        }
        if (g_ddsMouseSurface) {
            g_ddsMouseSurface->Release();
            g_ddsMouseSurface = 0;
        }
        if (g_ddsMouseSaveSurface) {
            g_ddsMouseSaveSurface->Release();
            g_ddsMouseSaveSurface = 0;
        }
        if (g_ddsMouseScratchSurface) {
            g_ddsMouseScratchSurface->Release();
            g_ddsMouseScratchSurface = 0;
        }

        HRESULT result = g_directDraw->SetCooperativeLevel(
            g_hwndApp, DDSCL_NORMAL);
        if (result != DD_OK)
            ddsd(result,
                 DATA_COMPGEN(0x0068c87c, wingraphSourceFile,
                              "C:\\Dev\\Heroes 3 Exp 2\\Game\\WINGRAPH.CPP"),
                 0x396);
        g_directDraw->Release();
        g_directDraw = 0;
    }
}

// E:\gamedcs\wingraph.cpp:1922
// Located by shape: fastcall bool(int) that early-outs on the 0x6989d4
// flag, compares the argument against bWindowedMode (0x6987b8), calls the
// adjacent static DDSetFullScreenStatus (0x601a00) and
// gpWindowManager->UpdateScreen(0,0,800,600); sole caller is AppCommand's
// KBWIN_MENU_FULLSCREEN arm (homm2 lineage).
// Before normalization (locals): bFullScreenOn, bChanged.
VA(0x006019a0, 0x5a)  // anchor-callee, dc 0x19a454
unsigned char setFullScreenStatus(int fullScreenOn)
{
    if (g_unnamed6989d4)
        return 0;
    if (fullScreenOn == g_windowedMode)
        return 1;

    unsigned char changed = ddSetFullScreenStatus(fullScreenOn);
    g_windowManager->updateScreen(0, 0, 800, 600);
    if (fullScreenOn)
        g_mouseManager->update(1);
    writePrefs();
    return changed;
}

// E:\gamedcs\wingraph.cpp:1712 - the mode change itself, emitted straight
// after its wrapper, which is the file-static emission pattern the header
// note already records. The whole body is one linear sequence and the
// retail bytes read it out: grab the screen into an 800x600 scratch,
// tear DirectDraw down, re-query the desktop, restyle the window, bring
// DirectDraw back up, remap and blit the scratch back, then reset the
// pointer and, in full screen, re-place the window.
//
// Two things worth reading twice. GetDesktopInfo is EXPANDED here (its
// GetDC / three GetDeviceCaps / ReleaseDC block and the `== 16` compare
// are inline) exactly as it is in DDResetDisplayMode; and the colour-mask
// triple is saved BEFORE the teardown and compared AFTER the rebuild, so
// the remap only runs when DirectDraw came back in a different pixel
// format - which is what bitmap16.h's own note about `0x7e0 ? 6 : 5`
// describes from the other end.
// Residual (94.58%): register allocation only - all 14 branches and all 31
// calls agree, and 23 of 28 blocks are byte-exact. What is left is which
// scratch register each of the three mask compares and the Grab/Draw
// argument loads land in (retail runs Width through ESI where we use ECX,
// and rotates EAX/ECX/EDX one place through the mask block), plus the
// resulting `push esi` save point. Three source levers were measured and
// two paid: hoisting GetDesktopInfo into a named local, which is what makes
// the desktop query UNCONDITIONAL and puts iStatus in its own frame slot
// (85.4440 -> 91.8531, and it is what closes every branch); reading
// iWindowX/iWindowY into locals ABOVE the `if (!bWindowedMode)`, which is
// where retail loads them (91.8567 -> 94.5813); and declaring the three
// saved masks blue/green/red rather than red/green/blue, worth 0.0036.
// Before normalization (locals): iNewStatus, iStatus, bChanged, bDesktopOk.
VA(0x00601a00, 0x31C)  // anchor-caller (SetFullScreenStatus) + dc order, dc 0x19a234
unsigned char ddSetFullScreenStatus(int newStatus)
{
    int status = newStatus;
    Bitmap16Bit savedScreen(800, 600);

    if (g_windowedMode == newStatus)
        return 1;
    if (g_winGraphBusy)
        return 0;

    unsigned char changed = 1;
    g_winGraphBusy = 1;
    if (g_mp3Stream)
        AIL_pause_stream(g_mp3Stream, 1);
    videoPause();
    Sleep(100);

    unsigned long savedBlue = 0;
    unsigned long savedGreen = 0;
    unsigned long savedRed = 0;
    if (!g_closingApp) {
        Bitmap16Bit* screen = g_windowManager->m_screenBitmap;
        savedScreen.grab(screen->m_map, 0, 0, screen->m_width, screen->m_height,
                         screen->m_pitch);
        savedBlue = g_colorMaskBlue;
        savedGreen = g_colorMaskGreen;
        savedRed = g_colorMaskRed;
    }

    ddCleanUpWinGraphics();
    g_winGraphBusy = 0;

    unsigned char desktopOk = getDesktopInfo();
    if (status == 0 && !desktopOk) {
        status = 1;
        changed = 0;
    }
    g_windowedMode = status;

    if (g_windowedMode) {
        SetWindowLong(g_hwndApp, GWL_STYLE, WS_POPUP | WS_VISIBLE);
        SetWindowLong(g_hwndApp, GWL_EXSTYLE, WS_EX_TOPMOST);
    } else {
        SetWindowLong(g_hwndApp, GWL_STYLE, WINDOWED_WINDOW_STYLE);
        SetWindowLong(g_hwndApp, GWL_EXSTYLE, 0);
    }

    ddInitGraphics();
    g_winGraphBusy = 1;

    if (!g_closingApp) {
        if (savedBlue != g_colorMaskBlue || savedGreen != g_colorMaskGreen
            || savedRed != g_colorMaskRed) {
            savedScreen.remap(savedGreen == GREEN_MASK_565
                                  ? BITMAP_GREEN_BITS_565
                                  : BITMAP_GREEN_BITS_1555);
            ResourceManager::remapGraphics();
        }
        Bitmap16Bit* screen = g_windowManager->m_screenBitmap;
        savedScreen.draw(0, 0, 800, 600, screen->m_map, 0, 0, screen->m_width,
                         screen->m_height, screen->m_pitch, false);
    }

    g_mouseManager->reset();
    g_mouseManager->loadFrame(g_mouseManager->m_frame);

    int windowX = g_windowX;
    int windowY = g_windowY;
    if (!g_windowedMode) {
        RECT windowRect;
        windowRect.left = 0;
        windowRect.top = 0;
        windowRect.right = 800;
        windowRect.bottom = 600;
        AdjustWindowRectEx(&windowRect, WINDOWED_WINDOW_STYLE, 1, 0);
        MoveWindow(g_hwndApp, windowX, windowY,
                   windowRect.right - windowRect.left,
                   windowRect.bottom - windowRect.top, 1);
        writePrefs();
    }

    kbChangeMenu(0);
    videoRealignBuffers();
    if (g_mp3Stream)
        AIL_pause_stream(g_mp3Stream, 0);
    videoResume();
    Sleep(100);
    g_winGraphBusy = 0;
    return changed;
}
